### ISSUE TITLE
v2.0.1 RE1 Jill softlock and sequence issue

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#100]
v2.0.1
R410-0000-Z1HHHMZL103
Jill 

1) After killed plant boss , if entered room 405 ,it will trigger Wesker talk to Jill and soft lock the game , chimera attacked Jill to die or crashed the game.

405:1 (0x194F4) [BEE,19,0,0,0] becomes [CHIMERA,0,0,0,0]

2) 4 crests already in there , cannot insert again.
Connected 11A:1 [WIND CREST, MOON CREST, STAR CREST, SUN CREST] to 201:3

3) game crashed if  :
Haven't trigger Barry encountered Jill in the cave (room 308) BEFORE found Enrico 
(Jill haven't met Barry in 308 -> found Enrico -> back to 308 ->crash)

4) crashed when using debug jump to the rooms :
a) opened the helmet key doors BEFORE killed plant boss. 
b) Before killed plants boss , jump to 2nd round mansion rooms. (library ,elevator, kitchen etc)

**Comment by IntelOrca** [comment]
1. Moved to #102
2. Moved to #103
3. Not sure how to reproduce this
4. Unfortunately nothing I can do about this. The debug menu does not let you teleport to 600 / 700 stages (Mansion 2).

**Comment by otamega72** [comment]
3. No need to do anything for this. Players must aware game will crash if found Enrico before met Barry in the Cave. When player entered Enrico room before Barry , turn back and move to room 308. 

But if you haven't killed 2nd giant snake , it might not trigger Barry in the cave . To prevent the crash mentioned , you have to kill 2nd giant snake , before to 308 and Enrico.

4. In vanilla version , crash will happen if you enter helmet key rooms before killed plants boss. 
(10A->119 , 201->215 , 20B->20C)

But I found that in this seed R410-0000-Z1HHHMZL103 , where 2nd giant snake room set in hall dressing room , no crash to enter the room before killed plants boss. 
(106->20C)  (in log_pl1.txt  is Connected 106:1 [ARMOR KEY] to 70C:0)

So maybe No.4 is not a issue.
