### ISSUE TITLE
RE 1 - Logic problems

### ISSUE THREAD

**Issue by CesarMartins12** [IntelOrca/biorand#101]
Hi, I'm playing the rando a few days, and I rolled 3 seeds unbeatable. 

I guess we're having a logic problem because acording the spoiler log the Items who can unlock me are fter them. 

In my pov I need the Crests or the Chemical

The crests open the second part of the mansion and the chemical open more checks at the plant room. But they're unaccesible. 
I'll upload the spoiler log here for your info.

Btw I have the helmet key, but as a friend of me Soket reported if you use the key without defeat the Plant 42 the game crashes. 

[log_pl1.txt](https://github.com/IntelOrca/biorand/files/10287662/log_pl1.txt)

**Comment by IntelOrca** [comment]
Yes, that said I think Chris does not have this issue. Have you had any successful Chris runs? Alternatively door randos should also be okay.

**Comment by CesarMartins12** [comment]
No, I never tried Chris runs, I'll try.

Never played as Chris but I'll try and send you some report here
