### ISSUE TITLE
RE 2, room 307, softlock caused by swap with Irons

### ISSUE THREAD

**Issue by Atreid3s** [IntelOrca/biorand#108]
Hi there,

Got this bug twice in both scenarios with the randomize cutscene characters. Claire is replaced with Irons, game got stuck with the Iron's s walk and aiming animation and he gets stuck with the corner while Sherry is watching.

![Captura](https://user-images.githubusercontent.com/121364437/209453300-bb4b4407-e7c8-4819-9450-9144fcac7ee8.JPG)

Also a quick question for curiosity is Ada player swap possible or is there a technical problem to add her?

**Comment by IntelOrca** [comment]
> Also a quick question for curiosity is Ada player swap possible or is there a technical problem to add her?

She is more difficult due to her having a special model to deal with her dress, but I think progress is being made.
