### ISSUE TITLE
v 2.0.3 RE1 Chris : crash 10b

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#109]
R410-9NG0-Z1YUNJZL193
Chris
Connected 10A:1 to 10B:0
10B:0 (0x113DC) [ZOMBIE GROUNDSKEEPER,4,0,0,0] becomes [TYRANT 2,0,0,0,0]
    
enter 10B ->  spray mist , sound : “barry ?!”  ->  crashed.

**Comment by IntelOrca** [comment]
Duplicate of #105
