### ISSUE TITLE
Sherry's neutral stance aims the gun "down".

### ISSUE THREAD

**Issue by RianQuenlin** [IntelOrca/biorand#115]
Any shot Sherry fires with a weapon that can be aimed (handgun, submachine gun) will miss outside of close range (which is about ten feet) unless she is aiming upwards, which makes her shoot forwards.

**Comment by Snipzu** [comment]
Hey there! 
Snipz here that worked on Sherry.

Unfortunately Sherry is smaller than Claire, the game is programmed for Claires guns to hit at a certain Y value height of her arms.
We could potentially fix this in the future.
But unfortunately the only way to get around it is aiming up as her at the moment.

Apologies for the inconvenience!

**Comment by RianQuenlin** [comment]
Until that can be done I'd have the randomizer state that Sherry needs to aim up to hit things in front of her. She's already difficult due to her speed.
