### ISSUE TITLE
Infinite cutscene loop

### ISSUE THREAD

**Issue by ImKatastrophe** [IntelOrca/biorand#116]
Seed: R521-FHAJ-ZJC5JEZL314

Scenario: Leon A
Character: Barry
Room: Circular platform room in the lab with 3 walkways.

Issue: Once I triggered the cutscene where Ada points her gun at Leon in the A scenario, Irons came out, and he walked slowly towards the camera... But he just kept walking, infinitely, never reaching his destination. I couldn't skip the cutscene either.

**Comment by IntelOrca** [comment]
Haven't been able to reproduce
