### ISSUE TITLE
Door softlock

### ISSUE THREAD

**Issue by ImKatastrophe** [IntelOrca/biorand#118]
Seed: R521-MUTP-ZJQJ62JL343

Issue: Softlocked between doors

I entered Kendo's gunshop from a random door, and because I triggered the Kendo conversation it says 'the streets are no longer safe', so the door I came through became useless. The only other door the shop lead to is the guard bunk/rest room where you find the Magnum in Leon A.. which is a single door room. So yes, softlocked between kendo's gunshop and that room.

**Comment by IntelOrca** [comment]
Was this Leon or Claire?

**Comment by IntelOrca** [comment]
I can't reproduce this, I have a feeling you might have been using Leon A for a rando that was generated for Claire A / Leon B.

**Comment by IntelOrca** [comment]
Unable to reproduce and lack of information
