### ISSUE TITLE
v2.1.3 RE1 Jill crashed if met Enrico before Barry in the cave

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#121]
BioRand 2.1.3
    Seed: R512-225N-Z9UQLYZL1ZZ
    Player: 1 Jill
Connected 20E:2 [SHEILD KEY] to 115:1
Connected 115:0 to 308:1

Enter room 115 , trigger the ceiling downward , cannot open the other door , must return back to room 20E.
After that back to 115 , ceiling on top , not moving , open the door to room 308 , crash.
***
Ok , I knew why it crashed :
Connected 101:1 [ARMOR KEY] to 30A:0 (locked #148)
if you trigger Enrico (30A) before met Barry in the cave (308) , game will crash.

**Comment by IntelOrca** [comment]
I think have disabled the cutscene now which should hopefully fix this.
