### ISSUE TITLE
RE 1, room 30C, item not present

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#123]
BioRand 2.1.3
    Seed: R510-225N-Z9UQLYZL1ZZ
    Player: 0 Chris

1) Sun Crest not found
(room 50E 3 items , randomizer generate 4 items)

Placing key item (FLAMETHROWER x1) in 50E:132 -->ok
Placing key item (MO DISK x1) in 50E:3 --> ok
Placing key item (SUN CREST x1) in 50E:5 --> (not found ,  replaced by green herb)
Replaced 50E:2 [GREEN HERB x1] with 50E:2 [GREEN HERB x1]

2) Star Crest not found 
(room 30c 1 item , randomizer generate 2 items)

Placing key item (STAR CREST x1) in 30C:3 --> not found
Placing key item (DORM KEY 003 x1) in 30C:2 -->ok

**Comment by IntelOrca** [comment]
The sun crest was on the bookshelf.
![image](https://user-images.githubusercontent.com/1482259/211155713-012f7508-a46d-45a1-9ed7-b0f6bdf2f9c8.png)

Room 30C has an ink ribbon, but I don't know what triggers it to spawn. I will make the item low priority so it isn't a key.
