### ISSUE TITLE
Door Crash

### ISSUE THREAD

**Issue by PxDeenon** [IntelOrca/biorand#126]
Seed: R420-NZFF-ZTUH2PXLLB3

Claire B, room where MrX first appears, once cutscenes appeared i was unable re enter the room
Used debug menu to teleport through it, made 2 room progress an another door bugged, can't tele cause it was progress so dunno what behind the door, room being the surveillance lab safe room

**Comment by PxDeenon** [comment]
not looking for fix btw just reporting so you guys can sort the errors out in future, ggs

**Comment by IntelOrca** [comment]
Which version were you using? The seed suggests an old version, so it may have already been fixed.
