### ISSUE TITLE
Firing the grenade launcher (explosive) crashes the game

### ISSUE THREAD

**Issue by kendosrando** [IntelOrca/biorand#127]
Seed: R520-X7QG-ZJEC3KPKKE01 
I also tried kendo, Leon, and barry, same crash as well

**Comment by kendosrando** [comment]
only the G.grenade leads to crash, flame and acid are ok

**Comment by kendosrando** [comment]
now even claire A has the same problem, only reinstalling the v2.13 can fix it

**Comment by IntelOrca** [comment]
Yeah, sorry we are aware of this issue. It is a regression from trying to enable Leon's weapons for Claire. I will investigate the issue this evening.

**Comment by kendosrando** [comment]
Don't be sorry and especially after you guys make so much more effort that brings this game so alive, Bawk was right, you guys are truly dream maker
