### ISSUE TITLE
RE 2, room 404, Claire softlock when partner is not Sherry

### ISSUE THREAD

**Issue by PxDeenon** [IntelOrca/biorand#131]
Seed: R520-LCN1-ZTNE26JLL631
![image](https://user-images.githubusercontent.com/122243447/211421954-f6a68d8a-22df-4223-95c0-4a8dc2f9eee6.png)
![image](https://user-images.githubusercontent.com/122243447/211421984-1d969955-0ec6-4fbc-965d-2ccc86478bb5.png)
![image](https://user-images.githubusercontent.com/122243447/211422037-3ddcdf2c-593d-4209-bf63-74e9f4e3a212.png)
attempted to reset room via debug room tele and once re entering same problem occurs

**Comment by IntelOrca** [comment]
Thanks, looks like I need to prevent Sherry from being swapped in this room.

**Comment by PxDeenon** [comment]
glad i can help orca! <3
