### ISSUE TITLE
Screen freezes after Leon Meets Ada Cutscene

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#133]
Seed: R521-8HV4-ZTXV3K5LLC03

![Screenshot 2023-01-10 164604](https://user-images.githubusercontent.com/122331724/211669240-f7ce8bd3-03ce-4f4f-9cbb-005651685864.png)
There is a zombie in the room as you meet the Leon and Ada cutscene and causes Leon's character to get bit during cutscene

**Comment by IntelOrca** [comment]
I don't think this happens anymore.
