### ISSUE TITLE
one enemy always found out of bounds in this area

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#135]
![Screenshot_20230110_075116](https://user-images.githubusercontent.com/122331724/211692699-fa220799-4a1e-4436-847b-aa07f5c65ab7.png)
Seed: R521-XEA1-ZTXV3K5LLB33

**Comment by JonSolo11** [comment]
I also had this happen in the bus, the dark room, and b scenario save room where you have to push the box down the lift. a dog spawned between floors and could still bite me.

**Comment by IntelOrca** [comment]
Most of these were fixed, please create a new issue if you find any more.
