### ISSUE TITLE
Shooting The G-launcher Crashes Game, Period! (RE2)

### ISSUE THREAD

**Issue by Hemavore** [IntelOrca/biorand#136]
Seed: R520-HUNK-ZTV85LZLL641

**Comment by IntelOrca** [comment]
Already fixed in dev. builds

**Comment by Hemavore** [comment]
I Just Figured Out that it Does It When You Are playing with the Hunk Skin. Anyway, Happy To Know That It's Fixed And I Can't Wait For Updated Build. Cheers!!!
