### ISSUE TITLE
RE 1, room 10F, Rebecca disappears after leaving potentially causing softlock

### ISSUE THREAD

**Issue by Hemavore** [IntelOrca/biorand#137]
Seed: R510-T002-Z9Z93VYL1641

I Want To Give More Info About The Rebecca Practicing Issue. After Allowing Her To Practice. I Left For About 5-10 Rooms Worth Of Exploration Returned Expecting Progression. And..... There Was Nobody There. The Room Was Empty Effectively Killing Any Chance Of Opening The False Wall.

**Comment by IntelOrca** [comment]
Not easy to fix Rebecca disappearing, but I can at least stop the item from ever being a key item.
