### ISSUE TITLE
Suggestion: Add Resident Evil 3 To BioRand And Eventually Get All 3 Games To Be In A Run (My Ultimate Lifelong Fantasy, Seriously)

### ISSUE THREAD

**Issue by Hemavore** [IntelOrca/biorand#138]
I Am Aware of How Complicated A Randomizer Can Be Especially Making It Fully Functional With Little To No Issues However My Suggestion Is At Least For Starters If The Trilogy Ever Is Made Possible To BioRand. To Mitigate SoftLocking You Could Have Generated Segments Pertain Specifically To 1 Game At A Time. Allowing BioRand To Then Pick A Room And Connect It To The Next Segment/RE Game. End Goal Would Be To Launch Resident Evil 3 With BioRand And Hopefully Have The Potential Size of All 3 RE Games Worth Of Rooms And Enemies/Weapons Etc...

**Comment by IntelOrca** [comment]
RE 3 will eventually be supported.
