### ISSUE TITLE
RE 1, room 302 battery lift can corrupt inventory

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#141]
BioRand 2.1.4
    Seed: R510-E2Q6-Z9UQLYZL1ZZ1
    Player: 0 Chris

Take Room 300 lift will change Chris's Inventory to Jill's . It will cause Room 308 missing flamethrower and cannot open the door.
If you use debug menu to add flamethrower and put on the board , game crashed.
![Capture-02](https://user-images.githubusercontent.com/120957601/211981486-e05f7acc-8974-4fd7-abb2-8e7c7ad15fd9.JPG)
![Capture](https://user-images.githubusercontent.com/120957601/211981506-ee078018-fa1e-4a7c-91ce-557531239cf3.JPG)

**Comment by IntelOrca** [comment]
Does your player image in the inventory also change?

I have hit this as Jill but never Chris, and I have never got to the bottom of why it happens.

**Comment by otamega72** [comment]
1) Step in lift room 302
![Capture-02](https://user-images.githubusercontent.com/120957601/212035748-a823a35f-7538-4e3a-9056-b074a1fff987.JPG)

2) It is Chris's Inventory 
![Capture03](https://user-images.githubusercontent.com/120957601/212037581-2ce7cc14-faf1-4a2d-9a1c-fe5944fc3e0b.JPG)

3) Take the lift to room 300 ,PC still is Chris , but 
![Capture05](https://user-images.githubusercontent.com/120957601/212037914-148717c9-0ed9-4aa7-8b25-59a86a4b6742.JPG)

4) Inventory changed to Jill's
![Capture06](https://user-images.githubusercontent.com/120957601/212038142-9738a5c5-8a82-428c-9bb1-7dc38b68b6fa.JPG)

5) PC is Chris but Inventory is Jill's cannot open this door ,even debut adding flamethrower , game crashed when door opened.
![Capture](https://user-images.githubusercontent.com/120957601/212038694-2c1c4919-6253-40bd-87af-caecbbd7971b.JPG)

**Comment by IntelOrca** [comment]
I was waiting for reports before I acted. I don't know how to fix the issue, so it looks like I will have to prevent the lift from being used and not spawn the battery.

**Comment by Hemavore** [comment]
So If The Battery Doesn't Spawn, How Will You Make It Possible To Use The Elevator At The End Of The Game? Are You Just Going To Remove That 2nd Battery From The Pool? I Assume The 2nd Battery Would Just Have To Be In The Original Spot Five Steps Away From The Elevator Terminal?

**Comment by IntelOrca** [comment]
Not randomizing the battery could work. A player could softlock if they place the single only battery into the lift. But I might be able to simply disable the lift battery slot from being interactable.
