### ISSUE TITLE
Possibility to include Resident Evil 3 aswell?

### ISSUE THREAD

**Issue by LL187** [IntelOrca/biorand#146]
Hi IntelOrca,

because of the simplicity of your Randomizer interface and ease of use i started playing them regulary and enjoy them quite a bit,
so i was just curious to ask if there are any Plans to expand the Tool to also include RE3 with those neat features in the future.

Sorry in advance if this has been asked before.

Thanks for your efforts and your time

**Comment by IntelOrca** [comment]
Yes, RE 3 will happen eventually.
