### ISSUE TITLE
RE2 Leon B: Fastest Soft Lock: Save File Available On Google Drive Link

### ISSUE THREAD

**Issue by Hemavore** [IntelOrca/biorand#148]
Seed: R521-M92F-ZJZ93LZLL641

This B Scenario Seed Has 2 Options For Potential Progression But I Need A Heart Key For The RPD Office Or I Need A Manhole Opener For The Kennels. Neither Are Available. There Are Maybe 10-15 Rooms In This Scenario That Are Available Before The SoftLock Which Is Pretty Crazy!

Save File  Leon B
https://drive.google.com/file/d/11GPDnBli0e866ram0vNAtYDJvYkShjdv/view?usp=share_link

**Comment by Hemavore** [comment]
Imagine Playing Sherry On A Really Hard (A Scenario) Only To Be Given The Middle Finger By The RNG Gods.

**Comment by IntelOrca** [comment]
This may be different to yours, but otherwise the log says:
```
        Placing key item (ManholeOpener x1) in 403:19
        Placing key item (DiamondKey x1) in 60D:2
        Placing key item (PlatformKey x1) in 60E:4
        Placing key item (HeartKey x1) in 60E:5
        Placing key item (ClubKey x1) in 704:3
        Placing key item (JointPlugBlue x1) in 508:2
        Placing key item (JointPlugRed x1) in 60D:3
        Placing key item (FuseCase x1) in 10C:5
```

Have you checked all the items in room 403 and 60E. Are those rooms accessible?

**Comment by Hemavore** [comment]
It Wasnt Accessible and i gave up and started a different run Because U Realeased 1.5 an hour ago
i just regenerated the seed in 1.5 and loaded my save its wildly different and the log matches yours

**Comment by Hemavore** [comment]
Im going to redownload 1.4 and see if i can recreate the condition

**Comment by Hemavore** [comment]
i Was Able To Recreate It Heres The Proof Also Since This issue isn't relevant to the new build i suppose this issue can be closed i promise ill find you more issues. i got you
![log](https://user-images.githubusercontent.com/122418252/212184088-26db672a-3cd8-438e-b470-e4c2d37feb5c.PNG)

**Comment by IntelOrca** [comment]
Hmm, usually if it doesn't spawn a key item - the door is not connected. I would have to rollback and investigate.

**Comment by IntelOrca** [comment]
Re-open if this happens again
