### ISSUE TITLE
Balancing: (Random Enemy Placement) Maybe You Could Add An Option To Have Enemy Placement In Save Rooms? This Was Unfair! (See Pic)

### ISSUE THREAD

**Issue by Hemavore** [IntelOrca/biorand#149]
![Trap](https://user-images.githubusercontent.com/122418252/212173625-6846f29a-128f-442f-a84d-63bcaeb77e4a.PNG)

**Comment by JonSolo11** [comment]
Honestly, I would just turn this off. It just felt so wrong.

**Comment by Hemavore** [comment]
The Thing Is I Want It On It Made The Game Feel Fresh Also That Picture Of Me Dead Has A Nice Back Story That I Will Remember Because Just Before I Entered This Save Room I Dodged 9 Lickers In  RPD Main Hall It Was Scary But Awesome, Unfortunately When I Entered Here It Was Over

**Comment by IntelOrca** [comment]
Random enemy placement is currently experiemental. More settings to control it will be added.
