### ISSUE TITLE
Add inventory expansion option

### ISSUE THREAD

**Issue by JonSolo11** [IntelOrca/biorand#150]
I would like to be able to toggle the 2 additional inventory slots from the beginning. mostly just to save time from backtracking. 

also, if you can create door skip, I would be so happy. Even if it just temporarily speeds up the game.

**Comment by JonSolo11** [comment]
lastly, a lot of the voice lines from re1 (at least) are very quiet.

**Comment by JonSolo11** [comment]
I surprisingly didnt know that. Thank you

**Comment by IntelOrca** [comment]
@JonSolo11 are you happy with that workaround? I don't think making the rando give you easy stuff like ammo, weapons or inventory at the start is particularly necessary when you can just use debug menu to get it.

As for the door skip, I don't think it can be made faster. The RE 1 is a lot quicker, but HD textures can slow it down.

**Comment by JonSolo11** [comment]
its not really about making it easier. just less backtracking. Was just a thought. debug is also fine.
