### ISSUE TITLE
RE 1, room 103, crash during Mansion 2

### ISSUE THREAD

**Issue by Soket13** [IntelOrca/biorand#152]
Seed: R510-Y58M-X4Y21MY11000

Jill seed, after Guardhouse Plant 42 events returning to Mansion, a Crash happen back to 103F going for the Tiger Statue room.
Enemy respawn maybe?

On the 1.14 branch i got a crash after the same events on the 108 L Passage - Dogs window - maybe same problem
![image](https://user-images.githubusercontent.com/68131733/212204708-2f510153-c26d-409f-9a64-d96d2ce7610b.png)

And btw nice work about the development for this rando!

**Comment by IntelOrca** [comment]
If this issue happens again, please re-open with a saved game just before the crash happens.
