### ISSUE TITLE
RE 2, room 201, crash at licker window with random enemies enabled on Claire

### ISSUE THREAD

**Issue by Atreid3s** [IntelOrca/biorand#153]
Hi there, i couldn't take a picture with this issue because it insta crashed the game but the game crashed in the window with a licker. I guess is related to the new experimental NPC placement but just reporting it. The NPCs were zombies in this room.

BioRand 2.1.5
Seed: R521-87WP-XZ6J4BX3L603

EDIT1: I tried with another seed and crashed again. I managed to avoid the crash running straight to the door and quickly open it.

BioRand 2.1.5
Seed: R521-NV0R-XZ6J4BX3L653

https://images.squarespace-cdn.com/content/v1/55ef0e29e4b099e22cdc9eea/1484195488349-7E3UQMEO0WT77M32RV6W/Uh+OH.jpg

**Comment by Atreid3s** [comment]
Apologies for the title mistakes, english is not my native language.

**Comment by IntelOrca** [comment]
@Atreid3s don't worry about that, I am just making the titles consistent and the same as what I will write in the changelog.
