### ISSUE TITLE
RE 2, room 200, glitch when enemy attacks during cutscene

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#154]
Seed: R521-ALFX-ZTK82K9LLB17

Dogs attack you when you first enter the RPD main hall during the cutscene and causes the game to glitch and not allow you to go into your menu or use your weapon or let the enemies attack you again until you reload the room using debug menu
![Screenshot_20230112_084646](https://user-images.githubusercontent.com/122331724/212218322-41d870d4-f051-41d5-8982-290ce70992f6.png)

**Comment by ShannonCobannon** [comment]
![Screenshot_20230112_085139](https://user-images.githubusercontent.com/122331724/212218871-5e7e0faf-6285-47b5-8bc4-f5df81401f16.png)

**Comment by JonSolo11** [comment]
I had this happen at the final boss as well. but I also couldnt move.
