### ISSUE TITLE
crashed on ada annette cut scene in sewers and other issues in comments

### ISSUE THREAD

**Issue by JonSolo11** [IntelOrca/biorand#156]
Seed: R520-V49F-X7HHHMZLL001

**Comment by JonSolo11** [comment]
I cant remember if this was all in this seed because I did a few tonight but 

spiders in the crow hallway could attack before the glass was broken but they couldnt be damaged. 

g1 spawned in the magnum room. I killed him and he just walked around in circles while still being able to be auto aimed. He did not attack though. 

blue card key stayed in inventory after use. 

dogs attacking while watching the cut scene opening the shutter in the lab. multiple instances of dogs attacking right as the door closing animation is over. 

wesker audio too quiet at times. 

ivy out of bounds in dark room.

licker out of bounds in bus. 

I did about 5 runs on twitch today so if you need video of any of this, I should be able to pull the seed and clips if needed.

**Comment by IntelOrca** [comment]
> g1 spawned in the magnum room. I killed him and he just walked around in circles while still being able to be auto aimed. He did not attack though.

This is expected, he would normally jump off the bridge - but since we aren't in the correct room this logic does not work.
