### ISSUE TITLE
Left room 403 as leon, next room was ada. Going back did not reset inventory.

### ISSUE THREAD

**Issue by JonSolo11** [IntelOrca/biorand#158]
Will disabling npc randomizer fix this for now or should i roll back?

**Comment by JonSolo11** [comment]
seed: R520-QM27-Z9HH0QZL3003

**Comment by IntelOrca** [comment]
You can use debug menu to reset the player back to Leon. This has now been fixed in dev. builds. I am not sure whether it happened in previous build - the issue did not look like an obvious regression.

**Comment by Hemavore** [comment]
I Would Like To Report That I Did Not Experience This Issue Until 2.1.5.

**Comment by JonSolo11** [comment]
Clearly I'm not aware of everything the debug menu can do so I apologize.
