### ISSUE TITLE
Stuck, help plz

### ISSUE THREAD

**Issue by residentraccoon** [IntelOrca/biorand#160]
I am seemingly stuck.. need suncrest, don't have lighter either for two items in candle room... something I'm missing? Was no item on bed in serum saferoom. Thanks!
Download Visual Studio Code to view DGML file so that I may break down item code location but not having much luck in deciphering this.

[log_pl1.txt](https://github.com/IntelOrca/biorand/files/10419271/log_pl1.txt)
Seed: R510-VHCK-J6ABCKX01ZZ1

**Comment by IntelOrca** [comment]
The sun crest is in room 212, which is Forrest's grenade launcher. Did you check this, was it the grenade launcher or something else? Did the Barry cutscene play, and did he give you a different item?

**Comment by residentraccoon** [comment]
Thanks for quick response. Forest gave me the grenade launcher and Barry gave me acid rounds.

**Comment by IntelOrca** [comment]
I wasn't able to reproduce this. Forrest gave me the sun crest.

**Comment by residentraccoon** [comment]
ok, going to run a few more tests.. starting to think I may need fresh install, this isn't my first time being soft locked, even going back to a randomizer that pre-dates yours.. Barry always gives me acid and Forest always has launcher, like in vanilla, wood crest is always wood crest.. I assume that's normal though. Thanks again

**Comment by IntelOrca** [comment]
Mixing randomizers is also not a good idea. So yeah make sure you have a vanilla install.
The wood crest is not randomized as doing so prevents the gold one from being placed.
