### ISSUE TITLE
Crashing in go after Annette after the elevator, the door that leads to the sewer

### ISSUE THREAD

**Issue by napr0** [IntelOrca/biorand#163]
Seed: R520-G6EV-XQRV1FWLLA03

**Comment by napr0** [comment]
crash 3 times and i cant keep progress

**Comment by napr0** [comment]
Door 404

**Comment by napr0** [comment]
i use debug for teleport in another doors and keep crash

**Comment by IntelOrca** [comment]
Possibly caused by enemy randomization. I have changed things, particularly this room and it doesn't appear to crash in dev. builds - so hopefully it is fixed.
