### ISSUE TITLE
RE 2, room 208, enemies in safe room even when option unchecked

### ISSUE THREAD

**Issue by JulumEi** [IntelOrca/biorand#164]
Version: BioRand 2.1.6
Seed: R521-3YTW-XXZ80AWLL143

In Claire A in Room 208 there was an enhanced Licker despite not allowing enemies in safe rooms.
[log_pl1.txt](https://github.com/IntelOrca/biorand/files/10420348/log_pl1.txt)

**Comment by IntelOrca** [comment]
Oops, missed that room.
