### ISSUE TITLE
no generate option 

### ISSUE THREAD

**Issue by tyrant20202** [IntelOrca/biorand#170]
there is no option to generate seeds as well as no leon A/ clair B Clair A/ Leon B and the logs at the bottom of the rando is missing. re1 has it bun re2 dose not  biorand v.2.1.6
![image](https://user-images.githubusercontent.com/119074612/212590490-9336681a-39c8-4a86-abd1-ab206f89022b.png)

**Comment by IntelOrca** [comment]
Looks like some of the controls have been clipped due to a small window size. What is your screen resolution? Is the window too tall for it?

**Comment by tyrant20202** [comment]
The resolution is 1366 x 768 that's the max . I had to put my laptop in
portrait mode to get it to come up right.

**Comment by IntelOrca** [comment]
Ah okay, I will have to try and redesign the UI a bit to work with that resolution.

**Comment by tyrant20202** [comment]
Ok, thanks. And thank you for this great rando and hope you have a great
day😀😀

**Comment by IntelOrca** [comment]
UI has now been re-designed.
