### ISSUE TITLE
RE 1, room 408, softlock during Chris / Rebecca cutscene

### ISSUE THREAD

**Issue by Hemavore** [IntelOrca/biorand#181]
Version: BioRand 2.1.6
Seed: R510-K1LL-X7Z62LZL1ZZ1
![1](https://user-images.githubusercontent.com/122418252/212976064-4efa13f4-ccb5-4023-811c-e32ee4b49ebf.PNG)

**Comment by IntelOrca** [comment]
Might be fixed in latest version
