### ISSUE TITLE
game crashes during Room 509

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#185]
Version: BioRand 2.1.6
Seed: R521-UEBM-ZTNT9N9HL06G

When room loads for room 509 boss fight the game freezes and doesn't show screen, crashes instead. Claire A

**Comment by IntelOrca** [comment]
I am having trouble reproducing this. I generated the seed, teleported to 509 - but it doesn't crash.

**Comment by ShannonCobannon** [comment]
This just happened again but with Leon A this time.
