### ISSUE TITLE
v2.1.6 RE2 Claire B 309 crashed when triggered Birkin Boss 

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#188]
BioRand 2.1.6
    Seed: R523-YG32-ZTZMPQZLLF1Q
    Player: 1 Claire
    Scenario: B
 
Connected 207:4 [DiamondKey] to 309:2 (locked #132)

**Comment by otamega72** [comment]
I don't know is this cause the problem ? 

   cutscene #0 contains rebecca, alyssa
    309:255 (0x130E) [SherryWithPendant] becomes [SherryWithPendant (sherry)]
    309:255 (0x1328) [SherryWithPendant] becomes [SherryWithPendant (sherry)]
    309:255 (0x134E) [SherryWithPendant] becomes [SherryWithPendant (sherry)]
    309:255 (0x1368) [SherryWithPendant] becomes [SherryWithPendant (sherry)]

**Comment by IntelOrca** [comment]
Might be fixed by 1b84c4f9e35712748e3d92a9f54d8e061aaac992

**Comment by IntelOrca** [comment]
Re-open if it happens again
