### ISSUE TITLE
Seed issue

### ISSUE THREAD

**Issue by bfinz** [IntelOrca/biorand#195]
Version: BioRand 2.1.7
Seed: R520-2TNZ-X7HHHMZLL00N

Played through Leon A just fine, went to check out Claire's A (didn't run the game as admin, so my file wasn't able to save). Anyway, first area as Claire/Regina, went to Kendo's and it said it was locked from the inside. Nowhere else to go, stuck in the starting area? Pretty sure outside of other mods like Origin of Species there's no other way out of the starting crash site except through Kendo's.

**Comment by bfinz** [comment]
This may be intentional, as I realized the seed was Leon A / Claire B, so that keeps you from getting too far in the wrong scenario. Gonna close this unless I'm wrong!

**Comment by IntelOrca** [comment]
Each room has one file for Claire and one for Leon. So it is not possible (or not simple 😅) to configure a layout that would work for both scenarios.
