### ISSUE TITLE
Leon A - Crash After Leaving Cable Car After Birkin Attack

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#208]
Version: BioRand 2.1.7
Seed: R520-FX0A-ZTBE9MQLL16Q

Can't tell if it was the room or the enemy that caused the crash. Screen went black once I opened the door.

Thank you so much for making this
 randomizer!

![image](https://user-images.githubusercontent.com/123828971/215279853-08b6bd7d-7aee-49e0-b5e6-8c1ae62861a8.png)

[log_pl0.txt](https://github.com/IntelOrca/biorand/files/10527828/log_pl0.txt)

**Comment by IntelOrca** [comment]
This room tended to crash when you the partner and random enemies spawn. This should be fixed in the dev. builds.

**Comment by missingno1711** [comment]
Sounds good. Were you keeping issues open until they are fixed in the next release? Or did you want me to close this one?

**Comment by IntelOrca** [comment]
Duplicate of #193

**Comment by IntelOrca** [comment]
> Sounds good. Were you keeping issues open until they are fixed in the next release? Or did you want me to close this one?

I think it is the same as #193, so I have closed it as duplicate.
