### ISSUE TITLE
Run out of free item slots

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#209]
### Version

v2.1.7

### Seed

R520-WHK8-ZTQ6T03LLG27

### Scenario

RE 2 (Leon A)

### What happened?

Hit the random button and got:
![image](https://user-images.githubusercontent.com/123828971/215302461-596e7a42-e82c-47bd-ba98-c8aa0a5e317a.png)

**Comment by IntelOrca** [comment]
Closing all "run out of item slot" issues for now.
