### ISSUE TITLE
Leon B, inventory is Claire's inventory

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#213]
### Version

2.1.7

### Seed

R521-73T8-9JNN5CCHLB3P00100W00000Z88Z

### Scenario

RE 2 (Leon B)

### What happened?

Even with randomizer turned off, it still changes Leons Handgun to Claires. Leon B
![Screenshot_20230130_085517](https://user-images.githubusercontent.com/122331724/215640240-7f787613-9f87-4cac-8a45-4b0712a61e09.png)

**Comment by IntelOrca** [comment]
@ShannonCobannon what do you mean by, even with the randomizer off?

**Comment by ShannonCobannon** [comment]
> @ShannonCobannon what do you mean by, even with the randomizer off?

When Randomize Items is unchecked and it is just default RE2 with no randomization of the items or Weapons but in the 2nd scenario Leon uses Claire's handgun instead
