### ISSUE TITLE
RE 1, room 10B, key item not present

### ISSUE THREAD

**Issue by ShiroiBara** [IntelOrca/biorand#216]
### Version

2.1.7

### Seed

R510-AZPB-N0HHH4ZL100N

### Scenario

RE 1 (Chris)

### What happened?

Unable to proceed to dormitory area after using all 4 crests. No square crank in room 300 (Log file record: Placing key item (SQUARE CRANK x0) in 300:10). Instead of it there is only herbs, regardless what picked it's all same as in standard game.
Steps to reproduce. Use this seed and start new game as Chris. Move to area 11B via debug menu and proceed to room 300 (first house out). Check all herbs there - red, green and blue. There is should be crank instead of some of them but Chris keep pick up herbs only.

**Comment by ShiroiBara** [comment]
Definitely something wrong with item randos. I got another soft lock.
Seed: R510-Q6ZK-N0HHH4ZL100N
Room 10B should has Moon Crest instead green herb, but Chris keep getting her there. Log file says Placing key item (MOON CREST x1) in 10B:4 but line below says something about linking: 10B:4 [MOON CREST x1] placed at 60B:4 that's probably Lab area.

**Comment by IntelOrca** [comment]
The only issue I could reproduce was the item not being in room 10B. Everything else was fine, so maybe your seed hadn't generated correctly?

**Comment by ShiroiBara** [comment]
Apologizes for confusing you but looks like you right. This is conflict between HD textures pack made by teamex and this rando. Removing pack fixing issues with most of bugged areas which I provided before. I don't know how it possible but we have what we have. I only could ask you try your rando with this pack and check is it possible to resolve this conflict. But if it's not possible, well I will play without HD pack them.
