### ISSUE TITLE
Crash before Birkin fight Room 509 Leon A

### ISSUE THREAD

**Issue by ShannonCobannon** [IntelOrca/biorand#217]
### Version

2.1.7

### Seed

R620-VN9F-ZTKK4CZUF06BH26T4PZZZZZZ98Z

### Scenario

RE 2 (Leon A)

### What happened?

![Screenshot_20230203_111336](https://user-images.githubusercontent.com/122331724/216652561-506ff91b-3d68-4e50-8b52-1f0f73c4c142.png)
It crashes when I try to go through the door.

**Comment by IntelOrca** [comment]
Assuming this was caused by the issue of re-using boss enemy IDs for other enemies. So should be fixed now.
