### ISSUE TITLE
Crash After Chief's dialogue

### ISSUE THREAD

**Issue by siroco1** [IntelOrca/biorand#218]
Version: BioRand 2.1.7
Seed: R521-5M3G-R8ZC0GX3300Q

My seeds with Claire A keep crashing when entering the stuffed tiger room.

**Comment by IntelOrca** [comment]
I can't reproduce this, I generated this seed with 2.1.7 and went through 21B to 10E and back again without it crashing.

**Comment by IntelOrca** [comment]
Might be fixed by 954a2884e51c7cc7e539a384477f01de521adebb

**Comment by IntelOrca** [comment]
I think this is fixed now
