### ISSUE TITLE
RE1 Room 116 shotgun key item should not be randomized

### ISSUE THREAD

**Issue by ShiroiBara** [IntelOrca/biorand#222]
### Version

2.2.1

### Seed

R610-E1EZ-NHFKBCZ9400N000000ZZZZZZZZZZ0HZ

### Scenario

RE 1 (Chris)

### What happened?

Normally room 116 contains shotgun which must be replaced by broken one. Currently this shotgun replaced by random item same as for Chris and Jill. When player pick Chris and have no another shotgun or broken shotgun in his inventory at moment when he come to this room he won't place back randomized item and unlock door. This leads to soft lock. Same possible with Jill too if she took alternate route at the beginning of the game and Barry won't come to help her and brake the door. I don't remember now how to trigger this for her but this is possible scenario. The only solution now put there normal shotgun and not randomize it at all or somehow put there broken shotgun instead to prevent possible soft lock, so player will put broken shotgun back and unlock the door. Another interesting bug here - random item what came to inventory instead of shotgun has multiplier x7 (check via debug menu) and using it later not removes it from inventory normal way. Shotgun has 7 shells, seems that's why it happens.

**Comment by IntelOrca** [comment]
I am not sure I can code it so that you can place back the random item, because if it were for example an ink ribbon - it might put down the whole stack. Is the problem just that you tried to pick it up without having a broken shotgun? If that is the case, you just need to make sure you have something to put back - or Barry is able to save you.

**Comment by ShiroiBara** [comment]
Thank you for response. Yeah, seems this is hard to fix without changing bunch of code. In future players should avoid this situation. May be it's good idea to post info about it (possible soft lock) in README.md on main page of project? Same like for possible crash of sourcenex logo.
