### ISSUE TITLE
RE 1 data not found when data folder name is USA

### ISSUE THREAD

**Issue by kendosrando** [IntelOrca/biorand#225]
when I put "randomize music" on check (in RE2 layout), it'll notice that "RE1 installation must be enabled to use RE1 assets," could you please add RE1 voice and music data into the randomizer? cause I can't find any version of RE1 that can be running on my computer

**Comment by IntelOrca** [comment]
@kendosrando you don't need RE 1 to be able to run, you just need it installed so BioRand can harvest the data folder from it. I don't particularly want to include actual RE1-3 assets as they would increase a size of randomizer much more than it already is.

I will investigate the issue with the message, but for any RE 1 NPCs and RE 1 BGM, you will need to link it to the game.

**Comment by kendosrando** [comment]
I just find out that BioRand harvests RE1 data only for the Japanese version, one of the directory folder name must be "JPN." most version I can find is the U.S version which's the folder name is "USA," so I change "USA" to "JPN," the problem that tortured me few months finally solved out, thanks, bro!

**Comment by IntelOrca** [comment]
I didn't know a USA version existed... I guess I could look in there if JPN is not found.
