### ISSUE TITLE
Crash when entered the hall via ladder from 2F Hall

### ISSUE THREAD

**Issue by Akahama-Patryk** [IntelOrca/biorand#226]
### Version

2.2.1 (bd54d6c)

### Seed

R620-1845-ZJEL0GZAF77G9K71MHZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### What happened?

When I enter the Hall [200] via ladder from Hall 2f [110] in a few secs crashes the game. When entering the Hall via debug menu gives me more time to move but after some time it crashes. I have tested the Hall with early save and I know what makes it crash. When I enter the Hall via debug without Sherry with my early save it doesn't crash the game but when I have Sherry in my inventory then it crashes.

**Comment by IntelOrca** [comment]
I haven't been able to reproduce, lets see if it happens again in a more recent version.
