### ISSUE TITLE
RE 1, overflow when combining ammo with flamethrower

### ISSUE THREAD

**Issue by ShiroiBara** [IntelOrca/biorand#229]
### Version

2.2.1 (bd54d6c)

### Seed

R610-3H8X-N1FKBCZ1400N000000ZZZZZZZZZZQMZ

### Scenario

RE 1 (Chris)

### What happened?

If you add to Chris' flamethrower additional fuel using mix menu and amount of it breaks certain in-game value, additional fuel will gone and flamethrower will take less fuel before mixing or another incorrect amount. Step to reproduce: use this seed and create some amount of fuel in inventory. Try to mix it and see what happens. For example: I had flamethrower with 233 ammo left and adds  96 more. Totally I got 201, which even less than initial amount. This might affect other weapons too, haven't tested it yet.

**Comment by IntelOrca** [comment]
Fixed in 249ae907009f6d2409e3d3eb9d9ff85c13baa059
