### ISSUE TITLE
New RE2 PC skins for next update

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#233]
May I suggest new RE2 PC skins for next update ?

Carlos , Mikhail ,Nicholai etc Skins :
http://remer.bplaced.com/remer_files/res_index.php
download link :
http://remer.bplaced.com/BH_1-3_skins.rar

Nemesis Skins Source : DarkSpyda04
https://www.tapatalk.com/groups/residentevil123/playable-nemesis-re2-t2894.html 
[Playable Nemesis RE2 v0.1.2.zip](https://github.com/IntelOrca/biorand/files/10677726/Playable.Nemesis.RE2.v0.1.2.zip)

**Comment by IntelOrca** [comment]
RE 3 characters will soon be available
