### ISSUE TITLE
RE 2, random inventory double items glitch if not at top

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#238]
### Version

2.2.1 (bd54d6c)

### Seed

R620-8LL5-ZTCQ4NZCF3BZVPEVPEZZZZZZZZZZGGZ

### Scenario

RE 2 (Leon A)

### What happened?

So I started with a Magnum with extra ammo and a 100% Machine Gun. I killed a Tyrant in the next room after the start and reloaded the Magnum. Picked up more Magnum ammo, and got this. Perhaps the game is not aware that the machine gun occupies 2 spaces? I don't know.
![image](https://user-images.githubusercontent.com/123828971/217426174-47038d44-165b-498a-a512-ee928da583db.png)

**Comment by missingno1711** [comment]
Might not be a bug. Randomizer had put the machine gun in the second row of the inventory, I went to the item box, emptied my inventory and it corrects itself. I guess the game forces 2 space weapons to have priority to the top of the inventory.

**Comment by IntelOrca** [comment]
I thought the same was a bit smarter than this, I will have to force all double items to be at the top.
