### ISSUE TITLE
No key items to progress. Just locked doors

### ISSUE THREAD

**Issue by SmallMaggot** [IntelOrca/biorand#240]
### Version

2.2.1 (bd54d6c)

### Seed

R620-GT8R-ZHQEAL825J7H27FV6CZZZZZZZZZZ4HZ

### Scenario

RE 2 (Claire A)

### What happened?

Got stuck 4 rooms in. First two rooms are standard, leaving Kendo's shop through the back brings you to the 3rd story RPD crank and gear room. Leaving though the same door back into Kendo's shop and leaving through the front door brings you into the RPD interrogation hall. All three doors in that hallway were locked and the only herb in that hallway did not yield a key item to progress any further.

**Comment by IntelOrca** [comment]
Your seed was configured for Leon A / Claire B.
