### ISSUE TITLE
RE 2, room 21B, mayor's daughter is licker

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/biorand#243]
### Version

2.2.1

### Seed

R620-RP54-XNHB6QZB6T5LJ2692E6QA5W2MKZZPMZ

### Scenario

RE 2 (Claire B)

### What happened?

Enemy placement should be disabled for Claire.

**Comment by ShiroiBara** [comment]
Wrong room. 21B, I had daughter there with Billy as chief. My seed is R623-1M93-Z1JB54Z16H69VPEVPEZZZZZZZZZZZZZ. I'm using Seamless 2.0 rebirth version and HD pack made by teamx. No idea am I had lucky or this just some version glitch. Posting here just for additional info.
