### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ripperc100jr** [IntelOrca/biorand#247]
### Version

2.2.1 (bd54d6c)

### Seed

R621-TCF9-ZT853MZ9FE2QK49AM4ZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### What happened?

After blowing up the helicopter and entering chief irons door which leads to birkin fight (g1) it crash's

**Comment by IntelOrca** [comment]
I think I have fixed this, it is due to a crow in room 10A sharing the same kill ID as G adult. So when you killed the crow, it didn't spawn G adult which caused the crash.
