### ISSUE TITLE
Softlock on missing character model

### ISSUE THREAD

**Issue by NowhereIsHere** [IntelOrca/biorand#250]
### Version

2.2.1 (bd54d6c)

### Seed

R620-1R7Z-XNFK3EX3FG5NQTKUU4ZZZZZZZZZZZZZ

### Scenario

RE 2 Claire B

### What happened?

When playing Claire B, upon loading into the room where you meet Annette climbing out of the water, the character model was missing which caused the camera angle to never change and softlocked the game. My character was Ashley which never had a problem, but Annette was apparently changed to Sheva; I could tell because the dialogue was still working, but never gave me back control when it ended. When trying to use menus, I could hear it come up, but the screen was still locked to that same camera angle and when trying to use the debug menu, I manage to load into another room, but the game crashed immediately after. Luckily the seed spawned both Wolf and Eagle medals before then so I could reload the save and skip over that section so I could complete the game.

**Comment by IntelOrca** [comment]
This might be fixed in v2.2.2
