### ISSUE TITLE
RE 2, room 508, soft lock if partner shoots arm while it attacks player

### ISSUE THREAD

**Issue by Soket13** [IntelOrca/biorand#254]
### Version

2.2.2 (81c73fc)

### Seed

R620-1WRH-XMKH7MY92F3JVPEVPE00000000YZ0HZ

### Scenario

RE 2 (Leon A)

### What happened?

A Softlock at room 508 Under Ground Passage, Arms spawn and partner kills it making Leon dance. 
Leon A

**Comment by IntelOrca** [comment]
Arms now excluded from rooms with partner
