### ISSUE TITLE
RE 2, room 10D, Claire, crash

### ISSUE THREAD

**Issue by LordOfLocation** [IntelOrca/biorand#256]
### Version

2.2.2 (81c73fc)

### Seed

R621-TLXB-XN0HHQZ3FP6PTZ3ZZ400000000YZ0HZ

### Scenario

RE 2 (Claire A)

### What happened?

Game Crashes when entering Room 10D in the Clair A - Campaign

**Comment by IntelOrca** [comment]
I am unable to reproduce this crash

**Comment by IntelOrca** [comment]
Should now be fixed

**Comment by LordOfLocation** [comment]
Thank you.
And sorry for my late response.

Best regards
Alex Zagelow

Von meinem iPhone gesendet

Am 06.03.2023 um 23:12 schrieb Ted John ***@***.***>:

﻿

Closed #256<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIntelOrca%2Fbiorand%2Fissues%2F256&data=05%7C01%7C%7Cf9b3bc69b8e34a315dc108db1e8fd42f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638137375299721887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2ZdEeHWrmNXjJE0P1AomfDs8O590NcNDzi3m%2BYAm%2BMw%3D&reserved=0> as completed.
