### ISSUE TITLE
Game Crash After Picking Up Item

### ISSUE THREAD

**Issue by spectacularchungus** [IntelOrca/biorand#264]
### Version

2.2.2 (81c73fc)

### Seed

R620-G2KY-ZJBP8EJ92FBNT8UJUMZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### What happened?

In the West Stairwell (Outside of the Dark Room), attempted to pick up one of the two herbs next to the Dark Room entrance. Game crashed.

**Comment by IntelOrca** [comment]
I am unable to reproduce this crash
