### ISSUE TITLE
RE 2, room 10D, Claire crash when entering room

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#265]
### Version

2.2.2

### Seed

R623-Q38V-ZTHKMNZBAP1Q0H3000ZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire B)

### What happened?

Connected 20C:0 to 10D:0
20C to 10D crashed

**Comment by IntelOrca** [comment]
Is it possible for you upload a save game that reproduces this crash? There have been lots of crashes related to room 10D, but I have never been able to reproduce them from a new game.

**Comment by otamega72** [comment]
Save file 12. Go to door waiting room , then go to long corridor entrance.

Also uploaded save file 11 , just in case.

[10d.crash.save.zip](https://github.com/IntelOrca/biorand/files/10896203/10d.crash.save.zip)

**Comment by IntelOrca** [comment]
@otamega72 thanks, I think I have fixed it now.

The room crashes even in vanilla RE 2. This particular room has Leon specific script in it and usually it doesn't get executed, but in your seed - a flag got set which meant it spawns magnum ammo in room (Tyrant drop). For some reason that item spawn crashes the game, so I have patched it out now.

**Comment by otamega72** [comment]
magnum gun is no use for Claire B. PC and use magnum gun but it cannot kill enemies.

**Comment by IntelOrca** [comment]
> magnum gun is useless for Claire B. PC and use magnum gun but it cannot kill enemies.

Raise a separate issue for that. For this, it is irrelevant, because even if the item did spawn, it wouldn't necessarily be magnum, it would be random.
