### ISSUE TITLE
RE 2, Claire B, Magnum/Shotgun cannot kill enemies

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#270]
### Version

2.2.2

### Seed

R623-Q38V-ZTHKMNZBAP1Q0H3000ZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire B)

### What happened?

Magnum Gun and Shot Gun cannot kill enemies.
Claire use Leon's weapon might face some problems.

Claire can use shotgun to shot zombie head and Ivy , but cannot hurt zombie's body and boss. Magnum gun cannot kill any enemies.

Attach the save file 
[Claire B_02_2023-03-08 08^44.07.zip](https://github.com/IntelOrca/biorand/files/10915318/Claire.B_02_2023-03-08.08.44.07.zip)

**Comment by baesik** [comment]
I came across this post on an old modding forum for RE2:
[http://re123.bplaced.net/board/viewtopic.php?f=11&t=1397](http://re123.bplaced.net/board/viewtopic.php?f=11&t=1397)

Looks like they used some sort of hex editing to fix this issue. 

You can find more information in the parent board. [Some stuff is really interesting and potentially might help @IntelOrca figure stuff out or how something works.](http://re123.bplaced.net/board/viewtopic.php?f=11&t=1141)

**Comment by otamega72** [comment]
RE2 Nemesis skin also has handgun aiming problem. 

[nemesis.pld.zip](https://github.com/IntelOrca/biorand/files/11582426/nemesis.pld.zip)

**Comment by IntelOrca** [comment]
Should be better now after 7ebea35fb1a51cda2f7a23ba80ba97a0f3b0d103
