### ISSUE TITLE
Crashing before STARS Conference Room

### ISSUE THREAD

**Issue by JillXSTARS94** [IntelOrca/biorand#271]
### Version

2.3.0 (d86eb61)

### Seed

R730-ZK1A-ZJ040HTZ1F700E09TTP0ZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### What happened?

Random Crash in ROOM 115, Resident Evil 3. Also the Hunter Gammas seem to be very problematic; almost every room they appear in the game crashes

**Comment by IntelOrca** [comment]
Thanks, the crash was also a hunter gamma. I did originally stop them from spawning, but a regression creeped in. This should be fixed now.
