### ISSUE TITLE
RE 3, room 107, crash due to Jill 2 NPC

### ISSUE THREAD

**Issue by Datchoco** [IntelOrca/biorand#275]
### Version

3.0.0

### Seed

R730-MLHC-XXZQ8V73WFH00EZZW8K0ZZZZZZZZZZZZ10Y

### Scenario

RE 3 (Jill)

### What happened?

Got a crash on Biorand 3.0, Jill (RE3 but with inventory expansion strap model) spawned with a shotgun in the place of Brad in the bar, upon killing the zombie, the game froze. It was also funny seeing Jill run up to me and act similar to Carlos' AI.

Playing as Steve, ran into bar, initial cutscene played as usual (Jill getting bitten) once that was over, Jill ran up to player character (Similar behavior to Carlos AI) and fired shotgun model as a handgun, once the zombie was dead, the game hard froze.

**Comment by JulumEi** [comment]
Just had a crash here as well. RE3R Jill model, Bard became Chris with a floating zombie behind him and the game was stuck until I skipped the cutscene. Chris limped up to Jill and the game immediately closed.
