### ISSUE TITLE
RE 3, room 40C, crash on entering room

### ISSUE THREAD

**Issue by kickgripping88** [IntelOrca/biorand#279]
### Version

3.0.0 (fafcdd5)

### Seed

R730-52X8-ZJHH0HM89F000NV4PVP1ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### What happened?

Room 304 CT Hall 1F. Crashes trying to enter the stairs and the dining room. Tried using the debug menu to go to room 110 without success. I was able to trigger nemesis on the stairs only once, every other time crashed.

**Comment by IntelOrca** [comment]
Room 110 can crash, but I it must only happen if certain flags are set. So I am unable to reproduce it from a new game. If you are able to provide a saved game where it does crash, that would be helpful.
