### ISSUE TITLE
soft locked in first area of claire B as annette (RE2R)

### ISSUE THREAD

**Issue by wicstarry** [IntelOrca/biorand#281]
### Version

3.0.0 (fafcdd5)

### Seed

R720-0QME-ZJHH90GL9WYA01U6B275ZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire B)

### What happened?

Immediately upon starting the game in the first room (room 100), Kendo's gun shop is locked and I cannot proceed further.

**Comment by wicstarry** [comment]
Game also soft locks in second room (60c) of seed R720-1ZGF-ZJHH90GP9WYA01U6B275GZZZZZZZZZZZZZZ as Annette (RE2R). I've had a lot of seeds with Annette as Claire B that result in locked first or second rooms.

**Comment by IntelOrca** [comment]
If it is Claire B, how was your first room 100? It sounds like you are playing the wrong scenario.

**Comment by wicstarry** [comment]
Oh do you have to actually load a B scenario save to do the B scenario?

**Comment by IntelOrca** [comment]
> Oh do you have to actually load a B scenario save to do the B scenario?

Yep

**Comment by wicstarry** [comment]
Sorry about that, thank you.
