### ISSUE TITLE
RE3 Crash after killing zombie in the bar

### ISSUE THREAD

**Issue by ruinedplay** [IntelOrca/biorand#282]
### Version

3.0.0 (fafcdd5)

### Seed

R730-APQG-XXPH40BZ2PA00N8KW9K1ZQE5ZYQVZZZZX6Y

### Scenario

RE 3 (Jill)

### What happened?

Game crashed after killing the zombie attacking Brad in the bar scene, just as the cutscene was about to start.

**Comment by IntelOrca** [comment]
I am not able to reproduce this crash

**Comment by ruinedplay** [comment]
Crashes every time for me with this seed. I uploaded a video of it, starting from a new game, to Youtube.

https://youtu.be/wBKR-xSL2gY

**Comment by IntelOrca** [comment]
When I use the same seed, I don't get Krauser as the NPC. However, if it is the same issue as #305, then it might be fixed now.
