### ISSUE TITLE
Blood suckers crashing in rpd

### ISSUE THREAD

**Issue by Smurphy2014** [IntelOrca/biorand#289]
### Version

3.0.0 (fafcdd5)

### Seed

R730-50YW-T0ZL0A4Z2Y000MZBJ940ZZZZZZZZZZZZ00Z

### Scenario

RE 3 (Jill)

### What happened?

Shooting bloodsuckers with samurai edge was crashing my game in the hallway of the rpd where nemesis comes through the window.

**Comment by IntelOrca** [comment]
Duplicate of #286
