### ISSUE TITLE
RE3 - Crashed After Opening Cutscene Zombies

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#290]
### Version

3.0.0 (fafcdd5)

### Seed

R730-FRGQ-ZTHHHHMZ9Y000NVPEVP100000000ZZZZ00Y

### Scenario

RE 3 (Jill)

### What happened?

Played as Nicholai, crashed when trying to escape cutscene zombies.

**Comment by IntelOrca** [comment]
Possibly fixed in v3.0.1
