### ISSUE TITLE
Failed to generate

### ISSUE THREAD

**Issue by gman019** [IntelOrca/biorand#291]
### Version

3.0.0 (fafcdd5)

### Seed

R730-1K20-Z1HHHHMC9FH00N00000000000000ZZZZ00Z

### Scenario

RE 3 (Jill)

### What happened?

Error when generating any seed : "An error occurred during generation. Please report this seed and try another." 
RE2 and RE1 working fine.

**Comment by gman019** [comment]
Solved(Ish): Can run if enabling only random music and NPCs, nothing else. Music changes fine, NPCs also change but dialogue does not.

**Comment by IntelOrca** [comment]
Closing due to incompatible version or files
