### ISSUE TITLE
ROOM 120; BAR JACK ALLERY 120 CRASHED 

### ISSUE THREAD

**Issue by gurongi123** [IntelOrca/biorand#292]
### Version

3.0.0 (fafcdd5)

### Seed

R730-WU92-Z1ZT5ZQZ9Y000NZZZZZ3ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### What happened?

ROOM 120; BAR JACK ALLERY 120 CRASHED NEAR STAIRS.
It happened in Doorland, so it probably happened because the flag went wrong in the event of Brad escaping through the back door of BAE JACK.

**Comment by gurongi123** [comment]
After trying several times, it stopped happening after disabling randomize npcs.
The crash is not caused by the flag, but by Brad turning into another random NPC.

**Comment by IntelOrca** [comment]
I am not sure how you ended up in room 120. That is never included in the door rando. Are you sure it wasn't room 105? I have fixed the issue in 105.

**Comment by gurongi123** [comment]
I'm sorry it was room 105. I'm glad I got it.
