### ISSUE TITLE
BioRand doesn't have permission to write

### ISSUE THREAD

**Issue by Shfan3** [IntelOrca/biorand#293]
Every time I go to generate an RE2 seed I get this
![Screenshot (1)](https://user-images.githubusercontent.com/127770695/224752988-aa787513-043e-401e-b98c-1f4f747edeea.png)
Also for RE3 no seed is ever valid and can't be generated and it says my directory is good.
Can someone tell me how to give it permission to write in my re2 folder? I've tried security and other things. I found no solution.

**Comment by guiprd** [comment]
This link should help with this problem:
https://www.techadvisor.com/article/728225/how-to-run-programs-as-administrator-in-windows-10.html

**Comment by Shfan3** [comment]
I tried running it as administrator I still get the same error, I should of made that more clear

**Comment by IntelOrca** [comment]
Your RE 2 install location might be read only or on a disc that is too full. I assume this still happens after a PC restart? eliminating the possibility that another program is locking the files.

Try copying your RE 2 install to a different location and trying again.

**Comment by Shfan3** [comment]
Ok it does still happen after a restart and I tried copying it to another locations twice both times it said the directory was good than the same message came up. I ran as administrator both attempts also that was the result

**Comment by Kogohazan** [comment]
I have the exact same issue as Shfan3. I have tried for 3 days and nothing will give permission to write file. Ran it normally, ran it as an administrator, moved the directory out of program files, same message every time."Failed to generate. Biorand does not have permission to write in this location if your game is installed in "program files", you may need to run Biorand as an administrator. Same pop up error message as they are showing. And whenever I try to generate re 3 I get "failed to generate. An error occurred during seed generation. Please report this seed and try another." not sure what I am doing wrong as I have been using RE Dukes Randomizers and they work fine.

**Comment by IntelOrca** [comment]
Do you have any antivirus software installed that might be blocking it?

**Comment by Kogohazan** [comment]
That is a possibility. I do have kaspersky antivirus. I hasn't popped up that its doing anything when I try to generate a seed.

**Comment by Kogohazan** [comment]
I tried giving Biorand full access and to have the antivirus software ignore it and I still get the same error message. Both running it normally and as an administrator.

**Comment by Shfan3** [comment]
I get the same messages for RE2 and RE3 as you do, and it works for RE1. My antivirus isn't stopping for 1 why 2 and 3.

**Comment by Kogohazan** [comment]
Yeah same! Re 1 will work but 2 and 3 do not. Whatever our problem is, its something we both have or are doing.

**Comment by Shfan3** [comment]
If he made this mod he knows what he's doing, I sent a message for my RE3 issue explaining its Xosiv brand it says under the download its the European SourceNext. That makes sense because my RE2 needed new audio and video files to turn into sourcenext. My RE3 needed just the Japanese files for the version speedrunners use. Nothing else needed to be altered like RE2 so yeah. He seems like a capable guy, him and the help he got for making BioRand.

**Comment by Kogohazan** [comment]
Oh for sure. Massive respect for such an ambitious project. Its why I want to use this version. Currently I use RE Dukes randomizer which works fine but I really want to be able to use this one.  I have no doubt its just some little thing that's making it not work. I just have no idea what that is. I know it does work since I have seen streamers using it, and in the folders I see the file that it generated that shows the swapped item locations. Just for whatever reason it cant make the file that would need to be loaded.

**Comment by Shfan3** [comment]
Yeah this is one of tgose moments anyone would wish they had that kind of knowledge.
