### ISSUE TITLE
RE1 closes windowed or full screen at beginning

### ISSUE THREAD

**Issue by Shfan3** [IntelOrca/biorand#301]
It closes when you first enter the mansion or when you go into the dining room. Never had RE1 issues before this update the seed is

R710-XVX3-XNE7603LCF020149K49K0WZZZZZZZZZZ00Z

I was playing as Jill.

**Comment by IntelOrca** [comment]
Does it happen on vanilla as well or just when you load the biorand mod?
Does it happen if you select some NPCs and BGMs, or disable those two things?

**Comment by Shfan3** [comment]
it doesn't happen on vanilla. It happens with and without the NPCs and BGMs disabled

**Comment by IntelOrca** [comment]
Does it happen if use an older version of biorand?

**Comment by Shfan3** [comment]
No everything is fine with an older version of BioRand.

**Comment by IntelOrca** [comment]
Unfortunately I can't reproduce it, so I am not sure why it is crashing for you.

**Comment by Shfan3** [comment]
ok the 3.01 update fixed it brother so I'm gonna close this
