### ISSUE TITLE
RE3 Soft lock unless you skip and hard locks clock tower

### ISSUE THREAD

**Issue by miguel101senpai** [IntelOrca/biorand#302]
### Version

3.0.0 (fafcdd5)

### Seed

R730-QTAW-XQHHHHM79Y000N9K89K0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### What happened?

games progresses fine until clock tower library room after the train crashes cutscene with Carlos ( Richard ) crashes the game, unless you skip the cutscene. after that game hard locks and crashes after the fight with nemesis the game keeps crashing when it fades to black.

**Comment by IntelOrca** [comment]
I think the library crash may have been fixed in v3.0.1
