### ISSUE TITLE
RE 3, room 107, crash if NPC is EM67

### ISSUE THREAD

**Issue by Smurphy2014** [IntelOrca/biorand#305]
### Version

3.0.1

### Seed

R731-CX4U-NHZE06B09F50050Z3ZZ3ZZZZZZZZZZZZ00Z

### Scenario

RE 3 (Jill)

### What happened?

Same seed Ark being brad in the bar was acting weird he ran to me with a knife and when he killed the zombie the game crashed.

**Comment by IntelOrca** [comment]
I am unable to reproduce this, for me Brad was Carlos (RE3R), not Ark.
