### ISSUE TITLE
RE 2, room 107, crash possibly due to moths

### ISSUE THREAD

**Issue by HaithamGaafer** [IntelOrca/biorand#307]
### Version

3.0.0 (fafcdd5)

### Seed

R720-KZ23-ZJQFA0QZLY9P0LRTBLF5ZZZZZZZZZZZZH8Z

### Scenario

RE 1 (Chris)

### What happened?

The room is full of Moths and it crashed While I was running to avoid them

Here's the save data

https://drive.google.com/file/d/1qSYflJl93aCsjgbevWW5v6-kOZqN_pti/view?usp=sharing

**Comment by IntelOrca** [comment]
Please make sure you pick the right scenario.

**Comment by HaithamGaafer** [comment]
I pick original and in normal difficulty, am I missing something?

**Comment by IntelOrca** [comment]
When you create the bug report, there is a dropdown for the scenario. You selected RE 1 when this is a report for RE 2.

**Comment by HaithamGaafer** [comment]
Sorry, my bad!
