### ISSUE TITLE
Game crashes at the alley in the first sections of the game

### ISSUE THREAD

**Issue by HaithamGaafer** [IntelOrca/biorand#308]
### Version

3.0.1 (412b94e)

### Seed

R730-0000-ZJMG8MQZBFB00NRGY1Z0ZZZZZZZZZZZZH9Z

### Scenario

RE 3 (Jill)

### What happened?

The game crashed after going through the room with the snakes that come down from the ladder....the room that is connected to it through the ladder crashes the game (it's an alley in the city which exists in the first sections of the game...sorry for the bad description but I don't know its code name).

**Comment by IntelOrca** [comment]
Closing due to lack of information. A saved game and a room number is needed.
