### ISSUE TITLE
RE3 an error occurred during seed generation 

### ISSUE THREAD

**Issue by Shfan3** [IntelOrca/biorand#309]
Every seed for RE3 an error occurs and it says my directory is good.
![Screenshot (2)](https://user-images.githubusercontent.com/127770695/226018399-8100aa10-bf26-4490-82f2-44fb7c3435e4.png)

**Comment by IntelOrca** [comment]
Can you please upload the log file, you can click Jill log to open it.

**Comment by Shfan3** [comment]
BioRand 3.0.1 (412b94e)
    Seed: R730-6AXH-T6HHHH4ZCY000N49F49200000000ZZZZ00Z
    Player: 0 Jill
    Scenario: A
Creating Original Room Graph:
    Exception: Object reference not set to an instance of an object.
       at IntelOrca.Biohazard.DoorRandomiser.GetOrCreateNode(RdtId rdtId)
   at IntelOrca.Biohazard.DoorRandomiser.CreateOriginalGraph()
   at IntelOrca.Biohazard.BaseRandomiser.GenerateRdts(RandoConfig config, IRandoProgress progress, FileRepository fileRepository)


ok i clicked Jill log I hope I got it right, I figured Jill log

**Comment by IntelOrca** [comment]
I can't reproduce it, it might be caused by a difference in your version of RE 3. Where did you get your version from, is it possible for me to get the same version?

**Comment by Shfan3** [comment]
I got Xplosiv brand or what ever, turned it into Sourcenext by adding files and added files for Seamless HD project

**Comment by IntelOrca** [comment]
Closing due to incompatible version
