### ISSUE TITLE
Room 219 unable to go through door after triggering Ben cutscene

### ISSUE THREAD

**Issue by smokethebear** [IntelOrca/biorand#31]
Seed: R220-F4BM-Z1MC27Z

If you enter the room which triggers the cutscene of William infecting Ben, It prevents you from going through one of the doors as it says to go and see ben first.

For me, Although i had the valve handle, it was in the item box, So when i got to the cutscene of ben & william, I couldn't go back to an item box which unfortunately means i couldn't progress as i needed the valve handle in order to continue.

**Comment by smokethebear** [comment]
Had to abandon this seed in the end, although i worked around the william & ben thing by keeping the valve on me, My game broke after a certain point anyway.

When you go down the elevator which triggers the Annette, Leon & ada cutscene where Annette shoots leon and you take over as ada. The game automatically sets you as ada, Which breaks the game as you lose all your items.

**Comment by IntelOrca** [comment]
Same problem occured in this stream:
https://youtu.be/bYbk2R0jr4c?t=3764
