### ISSUE TITLE
RE 1, crash when playing Rebecca due to invalid inventory

### ISSUE THREAD

**Issue by PMCDC** [IntelOrca/biorand#311]
### Version

3.0.1 (98fb96d)

### Seed

R710-T1Z4-X5MC60QZ9Y000N82TLP4ZZZZZZZZZZZZA1Z

### Scenario

RE 1 (Chris)

### What happened?

Hi there!

The game crash when you start controlling **Rebecca Chambers** (when you need to save **Chris** from the big Plant). If I **open the inventory, the game will crash**. I noticed that there is an **infinite weapon without any graphic asset** (black rectangle), which makes me believe there is an invalid item in the inventory of **Rebecca**.

I tried to use the debug menu to remove this, but if I try to edit the inventory via the debug menu, the game will also crash.

_Note: I am also using the TeamX HD mod to play the game._

**Comment by PMCDC** [comment]
Just wondering one thing. With Rebecca, having the inventory full, won't it break the game? You need to create the J-VOLT and for that you need to grab chemical containers, right? And since you can't open Chest when you are playing with her, won't it make me stuck? Or maybe not? I'm not too sure how it is handled in this randomiser and its been years since I played this classic, so my memory on this is a bit fuzzy...

But anyway, her inventory looks like this:
- Handgun (loaded with 15 rounds)
- MixedHerb (G+R)
- Doom Book 1 (Eagle of East Wolf of West)
- Grenade Launcher Rounds x117
- Shotgun (loaded with 3 rounds)
- ????? (Balck Rectangle with Infinite quantity)

I tried to dive in the code to see how the inventory is made for this rando, but I do not understand the `init.xml` vs the `Re1ItemIds`. Nothing match what Rebecca have.

```
<Init>
  <Player>
    <Entry id="1" count="1" />
    <Entry id="73" count="1" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
  </Player>
  <Player>
    <Entry id="2" count="15" />
    <Entry id="11" count="66" />
    <Entry id="1" count="1" />
    <Entry id="73" count="1" />
    <Entry id="70" count="1" />
    <Entry id="71" count="1" />
    <Entry id="2" count="15" />
    <Entry id="70" count="1" />
  </Player>
</Init>
```

Like, the second Player entity does match what Chris starts with, but thats about it. Where does the inventory of Rebecca is being set? ^^'

**Comment by PMCDC** [comment]
![Rebecca](https://user-images.githubusercontent.com/14597708/226090560-58c19ed8-c817-447b-99e3-78adc58bb439.png)

Though I could give a screenshot just for reference. Also, sorry for the spamming messages. ^^'

**Comment by PMCDC** [comment]
Alright, so I decided to generate the seed again, but this time with the actual official build. 
(I was messing around with the source code in Visual Studio, but when I generated the seed, I didn't have the "data" folder of biorand in the **bin**, so I was thinking maybe I screwed something up.)

The generation is the same (**init.xml** and inventory generation is identical, same logs), but now Rebecca have 3 items.
![image](https://user-images.githubusercontent.com/14597708/226093018-32f5f336-a25a-4b96-948a-e2b823dfdc12.png)

Maybe there is something wrong with the version of my game? For this test, I did skipped everything just so I can get to the problematic part, but still no luck.

**Comment by IntelOrca** [comment]
All biorand will be doing is editing `init.xml`. So you can edit that file manually in mod_biorand to understand what is going on. You must restart the game for it to load `init.xml` again. If you find the game is doing something different each time you load it without changing anything, then it isn't being patched right.

I might try to patch the inventory myself rather than using rebirth's mechanism, just like I do with RE 2, and RE 3. This also means you do not have to restart the game.

**Comment by PMCDC** [comment]
Hi dude! Thanks for the clarification, this sure does help. :)

So after messing around a bit, I think I finally understand the **XML** structure:
![image](https://user-images.githubusercontent.com/14597708/226145917-e8a250ce-361e-4347-9a02-d989fdf7dcc7.png)

I did a few test and noticed something in particular for **Rebecca**. If I remove the item from the second slot, I do not have the extra **Minimi** item.
```
  <Player>
    <Entry id="2" count="15" />
    <Entry id="11" count="66" />
    <Entry id="1" count="1" />
    <Entry id="73" count="1" />
    <Entry id="70" count="1" />
    <Entry id="71" count="1" />
    <Entry id="2" count="15" />
    <Entry id="0" count="0" />
  </Player>
```

![image](https://user-images.githubusercontent.com/14597708/226146013-a98cdb21-c6bb-4f54-9549-c614675a29db.png)

And If I try to replace set the second item with anything else (does not matter if its an herb or a weapon), I will have the **Minimi**
![image](https://user-images.githubusercontent.com/14597708/226146091-ff3f4d62-63d0-4576-8632-00726a4e0d30.png)

And if I remove everything, well my inventory will be empty as expected:
```
  <Player>
    <Entry id="2" count="15" />
    <Entry id="11" count="66" />
    <Entry id="1" count="1" />
    <Entry id="73" count="1" />
    <Entry id="70" count="1" />
    <Entry id="71" count="1" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
  </Player>
```
  
![image](https://user-images.githubusercontent.com/14597708/226146183-46fc3ee2-4eb0-40bb-bf3a-6612660ed647.png)

A bit of a weird behavior. ^^'

**Comment by IntelOrca** [comment]
What happens if you add 4 empty elements after the two items for Rebecca?

**Comment by PMCDC** [comment]
Oh, looks like you have found the solution! ;) 

Adding those extra empty elements allow me to have the 2 items that was set initially.
```
  <Player>
    <Entry id="2" count="15" />
    <Entry id="11" count="66" />
    <Entry id="1" count="1" />
    <Entry id="73" count="1" />
    <Entry id="70" count="1" />
    <Entry id="71" count="1" />
    <Entry id="2" count="15" />
    <Entry id="70" count="1" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
    <Entry id="0" count="0" />
  </Player>
```
  
  
![image](https://user-images.githubusercontent.com/14597708/226149265-4b3fe10e-b96e-4afd-a4b4-35e2f5c1e6f9.png)

**Comment by IntelOrca** [comment]
I expect it was an initialisation problem. Without those empty slots, the memory was never getting cleared so you would get random items appearing.
