### ISSUE TITLE
RE 3, room 209, crash when entering room

### ISSUE THREAD

**Issue by gurongi123** [IntelOrca/biorand#317]
### Version

3.0.1 (412b94e)

### Seed

R730-F99U-ZJZZ7P7Z9YB00NZZZZZ3ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

JILL(RE3R)

### What happened?

If you enter room 209 through the door on the side of room 208, it will crash. 
Is the enemy of the car involved?

**Comment by IntelOrca** [comment]
Are you talking about when the car door opens in 209? I stopped the car door from opening in 3.0.1.
Were the enemies zombies, and did you see the car door open, or did it crash as soon as the room loaded?
Do you have a saved game before this happens?

**Comment by gurongi123** [comment]
The enemy was a zombie, and a freeze occurred the moment I entered Room 209.
It will be the save data at that time.
[06_2023-03-18 21^37.32.zip](https://github.com/IntelOrca/biorand/files/11009747/06_2023-03-18.21.37.32.zip)

**Comment by IntelOrca** [comment]
Hopefully fixed now
