### ISSUE TITLE
Crash at the alley connecting to the room with Brat 

### ISSUE THREAD

**Issue by HaithamGaafer** [IntelOrca/biorand#318]
### Version

3.0.1 (412b94e)

### Seed

R730-A74T-XJMG8MQZBFB00NRGY1Z0ZZZZZZZZZZZZH9Z

### Scenario

RE 3 (Jill)

### Player Character

Jill RE3RE

### What happened?

The alley was full of  brainsuckers in it and then it crashed suddenly.

**Comment by IntelOrca** [comment]
Which room are you referring to? 103?

**Comment by HaithamGaafer** [comment]
The alley with multiple pathways...the alley where brad supposedly shoots a
zombie and then runs into the bar.
That's where the game crashed

**Comment by IntelOrca** [comment]
Hopefully fixed now
