### ISSUE TITLE
RE 3, room 106, crash when Nemesis performs attack

### ISSUE THREAD

**Issue by SolidFat** [IntelOrca/biorand#320]
### Version

3.0.1 (412b94e)

### Seed

R730-2B1W-ZJLF19N51YB00N92EJM0WC305HEU0ZZZ5XZ

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3R)

### What happened?

Entered from the clock tower main hall, had just fought the grave digger in the previous room. The street is filled with nemesis's and it crashes upon taking a step. Luckily I had a save and went through a different door, but it circled back to that same street, this time coming out of jack's bar, and same result, crashed on entrance.

**Comment by SolidFat** [comment]
I was able to reload on RE3 and clear the street there and reboot in biorand and finish the rando. Just seemed to be nemesis causing the problem.

**Comment by IntelOrca** [comment]
Do you have a save game that will reproduce this nemesis crash?

**Comment by SolidFat** [comment]
[savedata.zip](https://github.com/IntelOrca/biorand/files/11012955/savedata.zip)

Here you go. The newest save is in the clocktower main hall. Head in the door by the corpse and it'll go to the alley. You'll see nemesis start to attack and it'll crash right there. There's a 2nd save in the same alley after I've cleared in in regular RE3 if that helps any. The 3rd save is nothing important (didn't wanna delete the wrong save so just zipped the whole thing up).
