### ISSUE TITLE
An error occured during generation

### ISSUE THREAD

**Issue by ZefEU** [IntelOrca/biorand#322]
### Version

3.0.1 (412b94e)

### Seed

R730-J8M1-H4GANBW09FK00N49K4J3KNG0C4YEZZZZM1Z

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

This error pops up every time I try to generate a random seed with randomized doors and items. I can only randomize NPCs models, music and enemies, plus change player character... Whenever I try to change something else, it fails to generate the seed.

May I missing something? I can't find anything to solve this issue on my own, I'm using a RE:3 US version, the classic RE:3 REBirth patch v 1.1.0 and 3.0.1 patch of BioRand. What shall I do? 
- Shall I look for a different version of the game?
-  Shall I apply some other mods to make it work?

I saw some streamers doing well (when game doesn't crash/lock at least) with rando doors and stuff.

Thank you :)

**Comment by IntelOrca** [comment]
I think this is caused by a different version of the game. I haven't investigated this yet, so your best option is to look for another one.

**Comment by ZefEU** [comment]
Thank you for the answer :) so I tried with 2 versions by now, do you know which suits the best for this mod and where I may find it?

**Comment by ZefEU** [comment]
I solved it finally! I didn't use the correct version of the game (Mediakite JPN one to be precise) in order to get the mod work properly!

Now I can use each feature correctly (with some bugs here and there but for now it's quite fine).. Thank you IntelOrca for everything!
