### ISSUE TITLE
RE3 3.0.1 multi bug

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#323]
### Version

3.0.1

### Seed

R730-QK2C-ZTTQH5NZ3Z100N8KCVP0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Ada (RE2R)

### What happened?

save 01 :  Connected 101:0 to 501:0 crash 

save 02 :  Ada (RE2R) use mine thrower crash

save 03 : 
Connected 103:0 to 409:0 crash 
Connected 103:1 to 11B:0 crash 

[re3 bug.zip](https://github.com/IntelOrca/biorand/files/11011121/re3.bug.zip)

**Comment by IntelOrca** [comment]
Maybe changes have gone in since, if problems still occur, a new issue can be opened.
