### ISSUE TITLE
RE3 An error occured during generation

### ISSUE THREAD

**Issue by Pelorelo** [IntelOrca/biorand#325]
### Version

3.0.1 (412b94e)

### Seed

R730-99L3-X7HHHHMZ1Y000N92NKM0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

Everytime i'm trying to generate a seed for RE3 with Jill ( random items/enemies/NPCs)  i get this error, i found out this error come from "Randomize NPCs", if i uncheck the box it work, if i leave even 1 npc i still get the error.

I'm playing BH3 (MediaKite)  (Official 1.1.0 patch by SourceNext + rebirth DLL)

I don't have this issue with BH1 and BH2.

**Comment by IntelOrca** [comment]
Closing due to incompatible version or files
