### ISSUE TITLE
RE3 3.0.1 multi bug 2

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#326]
### Version

3.0.1

### Seed

Seed: R730-KK59-ZTTQH5NZ3Z500N8KCVP0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Carlos (RE3R)

### What happened?

1)  Connected 503:1 to 302:1 --> cannot enter room 302 , cause no water sample 

2)  Connected 404:2 [TAPE RECORDER] to 301:0 sometime crash 
(go to B3)
[03_2023-03-23 22^36.49.zip](https://github.com/IntelOrca/biorand/files/11054053/03_2023-03-23.22.36.49.zip)

3)  cannot finish the game after 30D (CT battle)  . Inventory full and  NO SAVE ROOM / INVENTORY BOX  in this segment. 
        Creating segment from 30B to 415: 
        Connected 30B:1 [CLOCK TOWER KEY BEZEL] to 30C:0
        Connected 30B:30 [GEAR GOLD, GEAR SILVER] to 30D: (always)
****        Connected 30D:0 to 404:0   **** cannot go back to clock tower save room again ****
        Connected 404:1 [TAPE RECORDER] to 503:0
        Connected 503:7 to 209:1
        Connected 209:0 to 412:1
        Connected 412:0 to 10E:1
        Connected 10E:0 to 212:0
  ****      Connected 404:2 [TAPE RECORDER] to 301:0   **** sometimes crash  ****
        Connected 301:2 to 201:11
        Connected 201:1 to 414:0
        Connected 201:0 to 11C:0
        Connected 412:2 [IRON PIPE, LIGHTER OIL, LIGHTER NO OIL] to 104:1
        Connected 104:2 to 506:0
        Connected 104:0 to 308:1
        Connected 308:0 to 112:1
        Connected 112:0 to 218:0
        Connected 218:1 to 205:0
        Connected 205:1 to 108:0
        Connected 205:2 to 508:0
        Connected 108:5 [LIGHTER OIL, LIGHTER NO OIL] to 40F:0 (locked 132)
        Connected 301:1 [CLOCK TOWER KEY WINDER] to 502:0 (locked 133)
****     Connected 503:1 to 302:1     **** cannot enter 302:1  , no water sample  ****
        Connected 302:0 [CLOCK TOWER KEY WINDER] to 11A:0 (locked 134)
        Connected 508:2 [SYSTEM DISK] to 509:0
        Connected 40F:1 [PARK KEY REAR] to 415:2 (locked 135)
 
   Creating segment from 415 to 20C:   **** cannot go back to room before 415 again. ****
        Connected 415:0 (unblock) to 40C:1
//// save room in here ///      Connected 40C:2 to 117:0

**Comment by otamega72** [comment]
new bug after room 117 
 Connected 10B:0 to 20D:0  --> room stagla trigger Carlos go outside to kill zombies.
 Connected 405:3 to 20E:1 -- > room stagla access softlock , pc attach by enemies

**Comment by IntelOrca** [comment]
Issues may be fixed now, new ones can be created if still unsolved
