### ISSUE TITLE
RE3 NPC Bug

### ISSUE THREAD

**Issue by jillsandwich200** [IntelOrca/biorand#327]
### Version

3.0.1 (412b94e)

### Seed

R730-M3JP-ZJHHHHMZ9Y200NVPEVP100000000RZZZ5YZ

### Scenario

RE 3 (Jill)

### Player Character

Steve

### What happened?

Every time I make a seed with NPC'S in RE3 the seed always has an error. 
![error](https://user-images.githubusercontent.com/122399522/226664708-7593dd1c-3c2e-4af4-a39a-583f8cf0e251.png)
![With no NPC's](https://user-images.githubusercontent.com/122399522/226664731-163f2c89-e883-483b-af29-b2eea2fbd47f.png)

**Comment by gman019** [comment]
Are you using the sourcenext version or something else?

**Comment by jillsandwich200** [comment]
I was on the RE3 sourcenext version with HD mod

**Comment by jillsandwich200** [comment]
> Are you using the sourcenext version or something else?
I was on the RE3 sourcenext version with HD mod sorry LOL my first time replying on this

**Comment by IntelOrca** [comment]
Closing due to incompatible version or files
