### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by youngmanson** [IntelOrca/biorand#330]
### Version

3.0.1 (412b94e)

### Seed

R730-0000-ZTPPHPM59Y000N92EK40ZZZZZZZZZZZZC3Z

### Scenario

RE 3 (Jill)

### Player Character

Leon (RE2)

### What happened?

Game seems to crash after the fight with nemesis after the clock tower i load into the next room and when i go to open a door the game crashes everytime was having fun with this seed as well

**Comment by IntelOrca** [comment]
Which room were you in which contains the door that causes the crash when you go through it?

**Comment by IntelOrca** [comment]
Closing due to lack of information
