### ISSUE TITLE
Room 501, crash possibly caused by moths

### ISSUE THREAD

**Issue by STARSMember930** [IntelOrca/biorand#331]
### Version

3.0.1 (412b94e)

### Seed

R721-TA2E-WXHH90C99UFR0GKMAABKZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Regina

### What happened?

Received a crash in the room you enter directly from exiting the cable car - it has the flare gun that allows you to find the Weapon Box Key in the standard game. The room had 1-2 moths spawn and when I moved toward the left (exiting the car) to pick up the new item, the game froze and crashed. Unfortunately I don't have additional information/screenshots

I had previously seen this same crash in an earlier version (I think 2.7.0) playing with Jill and I believe using the door randomizer with Sheva. I have previously been able to work around it by using the door jump option. 

[Truly impressive Mod that has made my play-through of these games extremely enjoyable and fresh. Looking forward to more iterations, thanks for bringing this to the community!]

**Comment by IntelOrca** [comment]
I am not able to reproduce this issue. I generated the seed, teleported to the room and cannot get it to crash.
