### ISSUE TITLE
RE 3, room 11B, missing sound file during cutscene

### ISSUE THREAD

**Issue by Soullesscat** [IntelOrca/biorand#333]
### Version

3.0.1 (412b94e)

### Seed

R730-VZBY-XQHHHHCZUYB00NK49H2020808A00RZZZ10Y

### Scenario

RE 3 (Jill)

### Player Character

Claire(RE2R)

### What happened?

After extinguishing the fire with the fire hose that leads towards the building where you usually encounter Nikolai shooting another merc RE3 softlocks as a real-time cutscene plays when you enter the aforementioned building. This cutscene where Nikolai shoots someone cannot progress and softlocks the game supposedly because the sound file cannot be played and the player character is stuck in one place waiting for the sound file to be played or finish. I did not hear any dialogue or sound file playing and could not skip the cutscene due to it being rendered in real-time and the game not allowing to skip the cutscene due to the game's limitations. The character was stuck in idle animation waiting for the dialogue to finish to run towards Nikolai but the dialogue never took place. Maybe one of the sound files in the log file is broken?

Here's the log file: 

[log_pl0.txt](https://github.com/IntelOrca/biorand/files/11068584/log_pl0.txt)

**Comment by IntelOrca** [comment]
Closing for now, can be re-open if this happens again and a debug save attached.
