### ISSUE TITLE
3.0.1 RE3 multi bug 3

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#335]
### Version

3.0.1

### Seed

R730-H79P-ZTTQH5XZ3Z700N8KCV60ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Claire (RE2R)

### What happened?

1) Connected 112:1 to 301:2  crash
[c 02_2023-03-25 22^40.16.zip](https://github.com/IntelOrca/biorand/files/11070538/c.02_2023-03-25.22.40.16.zip)

2) Room 209 : wipe out all enemies and returning to this room crashed.
[c 03_2023-03-25 23^32.41.zip](https://github.com/IntelOrca/biorand/files/11070555/c.03_2023-03-25.23.32.41.zip)

3) Room 102 :  wipe out all enemies and returning to this room crashed.
[c 06_2023-03-26 02^36.41.zip](https://github.com/IntelOrca/biorand/files/11070543/c.06_2023-03-26.02.36.41.zip)

4) 50e crash 
50E:0 (0x12E8) [CARLOS OLIVEIRA 1] becomes [MARVIN BRANAGH 2 (kevin)]
[c 07_2023-03-26 02^39.01.zip](https://github.com/IntelOrca/biorand/files/11070533/c.07_2023-03-26.02.39.01.zip)

5) missing head (#352)
[01_2023-03-26 09^41.50.zip](https://github.com/IntelOrca/biorand/files/11070563/01_2023-03-26.09.41.50.zip)

![Capture](https://user-images.githubusercontent.com/120957601/227750525-adac7e2b-9b42-4374-adc7-8bf95397491e.JPG)

**Comment by IntelOrca** [comment]
Issues may be fixed now, apart from the graphical issue. That is raised as its own issue.
