### ISSUE TITLE
Item at 105 behind Crank, and Cranks is a non key item 

### ISSUE THREAD

**Issue by Soket13** [IntelOrca/biorand#341]
### Version

3.0.1 (412b94e)

### Seed

R730-5E92-TMHHH6CZ9M000NVPEVP1X10045H7MZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Ada (Re2)

### What happened?

Got a Lighter oil at 105:8 - The Alley, but the item over there is behind Crank[Square] right?
Got that:
Replaced 10B:2 [CRANK x1] with 10B:2 [GUNPOWDER AA x1]
is that right, or i missing something?

**Comment by Soket13** [comment]
my bad just a rusty spot XD , but could have  key on this crank check?

**Comment by IntelOrca** [comment]
> but could have key on this crank check?

I am not sure what you mean.
