### ISSUE TITLE
Crash at Clock Tower

### ISSUE THREAD

**Issue by Soket13** [IntelOrca/biorand#342]
### Version

3.0.1 (412b94e)

### Seed

R730-0XPC-T4HHH6BZ9M900NVPEVP1X10045H7MZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

Going to the church part, afeter getting a clock key and the tremor scene, when i opened the door the game crashed. I did had the Chrono open on Left side and never climbed to 1f.

**Comment by IntelOrca** [comment]
Was the crash in room 301?
