### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by boodgt** [IntelOrca/biorand#345]
### Version

3.0.1 (412b94e)

### Seed

R730-Q8G4-Z9HH0HC59W000NVPEVP1ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

jill

### What happened?

nothing but crashing right before activating clock tower and 105 crashing too

**Comment by IntelOrca** [comment]
What do you mean by activating clock tower?
