### ISSUE TITLE
RE 3, room 202, crash when car door bursts open

### ISSUE THREAD

**Issue by killerlilm** [IntelOrca/biorand#350]
### Version

3.0.1 (412b94e)

### Seed

R730-VFJM-XZHL5EXK9Y900N0JJWR1V08H10H5JZZZ89Z

### Scenario

RE 3 (Jill)

### Player Character

Jill(RE3)

### What happened?

Event: Event Crash
Room: 202 Parking Lot Back
Enemies: Zombie Dogs
Carlos NPC: Regina(DC)
Occurs: Zombie Breaking through the Police Car Door causes crash It happens after hearing the sound of Carlos firing his assault rifle.

Event: Cutscene Crash
Room: 202 Parking Lot Back
Enemies: Zombie Dogs
Mikhail NPC: Barry (RE1)
Occurs: Beginning of Cutscene when you return to the Cable Car.

Event: Cutscene Crash
Room: 214 Power Station, 204 Power Station Front
Enemies: Nemesis, Hunters
Occurs: Using the Escape through the emergency door choice when the zombies are pounding at the power plant door, after the door opens and the cutscene starts theres no zombies(Hunters) around and the game crashes before Nemesis introduces them to his Rocket Launcher.

Event: Immediate Crash
Room:  CT Piano Room
Enemies: Nemesis
Occurs: From any door opening once you are inside the room it causes a crash regardless if Nemesis has broken through the glass.

**Comment by IntelOrca** [comment]
@killerlilm do you have any saved games you can share before each of these crashes?

**Comment by killerlilm** [comment]
oh sure i have a few 
[biorand.zip](https://github.com/IntelOrca/biorand/files/11411213/biorand.zip)

**Comment by killerlilm** [comment]
I've noticed the same crash on another seed at the same location and involving the same police car 


Police Car Break Open Crash
Room: 202 Parking Lot Back
Enemies: Brain Sucker

Police Car break open crash
Room: 103 Warehouse Street
Enemy: Brain Sucker

I believe if there is any enemies that aren't zombies after the door opens it crashes immediately.
