### ISSUE TITLE
RE 3, room 40A, crash when shooting explosive

### ISSUE THREAD

**Issue by killerlilm** [IntelOrca/biorand#351]
### Version

3.0.1 (412b94e)

### Seed

R731-GWXU-XZGG74VG9F60011H5371045K4HMHZZZZ19Z

### Scenario

RE 1 (Chris)

### Player Character

Carlos (RE3)

### What happened?

Event: Game Crash
Room: 40A Laboratory
Enemies: Zombie Dog
Occurs: Shooting the Wall Explosive killing any zombie dog causes the game to crash.

2 additional Notes 

1. I have noticed that the reloading tool is not in the item pool for the randomizers or at least in the immediate list, If you don't get it in the start randomizing your starting items you don't get it at all. I'm going to test that with a few more randomizer runs to ensure that. (Done 4 so far and only 1 had the reloading tool in the inventory when you randomized starting inventory as well.)

2. I noticed that in the item logs that it's using the names of items that belongs in the RE2 Randomizers.
I've done a bit of locating to notice which items are what so far.
[ShotgunAmmo x30] - HandgunAmmo x30 
[FuelTank x14] - ShotgunAmmo x14
[CustomHandgun x7] - Shotgun
[129 x3] - Ink Ribbon x3
[Bowgun x6] - Mine Thrower x6
[CustomMagnum x6] - Grenade Launcher x6
[HandgunParts x1] - First Aid Spray x1
[ShotgunParts x1] - Blue Herb x1
[MagnumParts x1] - Green Herb x1
[FAidSpray x1] - Red Herb x1
[SparkshotAmmo x6] - Mine Rounds x6
 
[log_pl0.txt](https://github.com/IntelOrca/biorand/files/11411395/log_pl0.txt)

**Comment by killerlilm** [comment]
[04_2023-05-05 15^29.33.zip](https://github.com/IntelOrca/biorand/files/11411401/04_2023-05-05.15.29.33.zip)

heres a save file if you need it.

**Comment by killerlilm** [comment]
Comment to Additional Note 2

Further experimentation the log changing from normal is if you have randomize items checked but not randomized doors.

**Comment by IntelOrca** [comment]
>  have noticed that the reloading tool is not in the item pool for the randomizers

The reloading tool is given to the player if and only if gunpowder is available to pick up in the seed.
