### ISSUE TITLE
it wont generate the seed

### ISSUE THREAD

**Issue by tomspc1991** [IntelOrca/biorand#353]
### Version

3.0.1 (412b94e)

### Seed

R710-C2N5-XYHHH04Z9Y000N49K49KZZZZZZZZZZZZ20Z

### Scenario

RE 1 (Chris)

### Player Character

jill

### What happened?

it wont generate the seed

**Comment by IntelOrca** [comment]
Works fine for me
![image](https://github.com/IntelOrca/biorand/assets/1482259/e33f5ec9-337a-4c73-952b-09855ddffe36)
