### ISSUE TITLE
RE 2, room 10B, Claire A with random enemy placement crash

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#354]
### Version

3.0.1 (983007c)

### Seed

R721-BYF1-ZTHH00NK9Y940L49K499ZZZZZZTZZZZZF3Z

### Scenario

RE 2 (Claire A)

### Player Character

Ada (RE2R)

### What happened?

Crash toward the first couple minutes into the seed, going from Room 608 -> Room 10B.

I do have the latest high quality sounds and HD textures enabled. I don't have any issues otherwise and I've played around ~15ish seeds now. 

Attached is the debug save file I made before the room.
[Claire A_00_2023-05-10 15^21.18.zip](https://github.com/IntelOrca/biorand/files/11446449/Claire.A_00_2023-05-10.15.21.18.zip)

**Comment by baesik** [comment]
I have another seed that crashed when transitioning into Room 10B. 

R721-QHPT-ZTHH00NK9Y940L49K499ZZZZZZTZZZZZF3Z

This time it was Room 219 -> 10B. I record my runs but unfortunately don't save very often, if ever, in-game.

**Comment by IntelOrca** [comment]
Thanks for catching this bug so early
