### ISSUE TITLE
RE 3, crash after entering restaurant for the second time

### ISSUE THREAD

**Issue by Soullesscat** [IntelOrca/biorand#356]
### Version

3.0.1 (412b94e)

### Seed

R730-Z3F2-NQHHHHCZUYB00NK49H2000400P01HZZZ10Y

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3R)

### What happened?

After entering the restaurant from room 205 for the first time the game simply crashed. Because I didn't do much in-game other than hurrying to the previous location the game crashed at after restarting the game I assume is why I was now able to enter the restaurant from room 205. I used the lockpick, picked up the item and then exited from the other side into room 206. When I tried to enter the restaurant for the second time it crashed. Then I tried to switch the places I entered from which was from room 206, repeated the process by using the lockpick, picking up the item inside and exited from the other side tried to re-enter and it crashed. Then I only used one door to enter from, I re-entered the restaurant for the second time and it crashed. 

Attachments:

[savedata.zip](https://github.com/IntelOrca/biorand/files/11454910/savedata.zip)

[log_pl0.txt](https://github.com/IntelOrca/biorand/files/11454909/log_pl0.txt)

![2023-05-11 19-13-28](https://github.com/IntelOrca/biorand/assets/36854965/993bc67b-522c-4795-85e0-d44cba94ca69)

![2023-05-11 19-18-18](https://github.com/IntelOrca/biorand/assets/36854965/19a8ab87-d912-4e49-822d-77992727e493)

**Comment by IntelOrca** [comment]
I am unable to reproduce the crash from a new game or your saved game. I didn't think any event happened in the restaurant until you used the fire hook.

**Comment by Soullesscat** [comment]
I didn't use the fire hook. The problem persists even if I don't do anything special but enter the door to the restaurant twice.

Also, I don't think it's my firewall since no process is neither contained nor blocked and I set the entire folder location of both RE3 and Biorand to trusted. It can't be my RAM either due to it happening under the same circumstances. After configuring my firewall I re-seeded with the same seed, started a new game but had the same outcome. Maybe if anyone else had been reading this - which is unlikely - and had been willing to test this problem it would be great, but I don't expect extra treatment.

Should I refrain from reporting problems? I don't want to waste your time if this problem is specific to me. Feel free to close this issue.

**Comment by IntelOrca** [comment]
> Should I refrain from reporting problems? I don't want to waste your time if this problem is specific to me. Feel free to close this issue.

No, please keep reporting issues. I can reproduce most of them. But when I can't, it is very difficult to fix, because I can't identify what the problem is, or whether I have fixed it.

I think RE 3 in particular is problematic because there are several different versions of the game that people are using which might behave differently. On top of that, the game is very fragile, it doesn't handle edge cases very well and has many issues when you take the game over the limits of what was originally tested.

Some things that might help diagnose the issue, is to disable enemies or NPCs and see if you can identify what it is that crashes. Another thing is to try saving in the room just before the crash, and then loading that save in vanilla to see if it still crashes. Sometimes just an incorrect sequence can crash the game. For example in vanilla, you can simply teleport straight to the press room, activate the Carlos cutscene, then teleport to the outside of the RPD. The game will crash due to a Nemesis flag.

I had an issue that no one else could reproduce where rain would crash my game if I just teleported from the start to the park. For that reason, I had to disable rain for everyone which isn't great.

**Comment by baesik** [comment]
I generated the seed, used your save data, and recorded using OBS to enter the restaurant exactly as you had described, and I did not crash.

**Comment by Soullesscat** [comment]
> I generated the seed, used your save data, and recorded using OBS to enter the restaurant exactly as you had described, and I did not crash.

Wow thanks for the help I really appreciate it.

> I think RE 3 in particular is problematic because there are several different versions of the game that people are using which might behave differently. On top of that, the game is very fragile, it doesn't handle edge cases very well and has many issues when you take the game over the limits of what was originally tested.

I'm using the Sourcenext version with the official 1.1 patch in combination with seamless HD project and classic rebirth which is supposed to fix random crashes during door transitions due to incorrect sound handling of the Sourcenext port. Are you implying that the addresses in the execution file are different with each version? In the readme you suggest to use the Sourcenext version. Am I supposed to use the 1.0 version instead?

I disabled manual reload and automatic door skip function but that didn't help. Then disabled the npc and enemy randomization but to no avail. After that I switched to vanilla version which didn't crash.

**Comment by Soullesscat** [comment]
baesik uses a different version than me as you can see in this issue https://github.com/IntelOrca/biorand/issues/360
my version is capped to 30 fps https://www.pcgamingwiki.com/wiki/Biohazard_3:_Last_Escape_(Sourcenext)#Resident_Evil_3_Classic_REbirth

**Comment by IntelOrca** [comment]
Would you be able to send me the binary .exe files? I can at least give a checksum warning if the version is not the best one.
Does playing in Japanese make any difference? Some of us noticed that when randomizing the door of the first room, it crashed only in Japanese mode.

**Comment by Soullesscat** [comment]
No difference, I already tried switching back to Japanese.
[bh3 1.0.zip](https://github.com/IntelOrca/biorand/files/11472403/bh3.1.0.zip)
[bh3 1.1.0.zip](https://github.com/IntelOrca/biorand/files/11472406/bh3.1.1.0.zip)

**Comment by baesik** [comment]
I couldn't help but notice that the menu screen had different sound. I thought it was supposed to be a randomized "Biorand?" You make a good point about the sound thing. Maybe try changing your sound format in your playback settings? 

In my config.ini, my sound settings are:
`SoundChannels = 2
SoundDepth = 16
SoundFrequency = 44100`

In sound settings the actual format used is 24 bit, 48000Hz.

**Comment by Soullesscat** [comment]
> I couldn't help but notice that the menu screen had different sound. I thought it was supposed to be a randomized "Biorand?" You make a good point about the sound thing. Maybe try changing your sound format in your playback settings?
> 
> In my config.ini, my sound settings are: `SoundChannels = 2 SoundDepth = 16 SoundFrequency = 44100`
> 
> In sound settings the actual format used is 24 bit, 48000Hz.

About that, I replaced the title bgm so yes it sounds different.

**Comment by Soullesscat** [comment]
https://github.com/IntelOrca/biorand/issues/312

**Comment by Soullesscat** [comment]
Fixed in 3.0.2v (see https://github.com/IntelOrca/biorand/issues/312). Tested issue in new release and was solved perfectly.
Not sure why you didn't tell me earlier. Closed.

**Comment by IntelOrca** [comment]
@Soullesscat when I try to reproduce bugs, I use the exact version specified in the report. I was not able to reproduce the crash, I assume #312 was a different issue, not related to the crash.
