### ISSUE TITLE
RE 2, room 202, crash due to shared enemy ID for Marvin

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#361]
### Version

3.0.1 (b5e7489)

### Seed

R721-8NZ0-ZTZZ00NK9W0A0L49K499ZZZZZZTZZZZZF3Z

### Scenario

RE 2 (Claire A)

### Player Character

Annette (RE2R)

### What happened?

Same seed as my previous bug report. #360 

Crash in Room 202 when Marvin event is playing.
Attached the debug save file made just before the room.
[Claire A_00_2023-05-13 20^05.13.zip](https://github.com/IntelOrca/biorand/files/11471029/Claire.A_00_2023-05-13.20.05.13.zip)

**Comment by IntelOrca** [comment]
Thanks, this issue was caused by a random generated enemy using the same ID as Marvin NPC. This means it crashed if you killed that random generated enemy prior to the cutscene.
