### ISSUE TITLE
RE 3, room 205, player gets stuck after using or removing bronze compass

### ISSUE THREAD

**Issue by Soullesscat** [IntelOrca/biorand#362]
### Version

3.0.1 (412b94e)

### Seed

R730-Z3F2-JQHHHHCZUYB00NK49H2000400P01HZZZ10Y

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3R) 

### What happened?

This one is obvious but you can get stuck in this place if you're not careful even if you have bronze compass in your inventory after you use it you cannot remove it to get out of this room due to it getting replaced with a randomized item. Happens in any seed.

https://github.com/IntelOrca/biorand/assets/36854965/abffa42e-d24f-4181-a80a-776eec9a980c

**Comment by IntelOrca** [comment]
I have decided to allow this one to stay in. It doesn't really make sense to allow the player to put the random item back since it might be ammo which could have been merged with another or gun.

**Comment by Soullesscat** [comment]
No but if you decided not to randomize the compass it will always be in it's original place. Problem is you'd have to find the book first and it would have to be found before the next checkpoint. Please don't get me wrong it's actually great that one can skip big portions of the game without having to find key items. Not that anyone can get stuck there. The chance is low because the game actually tells you that you are going to get ammo and have willingly to accept this so you know that you will likely get stuck there but in terms of quality control it just seems a bit broken to me especially when you think that you can get extra ammo because you actually found the bronze compass to insert. But not everyone knows that the address of the item is constant and will always result in extra ammo. So one might be thinking I'm going to get extra ammo and then use the bronze compass to get out, but that's not possible.

**Comment by IntelOrca** [comment]
RE 1 has two similar situations:
* The shotgun trap (https://github.com/IntelOrca/biorand/issues/222)
* The bronze/gold shield

While it may catch a few players out, they will not repeat the mistake.

**Comment by Soullesscat** [comment]
But then would it be possible to have the water already be activated so the player won't be able to get there? You could also exclude bronze compass from the game since it's a useless item.

**Comment by IntelOrca** [comment]
@Soullesscat I would like to keep the idea of having a key item there which requires the book key item to obtain. If you accidentially pickup the item without the book, then it is a reset for the player.

**Comment by Soullesscat** [comment]
Oh wow that would be a great solution. That's even better.

**Comment by Soullesscat** [comment]
> Oh wow that would be a great solution. That's even better. It won't result in a reset though you can put the item back in and you will get same item as you can see in the video but this time it will be a key item and not ammo because the item you pull cannot be changed once randomized. But then speedrunners will complain.

**Comment by Soullesscat** [comment]
No wait I forgot that you can't put that item back in. That would be terrible.
