### ISSUE TITLE
RNG related (i think) crash in pharmacy

### ISSUE THREAD

**Issue by SolidFat** [IntelOrca/biorand#365]
### Version

3.0.2 (10d7467)

### Seed

R730-TKGU-ZTLF19N53YC00N92EJM0WCB07HEUCZZZ5XZ

### Scenario

RE 3 (Jill)

### Player Character

Kendo

### What happened?

Crash inside the pharmacy that happens after the break in cutscene when leaving the room. When I had the crash the room's RNG loaded 3 yellow powders, 3 red powders. However I reloaded and tried again and the RNG I got only loaded the 3 yellow powders but not the 3 reds, that one **didn't** crash. 

To get to the pharmacy room just take the hospital elevator to B3. The save is in the elevator room. 
[re3crash.zip](https://github.com/IntelOrca/biorand/files/11483339/re3crash.zip)

**Comment by IntelOrca** [comment]
I was not able to reproduce the crash from your saved game. I used the elevator to get to room 11C, picked up the clock tower key which triggers the Zombie cutscene, killed the zombies, then left the room again.

**Comment by SolidFat** [comment]
When it crashed for me I went to 1F first from the elevator, checked every door in the boutique, saw the cutscene in the gas station (where the other red powders would move to) and then went back to check where B3 went to. Maybe its because I visited the gas station first that the issue happened?

**Comment by IntelOrca** [comment]
Are you able to provide a debug save just a few walk steps before the crash?
