### ISSUE TITLE
Unable to randomize key item.

### ISSUE THREAD

**Issue by gurizzy** [IntelOrca/biorand#371]
### Version

3.0.2 (10d7467)

### Seed

R720-H5AF-XNZ350NZ9R000QR67UR4ZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Random

### What happened?

Unable to randomize key item. Report seed and try another.

**Comment by IntelOrca** [comment]
I don't think you selected the right scenario.

**Comment by IntelOrca** [comment]
Duplicate of #368
