### ISSUE TITLE
RE 3, room 30B, camera stuck after Nemesis encounter

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#376]
### Version

3.0.2 (f8e2db1)

### Seed

R730-A0L4-ZTHH0HM69Y000NK49820ZZZZZZZZZZZZF3Z

### Scenario

RE 3 (Jill)

### Player Character

Jill RE3R

### What happened?

* [x] #383 Seed very early on has many issues. Room 500 loops back into itself from two doors, enemies are off-screen. 
* [ ] Room 30B locks it's camera view if you revisit the room after pushing Nemesis off. You can still guess your way to the ladder and/or use the key. The herbs that spawn here might be a little bit harder to grab.
* [x] #384 Softlock after beating virus nemesis with no boxes to store items.

Debug saves attached. 

[01_2023-05-21 02^20.26.zip](https://github.com/IntelOrca/biorand/files/11524231/01_2023-05-21.02.20.26.zip)

**Comment by IntelOrca** [comment]
@baesik if a door loops back to the same room, this is not a bug. They are just unconnected doors. Usually they are locked, but looping back to the same door is an extra safety mechanism if the lock fails to ensure you don't accidentially escape the door randomizer.
