### ISSUE TITLE
Nemesis Gone No Blue Gem

### ISSUE THREAD

**Issue by DJPhatzo** [IntelOrca/biorand#377]
### Version

3.0.2 (10d7467)

### Seed

R730-MQN7-T6HHHH4Z9Y000N9K8H2000000000HZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

Placing key item (GEM BLUE x1) in 11A:4

Nemesis didn't appear (likely because I grabbed the lockpick before entering the RPD) Thus where Brad's Card Key would be, didn't appear.

**Comment by IntelOrca** [comment]
Sorry, I am not sure what your issue is. The blue gem should be where the grenade launcher usually is in the STARS room. Was that not there?

Whether Nemesis spawns or not is just the nature of the rando.

**Comment by Neil-F2** [comment]
I decided to try and test this seed, i reach the clock tower and stopped playing after the nemesis fight (when you play as Carlos), i did not find any issues and it didn't crash in any moment
I think the person who reported the issue simply misunderstood where the blue gem was, maybe he thought it was in Brad's body, or maybe he thought he needed Brad's card to enter the inside of the RPD, but both cards are in accessible places, so I would say that this report might be a misunderstanding

**Comment by IntelOrca** [comment]
@Neil-F2 thanks, this can be re-opened if the raiser replies.

A few streamers have been confused by Nemesis not showing up at the RPD. This is because I switch to the the night time rooms for the fire hose to work correctly. I might look into improving this so that it switches back to day time after that room.
