### ISSUE TITLE
RE 3, Jill model not replaced

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#378]
### Version

3.0.2

### Seed

R730-VV5V-ZTRQHT7Z3ZA00N8VUYE2ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3)

### What happened?

biorand :  R730-VV5V-ZTRQHT7Z3ZA00N8VUYE2ZZZZZZZZZZZZZZZ
log_pl0.txt : R730-VV5V-ZTRQHTZZ3ZA20N8VUPE2ZZZZZZZZZZZZZZZ

Randomize npc crashed the game. 

1. 403 back to 412 , cut scene locked.
Connected 412:2 [IRON PIPE, LIGHTER OIL, LIGHTER NO OIL] to 403:0
412:0 (0x3100) [NIKOLAI ZINOVIEV] becomes [JILL VALENTINE 1 (ark)]
[c 412 05_2023-05-19 19^39.18.zip](https://github.com/IntelOrca/biorand/files/11524917/c.412.05_2023-05-19.19.39.18.zip)

2. back to warehouse crashed 
101:0 (0x6808) [DARIO ZOMBIE] becomes [CARLOS OLIVEIRA 1 (kevin)]
[c04_2023-05-18 21^01.22.zip](https://github.com/IntelOrca/biorand/files/11524934/c04_2023-05-18.21.01.22.zip)

3 remote control crashed 
11B:3 (0x432C) [PROMO GIRL] becomes [CARLOS OLIVEIRA 1 (kevin)]
[remote 01_2023-05-21 23^34.45.zip](https://github.com/IntelOrca/biorand/files/11524941/remote.01_2023-05-21.23.34.45.zip)

npc crash refer to : https://github.com/IntelOrca/biorand/issues/338#issuecomment-1538170809
" crash might be related to the graphical issues, which could vary across game versions, settings and GPU."

===========
I found that some randomize npc ( ark , jake , kevin ,krauser ) will crash my game.
Untick those npc above and generate the similar seeds again , no more crash.

**Comment by otamega72** [comment]
NPC and voice did not match. 

generate similar seed above (untick randomize npc ark , jake , kevin ,krauser ) 
R730-VV5V-ZTRQHT7Z3ZA00N8VUYC2VZZQGYZZZZZZZZZ

412:0 (0x3100) [NIKOLAI ZINOVIEV] becomes [JILL VALENTINE 1 (enrico)]
npc jill ,  enrico's voice.
    
[c 412 05_2023-05-19 19^39.18.zip](https://github.com/IntelOrca/biorand/files/11525224/c.412.05_2023-05-19.19.39.18.zip)

**Comment by IntelOrca** [comment]
@otamega72 I think something might be up with your game, because I was unable to reproduce any of the crashes. I was able to reproduce the problem where Jill did not become Enrico though.
