### ISSUE TITLE
RE 3, room 105, crash due to NPC

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#380]
### Version

3.0.2 (f8e2db1)

### Seed

R730-8QL8-ZTHH0HM69Y000NK49820ZZZZZZZZZZZZF3Z

### Scenario

RE 3 (Jill)

### Player Character

Claire

### What happened?

Room 105 crashes as you move forward through the room. The game will crash if you just wait in the room as well. Debug save attached. You'll want to bring up the status screen or leave the room before it crashes.

Virus clocktower nemesis was killed. Then, room before 105 is the first nemesis police station encounter and he was killed as well.

[01_2023-05-21 16^28.14.zip](https://github.com/IntelOrca/biorand/files/11525778/01_2023-05-21.16.28.14.zip)

**Comment by baesik** [comment]
R730-MA35-ZTHH0HM69Y000NK49820ZZZZZZZZZZZZF3Z

Another seed has Room 105 very early on (first 2 minutes) and will crash if I push "Brad" past a certain point or if I get grabbed by a zombie.

Debug save attached. You'll need to go through two rooms to get to 105.

![Screenshot 2023-05-22 05-45-28](https://github.com/IntelOrca/biorand/assets/16945591/0bdd9cf6-9579-4880-b3ad-b13f04db5db7)

[01_2023-05-22 05^49.13.zip](https://github.com/IntelOrca/biorand/files/11531233/01_2023-05-22.05.49.13.zip)

**Comment by IntelOrca** [comment]
@baesik for the second one, I am not sure what causes the crash specifically. Sometimes I can get it to happen, sometimes it doesn't crash no matter how many times I get grabbed or run about. I think the safest thing to do here is to just restrict the rando from always entering this room for the first time from the normal door. Although loopbacks can still occur. Either that or I remove the NPC.

**Comment by baesik** [comment]
@IntelOrca In my opinion, having 105 always from the normal door is a good compromise.

**Comment by IntelOrca** [comment]
@baesik yeah, actually I have changed it now to allow any door as the entrance to that room apart from the one that goes to the bar since the cutscene plays when you get to the small steps.
