### ISSUE TITLE
RE 3, room 11D, crash

### ISSUE THREAD

**Issue by Lirte** [IntelOrca/biorand#381]
### Version

3.0.2

### Seed

R730-W2U8-XNHL7UNZ2YB00N05PU80NBH5TRTTUZZZ6NZ

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3R)

### What happened?

I was just leaving the R.P.D and decided that I was going to get the itens from Dario's container since he would be dead already. The issue is after I run all the way to main street and open the door to the alley where Dario's daughter get killed, the screen fades to black and my game closes itself. I thought it could be my seed so I made it a new one, but I'm still getting the crash at the same place. 
Don't know if is a known issue, but I had it to report mine. Really liking the rando so far, I think I can still advance my game, but want to loot the container first, so here's hoping you find what is the problem.

**Comment by IntelOrca** [comment]
@Lirte are you able to provide me a debug save just before it crashes?

**Comment by Lirte** [comment]
> @Lirte are you able to provide me a debug save just before it crashes?

[re 3 debug save crash.zip](https://github.com/IntelOrca/biorand/files/11547609/re.3.debug.save.crash.zip)
