### ISSUE TITLE
RE3 3.0.2 Room 408 Crash

### ISSUE THREAD

**Issue by dudleycu** [IntelOrca/biorand#387]
### Version

3.0.2 (10d7467)

### Seed

R730-50C0-ZT4300L0LYB00MH4YVR0RUM04N8AJZZZAGZ

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3R)

### What happened?

Crash upon entering room 408. Recreated crash by simply starting a new game and attempting to enter room once again from Dining Hall.

**Comment by IntelOrca** [comment]
Maybe changes have gone in since, if problems still occur, a new issue can be opened.
