### ISSUE TITLE
RE3 3.0.2 Crashes in Room 101

### ISSUE THREAD

**Issue by dudleycu** [IntelOrca/biorand#388]
### Version

3.0.2 (10d7467)

### Seed

R730-1YMB-Z94300L0LWB00M8KX471RUM04N4AJZZZAGZ

### Scenario

RE 1 (Chris)

### Player Character

Jill

### What happened?

Crashes after exiting initial area leading into room 101. Recreated crash 3 times

**Comment by IntelOrca** [comment]
Maybe changes have gone in since, if problems still occur, a new issue can be opened.
