### ISSUE TITLE
RE3 3.0.2 Room 20F Crash

### ISSUE THREAD

**Issue by dudleycu** [IntelOrca/biorand#390]
### Version

3.0.2 (10d7467)

### Seed

R730-R4WH-Z14300L0LWB00M8KX471RUM04N4AJZZZAGZ

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

Crash upon entering the office/leaving the hallway in room 20F. Recreated by simply entering the same area.

**Comment by IntelOrca** [comment]
Maybe changes have gone in since, if problems still occur, a new issue can be opened.
