### ISSUE TITLE
RE 3, room 205, crash due to NPC

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#391]
### Version

3.0.2 (848906a)

### Seed

R730-54JY-ZTHH0HMA9Y600N49K490ZZZZZZZZZZZZF2Z

### Scenario

RE 3 (Jill)

### Player Character

Carlos (RE3R)

### What happened?

Entering Room 205 crashes. Debug save attached.

It would also be nice to request features or enhancements to your mod! I think having the option of starting with the side pack already would be a great QoL.

[01_2023-05-24 05^04.23.zip](https://github.com/IntelOrca/biorand/files/11554328/01_2023-05-24.05.04.23.zip)

**Comment by IntelOrca** [comment]
> It would also be nice to request features or enhancements to your mod! I think having the option of starting with the side pack already would be a great QoL.

You can use the discussions feature on GitHub to raise enhancement requests.
