### ISSUE TITLE
RE3 3.0.2 Instant Crash After Intro Sequence from 101 to 20C:

### ISSUE THREAD

**Issue by dudleycu** [IntelOrca/biorand#392]
### Version

3.0.2 (10d7467)

### Seed

R730-M11K-ZT3401V2LY500M8KX471H6M0444AJZZZC1Z

### Scenario

RE 3 (Jill)

### Player Character

Caralos

### What happened?

Instant Crash After Intro Sequence from 101 to 20C:

**Comment by IntelOrca** [comment]
@dudleycu hi, I have been unable to reproduce any of your crashes which leads me to believe that there is something wrong with your game or environment. Possibly the same issue @otamega72 has. You could try disabling NPCs, or choosing a limited selection to see if that helps.

If you contact me on discord (see channel link on the UI), you can try the same version of the game I have.

**Comment by otamega72** [comment]
For [dudleycu](https://github.com/dudleycu) reference :
npc Ark , ashley , jack , kevin , kauser , wesker re5 crashed my game.
