### ISSUE TITLE
RE 3 randomized Jill RE1 NPCs are glitched

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#393]
### Version

3.0.2 (243098e)

### Seed

R730-54JY-ZTHH0HMA9Y600N49K490ZZZZZZZZZZZZF2Z

### Scenario

RE 3 (Jill)

### Player Character

Carlos (RE3R)

### What happened?

Replaying the seed with the newest fix and it randomized Dario's NPC to RE1 Jill and looks like this: 
![RESIDENT_EVIL™_3_NEMESIS_PC03,47PM](https://github.com/IntelOrca/biorand/assets/16945591/d6058429-776e-497c-a60a-d9f2903fb45d)

This also happens to any NPC that is randomized into RE1 Jill.

**Comment by IntelOrca** [comment]
What do you mean by any NPC that is randomized into RE1 Jill?

I assumed that our RE 1 Jill model is just out right broken.

**Comment by baesik** [comment]
Yea, so there are some NPCs in the cutscenes that have been randomized into Jill and she also has this weird quasimodo vibe. I've seen her bugged with the safe exploding room as well, for example. 

I know nothing about modeling, but the built-in STARS costume is a faithful alternative.
