### ISSUE TITLE
RE 3, room 21A, crash if the dogs are damaged by explosive barrel

### ISSUE THREAD

**Issue by Neil-F2** [IntelOrca/biorand#397]
### Version

3.0.2 (10d7467)

### Seed

R731-G4NT-XXLG0FNZ2Y300N05PR80N7K7N5TURZZZ6NZ

### Scenario

RE 3 (Jill)

### Player Character

Annette

### What happened?

In room 21A  there is 2 dogs, if you shoot the explosive barrel and the dogs are damage by the explotion the game crash
I tested it and it's the dogs being damage by the explotion what cause the crash, since i don't crash if the dogs are dead or far enough of the explotion

**Comment by Neil-F2** [comment]
Debug Save here, because it didn't let me before (My own mistake)
[Debug Save.zip](https://github.com/IntelOrca/biorand/files/11570796/Debug.Save.zip)

**Comment by baesik** [comment]
I confirmed that I also crash. It's actually kind of hilarious.

**Comment by IntelOrca** [comment]
thanks, dogs are now banned from this room
