### ISSUE TITLE
RE 3, room 11B, glitches if entered after room 11C cutscene

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#400]
### Version

3.0.2 (243098e)

### Seed

R730-U5GU-ZTHH0HMZ9W300N09K490ZZZZZZZZZZZZF2Z

### Scenario

RE 3 (Jill)

### Player Character

Annette

### What happened?

After entering 11B and skipping the cutscene, the camera becomes locked. I wasn't able to make a save right before the bug and reloading the room will fix it. I figured a save wasn't necessary but if it will help, I can take a previous save and work my way forward to the point where this happens.

Additionally, there are graphical issues until the room is reloaded.
![image](https://github.com/IntelOrca/biorand/assets/16945591/04356c81-917e-4afb-9adb-832aea5ad4fb)

[01_2023-05-26 11^17.10.zip](https://github.com/IntelOrca/biorand/files/11578800/01_2023-05-26.11.17.10.zip)

**Comment by IntelOrca** [comment]
I am not able to reproduce this. Does it only happen when playing with the HD mod?

**Comment by baesik** [comment]
I just tested and it also happens with a clean install with nothing but rebirth and the 1.1 patch. I'll go back a bit in the save that way I can make a debug save just before the start of the actual cutscene as well as a video.

**Comment by baesik** [comment]
This is a save I made literally right after the cutscene that has the camera locked.
[01_2023-05-26 11^14.24.zip](https://github.com/IntelOrca/biorand/files/11579791/01_2023-05-26.11.14.24.zip)

**Comment by IntelOrca** [comment]
Okay, I think the issue is caused by triggering the zombie cutscene in 11C before the cutscene in 11B.

**Comment by baesik** [comment]
Here is the save file:
[01_2023-05-26 14^04.05.zip](https://github.com/IntelOrca/biorand/files/11579990/01_2023-05-26.14.04.05.zip)

And here is the video I uploaded of the issues. It's currently processing, but should be available shortly after posting. 
[https://www.youtube.com/watch?v=t-n_wK3Cxu0](https://www.youtube.com/watch?v=t-n_wK3Cxu0)
