### ISSUE TITLE
Cutscene freeze entering pharmacy

### ISSUE THREAD

**Issue by SolidFat** [IntelOrca/biorand#402]
### Version

3.0.3 (0b004de)

### Seed

R730-LP7H-ZTLF19N53Y700N92EJM0WCB07HEUCZZZ5XZ

### Scenario

RE 3 (Jill)

### Player Character

Claire (RE2)

### What happened?

Currently saved the game inside the room before water test. Taking the door that would go down to water test goes to the pharmacy entrance where the cutscene would start (either Nicholai or Carlos killing Murphy), and the cutscene just freezes there with Claire standing quietly infinitely without the cutscene proceeding 
[re3freeze (2).zip](https://github.com/IntelOrca/biorand/files/11580547/re3freeze.2.zip)

**Comment by IntelOrca** [comment]
Is this the same problem as #278?
And can you skip the cutscene?

**Comment by baesik** [comment]
> Is this the same problem as #278? And can you skip the cutscene?

It is the same problem. You cannot skip the cutscene.
