### ISSUE TITLE
RE 3, crash due to no weapon in inventory slot 0

### ISSUE THREAD

**Issue by SolidFat** [IntelOrca/biorand#403]
### Version

3.0.3 (0b004de)

### Seed

R730-GUVC-ZTLF19N53Y700N92EJM0XXZXQZXZGZZZ5XZ

### Scenario

RE 3 (Jill)

### Player Character

Claire (RE2)

### What happened?

Started the game, gets to "Farewell to my home" and the game crashes.

**Comment by baesik** [comment]
Confirmed this crash on my end.
