### ISSUE TITLE
RE 3, room 506, softlock due to no facility key

### ISSUE THREAD

**Issue by Neil-F2** [IntelOrca/biorand#404]
### Version

3.0.3 (0b004de)

### Seed

R730-1116-ZTHH0HM7AWJ00N09K090ZZZZZZLYZZZZY7Z

### Scenario

RE 3 (Jill)

### Player Character

Nikolai (RE3R)

### What happened?

according to the log the power cable should be in room 506 but i only found a Spray (Wich was a Gunpowder C), i searched the entire room but i don't find another item
Am i missing something or this is the randomizer fault?
Debug save here
[Debug Save.zip](https://github.com/IntelOrca/biorand/files/11580910/Debug.Save.zip)

**Comment by baesik** [comment]
This appears to be a randomizer error. The power cable is the item you get from inserting the facility key into the slot, tested using the debug menu. Seems like the randomizer isn't adding a check for the key to this room.
![RESIDENT_EVIL™_3_NEMESIS_PC10,06PM](https://github.com/IntelOrca/biorand/assets/16945591/08ed3dd4-8014-459b-873c-7afbb028c2f8)

Doing so will take away the facility key, so there will probably need to have at least two facility keys randomized in the future, as unlocking the facility key door will ask you if you'd like to discard the item. 
![RESIDENT_EVIL™_3_NEMESIS_PC10,07PM](https://github.com/IntelOrca/biorand/assets/16945591/f295df20-1cf9-435d-b98b-70c051fb2242)

**Comment by Neil-F2** [comment]
Yeah, i forget that that key with the code is a different item, since the rando don't place that key in any place then the seed is not beatable by normal means
By the way, what you said about the keys, i think the randomizer already place the 2 keys (With ad without codes) when they are needed, and the key with the code has 2 uses, so it will no ask you to discard it after you open the door,, in your case it ask you to discard it since you generated with debug and just 1 use

**Comment by baesik** [comment]
I don't think keys work with quantity. I think it's a flag set in memory. The key with the code won't ask you to discard it at the door because it still has a use/a flag where the rocket launcher storage is. At least I think so.

**Comment by IntelOrca** [comment]
Keys do work with quantities. The wrench and lighter don't, they do have code in the room script to ask you if you want to discard it.
