### ISSUE TITLE
RE3 Item box inventory goin wild

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#405]
### Version

3.0.3

### Seed

R730-5ETN-XNAA50GZ9U520NKMRKK0Z7XLTZZZZZZZXMZ

### Scenario

RE 3 (Jill)

### Player Character

Carlos OG RE3

### What happened?

When I would go into the item box and try to do stuff....it just went wild. At first I thought it was my controller, but my movement wasnt effected when controlling my character and when switching to RE2 there were no issues, it was just with the re3 rando. 
[01_2023-05-27 03^18.41.zip](https://github.com/IntelOrca/biorand/files/11581534/01_2023-05-27.03.18.41.zip)

**Comment by IntelOrca** [comment]
Did you try loading up RE 3 vanilla to see if it still happens?

**Comment by AlbertFnWesker** [comment]
Yea just tried it without the rando on, inventory worked fine.

**Comment by baesik** [comment]
I wasn't able to reproduce an issue. You can use F6 to check what inputs are being sent.

**Comment by Neil-F2** [comment]
I tried and tested, i can't reproduce the issue neither, i decide to go to the next item box to see if it has the problem but, no issues found
