### ISSUE TITLE
RE 3, room 213, glitched enemies after electrocution

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#406]
### Version

3.0.4 (f015691)

### Seed

R730-LF1A-ZTHH0HMZ1YB00N09K4T0ZZZZZZZZZZZZF2Z

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3R)

### What happened?

There are a gaggle of doggos that seem to replace the burnt corpses from increasing the electricity output at the power station. They are off-screen and do not damage the player. Leaving and re-entering the room clears the enemies.

I don't have a recent save made, but I am willing to run through the seed again to make a save if needed.
![image](https://github.com/IntelOrca/biorand/assets/16945591/3aec3573-85d2-499a-96a9-7a13aeb9c7e4)

**Comment by IntelOrca** [comment]
Would be able to provide a save for this? It should just be a case of teleporting to the power room and triggering the electrocution cutscene.

**Comment by baesik** [comment]
I don't have the seed anymore, but I made a save of just before entering the first power thing if that helps any?
[01_2023-05-28 10^17.26.zip](https://github.com/IntelOrca/biorand/files/11585271/01_2023-05-28.10.17.26.zip)
