### ISSUE TITLE
RE 3 room 410 randomized enemies are upside down

### ISSUE THREAD

**Issue by baesik** [IntelOrca/biorand#407]
### Version

3.0.4 (f015691)

### Seed

R720-3T29-ZTHG00PZ9W900QVPGVM4ZZZZZZZZZZZZ62Z

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3R)

### What happened?

The sliding worms that normally appear were randomized into spiders, which is super cool, but they're either out of bounds or upside down.

Debug save attached.

![image](https://github.com/IntelOrca/biorand/assets/16945591/5bbed6d8-2c7a-489c-b99b-8d499182ec7d)

[01_2023-05-27 11^43.55.zip](https://github.com/IntelOrca/biorand/files/11582802/01_2023-05-27.11.43.55.zip)

**Comment by IntelOrca** [comment]
This seed is for RE 2

**Comment by baesik** [comment]
Oh god I sent the wrong seed. I don't have the seed anymore. If I encounter this issue again I'll make sure to post.
