### ISSUE TITLE
Crash when entering room 20F with Granade Launcher equipped

### ISSUE THREAD

**Issue by Neil-F2** [IntelOrca/biorand#411]
### Version

3.0.4 (f015691)

### Seed

R730-R2LC-XXHJ0HCH28F001BNYJ803246CC00RZZZ80Z

### Scenario

RE 3 (Jill)

### Player Character

Leon

### What happened?

When entering the press offices (Room 20F) with a granade launcher equiped crash the game
Leaving a Save data
[Debug Save.zip](https://github.com/IntelOrca/biorand/files/11583333/Debug.Save.zip)
After some testing i can say
Entering with another weapon equipped don't crash the game but equipping the granade laucher in the room and exiting the menu crash the game.
No matter what choice to select, equipping the granade launcher in the room will also crash the game.
Entering without Carlos (Irons here) with the granade launcher equipped or equipping later in the room when Carlos is not with you will not crash the game regardless if nemesis is in the room or not
on one occasion the game did not crash when when i equipped after jumping out the windows, but i could't reproduce that again in future attempts

**Comment by baesik** [comment]
I'm unable to reproduce this issue.

**Comment by Neil-F2** [comment]
Don't know what to say
I tried to see if i can make this happen in other seed but no result, just in this seed happen to me
I also think that in the end it might be a problem of my computer

**Comment by IntelOrca** [comment]
Some crashes are related to the computer (not the game).
Some crashes are related to the version of the game one has.
Some crahses are unknown and don't repeat next time even on same seed.
