### ISSUE TITLE
RE 3, room 503, softlock due to locked elevator door

### ISSUE THREAD

**Issue by AugmentedAntics** [IntelOrca/biorand#413]
### Version

3.0.4 (f015691)

### Seed

R730-JLGK-ZJRG0FMB16200N5QXK60ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Ada (RE2R)

### What happened?

Taking the elevator in the waste disposal plant has you encounter a "locked from the other side" door when riding it. You're able to walk around but you can't ever leave.

**Comment by baesik** [comment]
I can confirm this issue. Once you enter the elevator, you can't leave.

Debug save attached for easy testing.
[01_2023-05-28 02^29.11.zip](https://github.com/IntelOrca/biorand/files/11584189/01_2023-05-28.02.29.11.zip)
