### ISSUE TITLE
RE2 - Leon A Randomized Lighter Causes Softlock with key item in lower part of room 403

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#421]
### Version

v3.0.2

### Seed

R720-5U77-ZTG000ZZ9Y000Z0H3000W64P7AENNZZZ10Y

### Scenario

RE 2 (Leon A)

### Player Character

Leon (RE2)

### What happened?

Since the fixed lighter item for Leon has been randomized, this causes an issue where the Umbrella Key Card is randomized in the dark portion of room 403, and without the lighter, it can't be acquired. Thus a softlock.

**Comment by missingno1711** [comment]
[log_pl0.txt](https://github.com/IntelOrca/biorand/files/11586034/log_pl0.txt)
[log_pl1.txt](https://github.com/IntelOrca/biorand/files/11586035/log_pl1.txt)

**Comment by IntelOrca** [comment]
This has since been fixed
