### ISSUE TITLE
Crash after getting into the warehouse

### ISSUE THREAD

**Issue by SolidFat** [IntelOrca/biorand#422]
### Version

3.0.4 (f015691)

### Seed

R730-GXBB-ZTLA15N53RC00N92EJM0XXZXQZXZGZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Kendo

### What happened?

Game starts, cutscene of breaking into the warehouse plays, along with the dialogue after. Game crashes when the scene with Dario should start.

**Comment by IntelOrca** [comment]
I am going to assume this is because you were Kendo. I have removed him now from RE 3.

**Comment by SolidFat** [comment]
That’s fair. He definitely has some buggy moments playing as him. The Western custom sometimes becomes the entire size of the room too upon entering rooms playing as him. Not a huge deal cuz you can fix it  unequipping it

**Comment by IntelOrca** [comment]
@SolidFat his model is just broken I think, so I have removed it for now.
