### ISSUE TITLE
Freeze before Dario Cutscene

### ISSUE THREAD

**Issue by SolidFat** [IntelOrca/biorand#423]
### Version

3.0.4 (f015691)

### Seed

R730-AV0A-ZTLA15N59R400N92EJM0XXZXQZXZGZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Ark

### What happened?

Intro plays, head to the warehouse, the dialogue plays but when it gets to "However" in the dialogue it black screens and just stays there before the final dialogue line and before the dario cutscene.

**Comment by SolidFat** [comment]
R730-RW8H-ZTLA15N59R400N92EJM0XXZXQZXZGZZZZZZ

Same issue with this one. Gets one line longer to "I'm still alive" but black screen after.

**Comment by IntelOrca** [comment]
I am not able to reproduce this
