### ISSUE TITLE
RE 3, room 30C, graphics corruption when enemy is present

### ISSUE THREAD

**Issue by themitosan** [IntelOrca/biorand#424]
### Version

3.0.4 (5e07460)

### Seed

R730-R3V3-ZT12B1VG9YJ20G9CGMK0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Nikolai (RE3R)

### What happened?

As soon I arrived at R30C, I noticed some object elements with rainbow colors on map, then I opened my inventory and __everything went wild!__

![Untitled](https://github.com/IntelOrca/biorand/assets/32562725/a42733df-ad0f-46d1-b7ef-ef0bf2648334)
![Untitled2](https://github.com/IntelOrca/biorand/assets/32562725/496a47f4-5f6b-4adf-9d2e-57cd92563beb)
![Untitled3](https://github.com/IntelOrca/biorand/assets/32562725/bf84866b-efed-426b-90dd-f6c6d4568ad8)
![Untitled4](https://github.com/IntelOrca/biorand/assets/32562725/51436c21-6097-4834-91f9-264a670caf48)

This already happened sometime ago while I was doing some tests __modifying the seed manually__ to add enemies on safe places, __but this time I added this option only using the GUI - after resetting all seed settings.__

**Comment by IntelOrca** [comment]
What do you mean by:

> modifying the seed manually to add enemies on safe places

**Comment by themitosan** [comment]
On a **previous version** (that didn't had this option available yet), I tried changing the seed values manually to add enemies on safe locations and _got the same result_.

![image](https://github.com/IntelOrca/biorand/assets/32562725/930d8a27-5d60-4046-b773-3deaa4658500)
