### ISSUE TITLE
3.0.4 RE3 NPC jill.re3r crashed in certain cut scene

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#425]
### Version

3.0.4

### Seed

R730-Z81Q-ZTC885XZ3ZK20NRPW4T0308020H4HZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Nemesis (not in default biorand list)

### What happened?

Normally NPC (jill.re3r) work fine EXCEPT cut scene in 20B and 205 
 
(trigger Mikhail's shooting zombies outside the cable car)
20B:255 (0x3966) [MIKHAIL VIKTOR] becomes [CARLOS OLIVEIRA 1 (jill.re3r)] 
20B:255 (0x39EE) [MIKHAIL VIKTOR] becomes [CARLOS OLIVEIRA 1 (jill.re3r)]

(enter door restaurant and return back trigger cut scene)
 205:0 (0x7414) [CARLOS OLIVEIRA 2] becomes [CARLOS OLIVEIRA 1 (jill.re3r)]

I untick  (jill.re3r)  and generate same seed again , other npc work fine in both cut scene.

Is this biorand bugs or just my pc / game bugs ?

[re3.npc.bug.zip](https://github.com/IntelOrca/biorand/files/11642908/re3.npc.bug.zip)

=============================
20C : randomize npc graphic bugs -- missing head -- in cable car ( Mikhail , Jill )

Did you try randomize npc  EXCEPT Jill and Mikhail in cable car cut scene ?  
20C:0 (0x4F5A) [MIKHAIL VIKTOR]
20C:0 (0x5050) [JILL VALENTINE 1]

**Comment by IntelOrca** [comment]
I was not able to reproduce these crashes, I think it is the same issue you have with the previous NPC crashes you raised.
