### ISSUE TITLE
[RE3] Crash when viewing whole cutscene in Room 508

### ISSUE THREAD

**Issue by YoshiChief** [IntelOrca/biorand#432]
### Version

3.0.4 (f015691)

### Seed

R730-ABQZ-ZTHHBHB91Y000NZZZZZ3ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Leon (RE2R)

### What happened?

Room 508, I had the cutscene where Jill would normally have a stand-off with Nicholai until he is killed. I was Leon (RE2R) and the other character was Jake (RE6). When Jake would have died, the game crashed. Can be avoided by skipping the cutscene.

**Comment by IntelOrca** [comment]
@YoshiChief can you please upload a debug save before the room / cutscene occurs. Thanks.

**Comment by YoshiChief** [comment]
[06_2023-06-09 17^45.18.zip](https://github.com/IntelOrca/biorand/files/11708478/06_2023-06-09.17.45.18.zip)

Save file attached. After loading simply walk forward to activate the cutscene and wait.

**Comment by IntelOrca** [comment]
I was unable to reproduce the crash

**Comment by YoshiChief** [comment]
Interesting! I just tried again and it still crashes. The only difference I believe could be the issue is that I have the seamless HD mod installed. I'll see if I can remove it temporarily to see if that's the cause.

**Comment by IntelOrca** [comment]
When it comes to character models, RE 3 seems to either be fine or crash for different people, even with the same version of the game.

**Comment by otamega72** [comment]
Rename folder mod_biorand \ [room] to [room.0] , then load the save file.

**Comment by YoshiChief** [comment]
After renaming the folder and loading the save file, the following occurred.

- The Jake NPC has changed to Marvin (OG), but still retained Jake's voice.
- The cutscene never progresses to the NPC being killed, it however does not crash, but rather stay soft-locked in the cutscene

**Comment by IntelOrca** [comment]
One thing to try next is only enable random NPCs, nothing else. And make Marvin the only NPC. If it crashes, try a different NPC and see if that works.

**Comment by YoshiChief** [comment]
Can no longer reproduce the crash with Jake, Marvin or other NPCs on latest. Closing.
