### ISSUE TITLE
RE 3, room 120, crank not placed

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#433]
### Version

3.05

### Seed

R730-03Y0-XMHZ0HZZ3GA00Z8KW9K0B0C0000B0ZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Jill(RE3)

### What happened?

・I know it's random, but no zombies, crows, worms, or spiders spawn in save rooms or vanilla no enemy rooms.
・Some map Car's door can't open.
・No Normal crank anywhere.
・What happened to these?↓
https://youtu.be/ZbCbOkgEJFY
https://youtu.be/6Whncu-W8yk

**Comment by IntelOrca** [comment]
These are known limitations, some enemy types can only be in certain rooms for RE 3.
The car doors are disabled, because they crash the game if the enemy type is not zombie.
Not sure what you mean by, no normal crank. Are you saying you are soft locked, if so can you provide more information?

**Comment by 123suke** [comment]
>Not sure what you mean by, no normal crank. Are you saying you are soft locked, if so can you provide more information?

Room 120 BAR JACK ALLEY 2 has shutter.
But I can open shutter with crank.
Room 10B had crank in vanilla game.
But there was "no" crank anywhere in the randomize.

**Comment by IntelOrca** [comment]
Okay, I don't place the crank for the shutter. The items will never be important.
One of the issues is that the crank does not work in room 105 (Bar Jack Alley 1) so it will be confusing for players if they try to use the crank before triggering the day/night change.
