### ISSUE TITLE
RE3 Game crash with Zombie dogs in random enemy placement

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#435]
### Version

3.05

### Seed

R730-03Y0-XHHZ0HZZ3GA00Z8KW9K0B0C0000B0ZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Jill(RE3)

### What happened?

・Game Crash when I kill dogs
Room 414,502,508

**Comment by IntelOrca** [comment]
Duplicate of #434
