### ISSUE TITLE
Crash when shooting zombie dogs with Assault Rifle.

### ISSUE THREAD

**Issue by JackDeRipper494** [IntelOrca/biorand#436]
### Version

3.0.5 (b953316)

### Seed

R730-C877-XXQHA9LZ9Y700LVPNUP0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Claire

### What happened?

Consistently crashes when shooting zombie dogs with the assault rifle.
Happens in multiple rooms, with full auto or manual shooting.

**Comment by IntelOrca** [comment]
Duplicate of #434
