### ISSUE TITLE
Crash when entering room 120 from room 122

### ISSUE THREAD

**Issue by JackDeRipper494** [IntelOrca/biorand#437]
### Version

3.0.5 (b953316)

### Seed

R730-C877-XXQHA9LZ9Y700LVPNUP0ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Claire

### What happened?

With every seed/character, when entering room 120 from room 122 after visiting the train car, the game crashes everytime.

**Comment by IntelOrca** [comment]
I think 11d8f05 fixed this issue
