### ISSUE TITLE
The rando is always crashing

### ISSUE THREAD

**Issue by MooMoony** [IntelOrca/biorand#439]
### Version

3.0.5 (b953316)

### Seed

R730-G2WU-R0HMZ9Y090000TZZZZZ300000HZZZZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3)

### What happened?

I don't know why, but once I get the "Belt" to get +2 inventory, the game always crash at the "Y" room (Where we pick up the Battery and the Bronze Book).... Is it possible the rando have difficulty with some card video ?

**Comment by MooMoony** [comment]
A debug save ? If you can explain me I can do it. Or I can check it out with the VoD on Twitch to see the run

**Comment by IntelOrca** [comment]
You have to enable it on the sourcenext launcher by pressing F1. Then in game you can use F5 to open the debug menu and save.
You can also just try and save at a typewriter before the crash happens and attach that.
