### ISSUE TITLE
Rebecca's inventory is crashing the game

### ISSUE THREAD

**Issue by Lirte** [IntelOrca/biorand#441]
### Version

3.0.5

### Seed

R710-AGY3-XNQLF0NZLY340NK2PB40ZZZZZZZZZZZZ7RZ

### Scenario

RE 1 (Chris)

### Player Character

Rebecca

### What happened?

Was playing the game normally, just defeated Yawn and after leaving the room, the game started the poisened sequence. I was playing Richard and another Richard (in Rebecca's place) came. After the cutscene, I started playing Rebecca on the segment to bring the serum to Chris. But the issue is that when I opened her inventory, there was a black square on one of her slots, and my game crashed as soon I tried to move the cursor. Don't know if this is normal or not...

The room when crashed was 20D Pillar Passage, but I think the issue is her inventory anyway

My save: 
[Jill_04_2023-06-15 23^40.48.zip](https://github.com/IntelOrca/biorand/files/11765621/Jill_04_2023-06-15.23.40.48.zip)

**Comment by IntelOrca** [comment]
A lot has changed in latest version, might be fixed now.
