### ISSUE TITLE
RE3: Immediate Crash

### ISSUE THREAD

**Issue by AugmentedAntics** [IntelOrca/biorand#442]
### Version

3.0.6 (d8709f5)

### Seed

R730-H9P1-X5RG8FMB36R00L6QYJ60ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Default (Jill)

### What happened?

The game crashes immediately upon leaving the beginning area and entering the warehouse.

**Comment by IntelOrca** [comment]
Does it crash with random NPCs off?

**Comment by AugmentedAntics** [comment]
Just checked it, and sure enough, it actually doesn't.

**Comment by IntelOrca** [comment]
I was unable to reproduce either of these crashes.
Were the dogs in room 125?

**Comment by AugmentedAntics** [comment]
It was room 10A. This is also really strange, as this seed consistently crashes for me when entering the warehouse and Randomize NPCs is turned on.

**Comment by IntelOrca** [comment]
Some people have had crashes even with the exact same version of the game and seed.
