### ISSUE TITLE
Rebecca not selectable in RE3?

### ISSUE THREAD

**Issue by Atreid3s** [IntelOrca/biorand#445]
Apologies if this is not a bug or i am missing something but i remember to read in the changelog some new playable characters in RE3 including Rebecca but i don't find her in the selectable character field just NPC.

**Comment by IntelOrca** [comment]
Yeah, unfortunately that changelog note was a mistake. I was unable to import Rebecca as her texture is too different from the Leon template that was used, so she requires a bit more work to convert.

**Comment by Atreid3s** [comment]
Thanks you for the clarification.
