### ISSUE TITLE
RE 1, room 603, crash when hunter jumps you

### ISSUE THREAD

**Issue by CesarMartins12** [IntelOrca/biorand#447]
### Version

3.0.5

### Seed

R710-T3W6-X4HHH0MZ9Y000NEVPEVPZZZZZZZZZZZZHZZ

### Scenario

RE 1 (Jill)

### Player Character

Jill (RE1)

### What happened?

When I entered in a corridor the game crashes. 

I made a vídeo on this link

https://youtu.be/hOTKH_tGy20

**Comment by IntelOrca** [comment]
Are you able to provide a debug save before the crash happens?
