### ISSUE TITLE
Problem with seed.

### ISSUE THREAD

**Issue by Matthewsaurusrex** [IntelOrca/biorand#448]
### Version

3.0.7 (0c5a5f2)

### Seed

R730-8H2T-XTHHHHWZ98000N00ZZL3ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

I seem to have an issue getting a seed working with RE3 when any NPC randomisation is selected.

**Comment by IntelOrca** [comment]
This seed works fine for me. What issues are you getting?
