### ISSUE TITLE
RE 3 Crash Closing Game

### ISSUE THREAD

**Issue by Soket13** [IntelOrca/biorand#450]
### Version

3.0.7 (0c5a5f2)

### Seed

R730-XPUL-XMKHH3CZ94000NVPEVP1ZZZZZZZZZZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Kendo

### What happened?

Going for the Y Corridor on streets -> 105 - Bar Jack Alley -> Cutscene with Brad running to bar Crashed on the opening door load. Brad was randomized as Leon(Re4) skin. Don't know if it was enemies or skins that crashed

**Comment by IntelOrca** [comment]
I was not able to reproduce this. According to my logs, no one was changed to Leon (RE4). Did you edit your biorand data in any way?
