### ISSUE TITLE
RE 3, doors to rooms originally connected to room 105 are locked

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#452]
### Version

3.0.7 (0c5a5f2)

### Seed

R730-ZJC4-ZTH00HZZ9F000NVPEVP1XQMZMNPZZZZZ10Y

### Scenario

RE 3 (Jill)

### Player Character

Ada (RE2)

### What happened?

You can see in the screenshot which door would not allow me to pass through again after entering this room. This causes a soft lock. 
![image](https://github.com/IntelOrca/biorand/assets/123828971/1bf10865-873f-44b9-8df6-3c68707bc3c5)
However, I could just jump to the prior room as a workaround.

**Comment by Neil-F2** [comment]
I decide to tested and yeah, can't go back once you enter the room
Here is a Save for easy testing
[SaveData.zip](https://github.com/IntelOrca/biorand/files/11813978/SaveData.zip)
It didn't look like is required to go there to be able to go to the next segment thankfully

**Comment by TheMitu97** [comment]
I can confirm that this happened to me before at least twice across different seeds. One time it was shopping alley safe room door that closed behind me and couldn't go back, another one was operation room in RPD and as it was the only door in this room, I got soft locked pretty hard. Unfortunately it was few versions ago and I don't have those seeds anymore.

**Comment by missingno1711** [comment]
I have another seed that does this. Strange. Not logging another issue, its the same symptom.
R730-09NX-ZTH00HZZ9F000Z0HZZZ3XQMZMNPZZZZZ10Y
![image](https://github.com/IntelOrca/biorand/assets/123828971/53374ab9-1fcc-490e-b1da-2f4f43626924)

**Comment by missingno1711** [comment]
Not a soft lock however.
![image](https://github.com/IntelOrca/biorand/assets/123828971/587cfdba-0497-4175-bfeb-81c2af52b909)
