### ISSUE TITLE
RE3 - Rebecca Speaking Like Ark

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#455]
### Version

v3.0.7

### Seed

R730-4YH5-ZTH00HZZ9F000Z0HZZZ3XQMZMNPZZZZZ10Y

### Scenario

RE 3 (Jill)

### Player Character

Wesker RECV

### What happened?

Hilarious. But Rebecca sounds like Ark in the intro...
![image](https://github.com/IntelOrca/biorand/assets/123828971/1b2cee1a-37e7-40b4-8d92-6102cd7e1362)

**Comment by Neil-F2** [comment]
How strange, in my game Ark actually appeared in this seed
![2023-06-21 19-56-05](https://github.com/IntelOrca/biorand/assets/130115877/2ee67cf5-ab1a-4c14-8106-b3fa16652fbb)

**Comment by missingno1711** [comment]
Ok. So I think this is a problem on my end. I'm on Windows 11 and now the randomizer is not being applied at times. Where should we be installing Biorand and the games?

**Comment by IntelOrca** [comment]
> Where should we be installing Biorand and the games?

Anywhere you like, but keep them seperate. I have my games on a dedicated drive:
* `F:\games\re1`
* `F:\games\re2`
* `F:\games\re3`

BioRand might be somewhere else:
* `C:\Users\Leon\Desktop\biorand`

**Comment by missingno1711** [comment]
> > Where should we be installing Biorand and the games?
> 
> Anywhere you like, but keep them seperate. I have my games on a dedicated drive:
> 
> * `F:\games\re1`
> * `F:\games\re2`
> * `F:\games\re3`
> 
> BioRand might be somewhere else:
> 
> * `C:\Users\Leon\Desktop\biorand`

So maybe the info I need is somewhere else, but I've noticed issues on my end involving running the games on administrator mode and install location. I am on Windows 11, I don't know if that contributes to the problem. So...
1. Do we need to run admin mode for both Biorand and the game? Does biorand run the game in admin mode when you launch from there?
2. I have my games on the ProgramFiles x 86 directory. Is that an issue?
3. Potentially, the issues I'm seeing are Windows 11 related. I've been getting c++ runtime distributable errors the other day, that I resolved by Windows update. Do you have anything on this?

Again. Thank you!

**Comment by IntelOrca** [comment]
> Do we need to run admin mode for both Biorand and the game? Does biorand run the game in admin mode when you launch from there?

If your game is in a protected location such as Program Files then you will need to use admin for BioRand. If your game is in a location that does not require admin rights like anything below your user directory, you do not need admin.

I am on Windows 11 and do not have any issues.
