### ISSUE TITLE
RE3 - Not Randomizing Doors Or Items

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#456]
### Version

3.0.7 (0c5a5f2)

### Seed

R730-05CE-ZTH00HMZ9Y000Q0HEVP1ZZZZZZZZZZZZ10Y

### Scenario

RE 3 (Jill)

### Player Character

Random

### What happened?

There is an odd bug going on for me. Biorand appeared to be randomizing my RE3 just fine, but now, even though the generation completes without fail, RE3 is not recognizing the randomized doors or items. Is there anything I should check on my end? I'm on Windows 11. I have already checked administrator settings and I do open Biorand with it. The music and character are randomized.
![image](https://github.com/IntelOrca/biorand/assets/123828971/8c087c11-0396-4dc1-81c5-3f684032147e)

**Comment by missingno1711** [comment]
I don't have a screenshot for you. But I grab the first aid spray in the warehouse in the beginning of the game, and it's still a first aid spray.

**Comment by missingno1711** [comment]
Ok. So it works on original mode (heavy). Does the randomizer only work on original?

**Comment by IntelOrca** [comment]
I thought it worked on both difficulties, maybe not.

**Comment by IntelOrca** [comment]
I just tried light mode and that works.

**Comment by otamega72** [comment]
Maybe what missingno1711 mean is " Does the randomizer only work on **arrange mode**"  ?

**Comment by IntelOrca** [comment]
What is the benefit of playing in arrange mode?

**Comment by otamega72** [comment]
No any benefit or different , unless you are playing Komizo's mod.

**Comment by missingno1711** [comment]
I think this one can be closed.

If there is anything going on, it's got to be on my end. Recently, windows 11 updated and I would randomly get a Microsoft Visual C++ Runtime Library error message. This happens not only for RE3, but for RE2 and RE1 as well. I changed them to run on compatibility mode for Windows XP and that seems to have calmed it down. I'll see if running RE3 on compatibility mode will do the trick. 

And about the arrange mode / original mode, I heard its a difference in damage enemies dish out / nemesis health. I agree, doesn't matter. But if there is an implied difficulty I should be choosing, let me know.

Thank you all for looking into this. I really appreciate it.
