### ISSUE TITLE
RE 3, room 122, enemy event crashes the game if not zombie

### ISSUE THREAD

**Issue by Soket13** [IntelOrca/biorand#457]
### Version

3.0.7 (0c5a5f2)

### Seed

R730-XW0R-T4KHH3CZ94H00NVPEVP1ZZZZZZZZZZZZ00Z

### Scenario

RE 3 (Jill)

### Player Character

Jill RE3

### What happened?

Returning downtown on the barricade alley (108) The zombie crasing window animation was a Brain sucker jumping and crashed. closing the game. I didn't patched any randon NPC or main character

**Comment by IntelOrca** [comment]
Can you provide a debug save before this event happens?

**Comment by Neil-F2** [comment]
Can confirm the crash
Here is a save for testing
[SaveData.zip](https://github.com/IntelOrca/biorand/files/11854023/SaveData.zip)

**Comment by IntelOrca** [comment]
@Neil-F2 thanks
