### ISSUE TITLE
RE 2, room 219, possible crash when Ben is replaced with EM5A

### ISSUE THREAD

**Issue by PlantBrain** [IntelOrca/biorand#460]
### Version

3.0.6 (d8709f5)

### Seed

R721-LQ1W-XCZWH0BZ9R000KRY36VEEE5WF1EGCRZZA1Z

### Scenario

RE 2 (Leon B)

### Player Character

Leon (RE2)

### What happened?

After sliding down the vent from the clock tower, the cutscene with Ben getting sliced across the chest by Birkin freezes. In this seed Ben is replaced by Kendo, it crashes just as Kendo is struck by Birkin.

**Comment by Neil-F2** [comment]
Damn, that seed is hard
Anyway, can confirm the crash
Here is a save
[SaveData.zip](https://github.com/IntelOrca/biorand/files/11873746/SaveData.zip)

**Comment by PlantBrain** [comment]
Yeah it really was a run full of trial and error. The only other weapon in the RPD was the flamethrower. The rest were in the factory which made the latter half a breeze.

Didn't think about attaching a save sorry! So thanks for going through that so I didn't have to again.
