### ISSUE TITLE
RE1 Swap Characters

### ISSUE THREAD

**Issue by Snipzu** [IntelOrca/biorand#468]
### Version

3.0.8 (a1e8985)

### Seed

R710-2WT6-ZTPR00C4CK58H11M88M0EVZZZZZZZZZZ10Y

### Scenario

RE 1 (Chris)

### Player Character

Regina/Richard

### What happened?

Both characters crash at the start main hall. Suspect custom characters crash swap characters.

**Comment by IntelOrca** [comment]
Duplicate of #466
