### ISSUE TITLE
biorand for Re 1 crash at start

### ISSUE THREAD

**Issue by nico8521** [IntelOrca/biorand#471]
### Version

3.0.8 (a1e8985)

### Seed

R710-R5NE-ZJHHH0MJ9F660N9KCKK5GXZZZZZZZZZZRKZ

### Scenario

RE 1 (Chris)

### Player Character

Wesker

### What happened?

![image](https://github.com/IntelOrca/biorand/assets/134842253/b5ab9926-041b-4c1c-9614-0727da9b0055)

I installed the latest version to try new characters like npc, unfortunately with this version the game crashes

**Comment by IntelOrca** [comment]
Works in latest build

**Comment by nico8521** [comment]
> Works in latest build

i'm using the latest version, but it doesn't work, after the initial video of resident evil 1, the game crashes

**Comment by nico8521** [comment]
> Funziona nell'ultima build

I tried without replacing player character, it works, basically it doesn't play with other characters

**Comment by IntelOrca** [comment]
@nico8521 it works in the latest dev. build, but it has not yet been released.
