### ISSUE TITLE
RE 1, room 305, player sometimes changes

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#475]
### Version

3.0.8

### Seed

R710-3B2X-ZTRHB0ZZCR64HNNMKATYVYZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

chris

### What happened?

  Connected 30D:2 [FLAMETHROWER] to 305:2 (locked 138)
305 back to 30D , chris's inventory changed to jill's.
[g Chris_01_2023-07-02 23^51.33.zip](https://github.com/IntelOrca/biorand/files/11930150/g.Chris_01_2023-07-02.23.51.33.zip)

**Comment by IntelOrca** [comment]
This can also happen when taking the lift in the garden. It is a very annoying issue/bug in the game.
