### ISSUE TITLE
RE1 error at the start of the game

### ISSUE THREAD

**Issue by Diamonti** [IntelOrca/biorand#477]
### Version

3.0.8

### Seed

R710-W7JR-WNFA60LZ9P000MWPTKP4ZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Didn't get far enough to tell.

### What happened?

![Capture](https://github.com/IntelOrca/biorand/assets/128434008/234013ce-7173-4a07-b546-39367ff30534)

I get this error as soon as the game starts. Instructions for Classic Rebirth specifies to copy the JPN folder and not the horr so I'm not sure why it is looking for something in a folder I am not supposed to copy.

**Comment by Diamonti** [comment]
To add to this, when I have random characters set, some seeds will just close the game after the "They escaped into the mansion" dialogue with no error or pop up.

**Comment by IntelOrca** [comment]
I was unable to reproduce this, (after removing the enemies folder from the generated folder).
The crash @Diamonti mentioned is already fixed

**Comment by Diamonti** [comment]
@IntelOrca Would you be able to tell me what the fix is? I am not sure what you mean by "removing the enemies folder"

**Comment by IntelOrca** [comment]
@Diamonti Does the vanilla game work for you? By the looks of things, your RE 1 installation is missing some sound files. So maybe reinstall or find another copy to install?

The biorand crashes will be fixed in the next update.

**Comment by Diamonti** [comment]
@IntelOrca I did a fresh install, following the instructions very closely. I can get the vanilla game to run now, but when I boot Biorand I get to the text "They escaped into the mansion" then the game just closes, no crash error or anything along those lines. Going to download 3.0.9 and see if anything changes.

**Comment by Diamonti** [comment]
@IntelOrca Just to update, a combo of fresh install and new version of Biorand got the game to actually load into the mansion. Going to actually play it in a bit but so far it looks cleared up. cheers.

**Comment by IntelOrca** [comment]
@Diamonti yeah the crash in 3.0.8 was a regression but should be fixed in 3.0.9 like you have observed. Good luck!
