### ISSUE TITLE
In room 21A Parasite Alley you grab the Merc's Diary even with the randomize files option activated

### ISSUE THREAD

**Issue by RyuuzakiL5** [IntelOrca/biorand#487]
### Version

3.0.8

### Seed

R730-3U3T-XXHHCH7Z9Y000JJKW9M0ZZZZZZZZZZZZ42Y

### Scenario

RE 3 (Jill)

### Player Character

Mr. X

### What happened?

After bringing an item the tex says the mercenary is hold something and instead of getting another random item, I get a file cães Mercy's Diary.

**Comment by RyuuzakiL5** [comment]
By the way. 
The same happens with rom 304 CT Hall 1F
With the mercenary body, you get an item and after that a file called Operation Instruction

**Comment by IntelOrca** [comment]
This is deliberate. The problem is that if it is an item and you choose not to pick it up, the first item is not registered as being taken and you can pick up infinite supply of the first item. It is an odd glitch and I simply chose not to randomize the document.

**Comment by RyuuzakiL5** [comment]
I see.

There is another one, about using one of the balls (crystal, ambar and obsidian) and leaving the room. When you come back, the ball is not at the painting anymore. Anyway, I used debug mode to fix this.

**Comment by IntelOrca** [comment]
> There is another one, about using one of the balls (crystal, ambar and obsidian) and leaving the room. When you come back, the ball is not at the painting anymore. Anyway, I used debug mode to fix this.

I am unable to reproduce this. I jumped to that room, gave myself the amber crystal and placed it in the painting. Left the room, came back and it was still in the painting.
