### ISSUE TITLE
Bowgun

### ISSUE THREAD

**Issue by Smurphy2014** [IntelOrca/biorand#488]
### Version

3.0.9

### Seed

R720-8T1V-XHZB304Z1Y000N1U46940ZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Leon normal 

### What happened?

equipping the bowgun just crashes the game when it was in the spot of the lighter in the menu. found out also testing the other weapons after trying to just playthrough it without it i am assuming it is all of claire's gun's doing it on leon a side at least did not test b but yeah i got the sparkshot from kendo and try to equip it also craahed.

**Comment by IntelOrca** [comment]
Caused by empty Dario PLD folder accidentially making it into release.
