### ISSUE TITLE
Tried on this outfit which was posted on discord (RE3)

### ISSUE THREAD

**Issue by nico8521** [IntelOrca/biorand#489]
### Version

3.0.9 (4d8d5d6)

### Seed

R730-151L-ZTZR8QC9CRK00NK4XK41ZZZG0YZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

JillValentine_RE3RWounded

### What happened?

![image](https://github.com/IntelOrca/biorand/assets/134842253/f4eac6a1-b917-455f-804a-0ec703f6d438)

Tried on this outfit which was posted on discord , I don't know if I did it right, but I put the winrar content I found in discord in the respective folders.

after the introductory video, after the black screen with initial subtitles, with this outfit the game crashes

![image](https://github.com/IntelOrca/biorand/assets/134842253/dd95e582-4a4a-43ca-9a4e-911827a32e38)

**Comment by IntelOrca** [comment]
Did you managed to figure out the problem?
