### ISSUE TITLE
RE3 - Low Audio For Some Tracks

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#490]
### Version

v3.0.9

### Seed

Any

### Scenario

RE 3 (Jill)

### Player Character

Any

### What happened?

I'm not sure if I'm the only one encountering this, but whether I use randomized RE1, RE2, RECV, or my own custom bgm's, a lot of areas have them playing very quietly. I understand if that's a limitation on what track they replace and setting, but at this point I'm not very sure.

**Comment by IntelOrca** [comment]
The randomizer reduces the volume of BGM so that voices are more audible. The amount depends on the game.

**Comment by missingno1711** [comment]
I do notice that a lot of my custom bgms are lower than the base RE1, RE2, RE3 music. I did make them .ogg format (mono) basing on the quality of the prebuilt bgms you provided. Would you recommend I try .wav format?

Also, a little of topic question, do you have plans adding in more bgms? Such as.....RE Outbreak/RE Outbreak File 2?

**Comment by IntelOrca** [comment]
The format won't make a difference to volume. You can try modifying your BGM to be louder.
The BGM that comes with biorand increases the size of the download quite a bit, and slows down deployment times. So I don't particularly want to go overboard with the BGM that is supplied. Players can provide as much of their own BGM as they like.

**Comment by missingno1711** [comment]
Ok. I will try that out. Thank you!
