### ISSUE TITLE
RE1 Biorand Error - Ran out of free slots

### ISSUE THREAD

**Issue by JWeavs** [IntelOrca/biorand#493]
### Version

3.0.9 (4d8d5d6)

### Seed

R710-0000-ZTQA00C72Z660N9MMAM0ZZZZZZZZZZZZZLY

### Scenario

RE 1 (Chris)

### Player Character

Chris as Wesker and Jill as Rebecca

### What happened?

I went to generate the seed, but when it finished I got an error message saying there were no more free slots left and to report this error to you.

**Comment by IntelOrca** [comment]
No longer accepting reports for this issue. Work around is to try another seed.
