### ISSUE TITLE
RE1 CLASSIC REBIRTH Stopped Working

### ISSUE THREAD

**Issue by ghost** [IntelOrca/biorand#494]
![resident evil classic rebirth bug](https://github.com/IntelOrca/biorand/assets/139450532/b75e7d0c-0eff-4202-8369-0a2741486c2b)
This picture is in Spanish, but I will explain this issue.

When I play Ada's Mod with Resident Evil Classic Rebirth, the game crashes right after I choose the mod.

Has this patch always had that problem, or does my laptop have a bug?

**Comment by IntelOrca** [comment]
This is the issue tracker for BioRand, not Rebirth or Ada's mod. I am not sure why you are hitting this issue.
