### ISSUE TITLE
crash at the door leading to the bridge

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#496]
### Version

3.0.9

### Seed

R730-WHKE-XNAA50QZ9W120LJMWK21XTACF857MXZZCXY

### Scenario

RE 3 (Jill)

### Player Character

Ada RE2

### What happened?

When about to leave the park, that door that leads to the factory. it crashed. Also a request, could we get an option to turn off the custom "biorand" audio in the beginning? I'd rather not hear streamers saying it. Gonna attach a save file right before that door it crashes at. 
[17_2023-07-19 02^09.25.zip](https://github.com/IntelOrca/biorand/files/12092631/17_2023-07-19.02.09.25.zip)

**Comment by IntelOrca** [comment]
Unfortunately I am not able to reproduce this crash, and neither were you on your second attempt. You teleported to the same room that the door connected to, so had it been a genuine issue you would have got a crash a second time. I think this might just be one of those occausional crashes that you can't do much about.
