### ISSUE TITLE
zombie dog in the wall at room 215.

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#500]
### Version

3.0.9 (1d6b330)

### Seed

R720-7LW9-XRZZ10ZZ4Y1RH7Q9K79K4ZV5W53H5FQ0Z00YZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Rachael

### What happened?

Since the beta, I think it's possible to move enemies after picking up an item in room 215.
However, in the case of the zombie dog, the dog ended up inside the wall.

sample:
https://youtu.be/rbEAiEDmjFU?t=3465

**Comment by IntelOrca** [comment]
Closing out of bound enemy issues for now as it is a common issue
