### ISSUE TITLE
Partner characters disappear in Room 40D and 501.

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#503]
### Version

3.0.9 (1d6b330)

### Seed

R720-7LW9-XRZZ10ZZ4Y1RH7Q9K79K4ZV5W53H5FQ0Z00YZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Rachael

### What happened?

I'm sorry if I did it on purpose due to the enemy's attack problem,
The partner character disappears in these two rooms.

sample
https://youtu.be/r8p4dzXgpCk?t=1017

**Comment by IntelOrca** [comment]
This is intentional, it prevents the game from crashing.
