### ISSUE TITLE
On the cable car partner Sherry keeps walking in the same direction.

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#504]
### Version

3.0.9 (1d6b330)

### Seed

R720-7LW9-XRZZ10ZZ4Y1RH7Q9K79K4ZV5W53H5FQ0Z00YZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Rachael

### What happened?

Inside the cable car, she went from Ada to Sherry. Also, she has a machine gun.
However, she never attacked G's arm, just ignored the player and kept walking in the same direction.

To begin with, I sometimes see Sherry's type of partner character generated by the room in the Leon scenario.
Is it impossible for the Leon Scenario to create only partner characters that can attack enemies, even if it's Sherry?
I would be happy if I could fix both the type and character, either Ada or Sherry.

sample
https://youtu.be/r8p4dzXgpCk?t=962

**Comment by IntelOrca** [comment]
I could limit it to Ada which may have anyone overlayed on to her.

**Comment by IntelOrca** [comment]
I don't think this is an issue anymore
