### ISSUE TITLE
Ada rises up inside Hunk attacked by Invisible G.

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#505]
### Version

3.0.9 (1d6b330)

### Seed

R720-7LW9-XRZZ10ZZ4Y1RH7Q9K79K4ZV5W53H5FQ0Z00YZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Rachael

### What happened?

NPC Hunk attacked by Invisible G will stand up after the event and walk normally with Sherry's motion.

samples
https://youtu.be/r8p4dzXgpCk?t=1228

**Comment by IntelOrca** [comment]
Ignoring the issue for now, it is very old and doesn't affect gameplay.
