### ISSUE TITLE
Sherry does not work properly in Main Shaft's Ada Fall cutscene.

### ISSUE THREAD

**Issue by 123suke** [IntelOrca/biorand#508]
### Version

3.0.9(1d6b330)

### Seed

R720-7LW9-XRZZ10ZZ4Y1RH7Q9K79K4ZV5W53H5FQ0Z00YZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Rachael

### What happened?

In the Mainshaft cutscene, when Ada turns into Shelly, she walks far too long before she raises her unloaded gun for the first time.

sample
https://youtu.be/r8p4dzXgpCk?t=2201

**Comment by IntelOrca** [comment]
Probably need to exclude some NPCs, will wait for reproduce in newer version
