### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Septictank5** [IntelOrca/biorand#510]
### Version

3.0.9 (4d8d5d6)

### Seed

R730-W41W-TN584RCJUWB00LR6UUR0000000000WZZ02Y

### Scenario

RE 3 (Jill)

### Player Character

Claire

### What happened?

Game crashed upon entering the large area with the bus (first pass through).  In og, theirs normally 3 dogs on first pass, and crows bust through window on way back for pharmacy trip.  Unfortunately, i don't have a saved game.

**Comment by Septictank5** [comment]
[02_2023-07-25 00^10.17.zip](https://github.com/IntelOrca/biorand/files/12166607/02_2023-07-25.00.10.17.zip)

The save file

**Comment by IntelOrca** [comment]
When I loaded the saved game and jumped to 200, which I assume is the room you are referring to. I can't reproduce any crash.
