### ISSUE TITLE
Out of bounds Zombie

### ISSUE THREAD

**Issue by Neil-F2** [IntelOrca/biorand#511]
### Version

3.0.9 (4d8d5d6)

### Seed

R720-BYVF-XTHH00NAAPC8HGLP3JN47ZXQZZZZZZZZZZY

### Scenario

RE 1 (Chris)

### Player Character

Annette

### What happened?

[SaveData.zip](https://github.com/IntelOrca/biorand/files/12178305/SaveData.zip)
I forgot the number of the room lol, but i left a save inside the room where the bug is happening
Anyway there seems like there is a zombie out of bounds in that room, if you aim, annette aims to the wall but there is nothing there, and there isn't any other zombie in that room

**Comment by Neil-F2** [comment]
Seems like it happens the same thing in RE2
![Captura de pantalla (678)](https://github.com/IntelOrca/biorand/assets/130115877/8b863261-ba89-41ec-93f5-d1fcf8067d29)
![Captura de pantalla (679)](https://github.com/IntelOrca/biorand/assets/130115877/da1a28f6-4ddf-4e1e-8708-0f95378826b6)
(NGL she looks nice with that white shirt)
Also with playable Annette (her Hand)
![Captura de pantalla (677)](https://github.com/IntelOrca/biorand/assets/130115877/779392a7-4c18-40c2-b0f9-3a6651e486e3)

**Comment by IntelOrca** [comment]
Closing out of bound enemy issues for now as it is a common issue
