### ISSUE TITLE
biorand 3.1.0 cannot generate re2 randomize npc's seed if pld files had been modified 

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#512]
### Version

3.1.0

### Seed

any seed

### Scenario

RE 2 (Leon A)

### Player Character

any

### What happened?

biorand 3.1.0 cannot generate re2 seed (randomize npc's ticked ) if pld files had been modified. (adding back dodge action)

back dodge file :
https://www.moddb.com/games/resident-evil-2/downloads/re2-dodging-skin-playable-boss-skin-for-biorand-20230706/#8593918

![biorand 3 1 0 gen kendo bug](https://github.com/IntelOrca/biorand/assets/120957601/347a29be-c813-433c-969b-7e6b3d9ac93f)

**Comment by IntelOrca** [comment]
This is not a bug, but a new requirement. The program now converts PLD files automatically to EMD files and that means the PLD files must conform to a standard. It not difficult to fix, and is down to the texture. Page 0 must have the body, page 1 must have the face. Page 2 and 3 must be identical to page 0 and 1 but optionally can be made to look like zombie or have gore.
