### ISSUE TITLE
failed to generate

### ISSUE THREAD

**Issue by Cpttheweeb** [IntelOrca/biorand#516]
### Version

3.1.0 (ef39513)

### Seed

R730-T6PG-ZJHH0HQZ9Y000QQCRAW431000000000RZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Chirs

### What happened?

when i try to generatin the seed it show me error message that saying an error occured during generation Please report this seed and try another

**Comment by IntelOrca** [comment]
I am unable to reproduce this issue, are you able to send me the log files?

**Comment by Cpttheweeb** [comment]
[log_pl0.txt](https://github.com/IntelOrca/biorand/files/12207589/log_pl0.txt)
I was wrong for the game that gives me a problem it's resident evil 3 when I try to create the seed

**Comment by IntelOrca** [comment]
This is likely caused by a slightly different version of the game, or unwated files in your RE 3 install directory. The next release will have a potential solution to this.
