### ISSUE TITLE
Biorand 3.1.0 RE1 Battery in room 715:5

### ISSUE THREAD

**Issue by Josh2084** [IntelOrca/biorand#517]
### Version

3.1.0 (ef39513)

### Seed

R710-W446-NTTKH0MZ9F040N52TUP4ZZZZZZZZZZZZZZGXZ0RZZZ

### Scenario

RE 1 (Jill)

### Player Character

Claire

### What happened?

3.1.0 RE1

Spoiler log says one of the key item batteries is in room 715:5. I can't recall seeing any rooms over 5XX
[R710-W446-NTTKH0MZ9F040N52TUP4ZZZZZZZZZZZZZZGXZ0RZZZ_SpoilerLog.txt](https://github.com/IntelOrca/biorand/files/12207665/R710-W446-NTTKH0MZ9F040N52TUP4ZZZZZZZZZZZZZZGXZ0RZZZ_SpoilerLog.txt)

**Comment by IntelOrca** [comment]
Rooms 6XX and 7XX are just Mansion 2 versions of 1XX and 2XX. 715 is the Stuffed Room.
