### ISSUE TITLE
RE 3, Ashley PLD crashes the game

### ISSUE THREAD

**Issue by ShiinWindragon** [IntelOrca/biorand#521]
### Version

3.1.0 (ef39513)

### Seed

R730-F35Q-ZTEECEWL9P000ZNZZZZZ3ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Ashley (according to the log)

### What happened?

During the starting sequence when there's an explosion and the character comes out, the game crashes right before the explosion.

**Comment by IntelOrca** [comment]
Ashley is broken in RE 3 (model too complex), I have now just fixed her, so she should be playable in the next release.
