### ISSUE TITLE
RE1 Jill Terrace room bug

### ISSUE THREAD

**Issue by BittyMERC** [IntelOrca/biorand#522]
### Version

v3.1.0

### Seed

R712-1WU9-WNHHH04Z9Y88HNN9KC9K0ZYZZZZZZZZZZZZZZ3XZZZ

### Scenario

RE 1 (Jill)

### Player Character

Steve (CV)

### What happened?

playing through the game normally. i finish everything up that i can in the main mansion but i couldnt find the star crest. upon looking into the log it stated it was in the room 212 terrace. which means it would have been in place of the grenade launcher. but when i went into the terrace the first time i had the barry cutscene barry was actually Ada (RE2) and with the cutscene he gives you the grenade launcher. well he gave me it and it was the grenade launcher even tho i had already gotten the grenade launcher in room 209 Bedroom. so i had 2 grenade launchers and no star crest. not sure if this will happen with other seeds as well or if its just this seed that changed the crest back to the grenade launcher while doing this cutscene.

**Comment by IntelOrca** [comment]
I was unable to reproduce this. I started a new game, went upstairs, went into corridor, then back into hall, then into terrace and Claire gave me the star crest.
