### ISSUE TITLE
bug claire 

### ISSUE THREAD

**Issue by Encantador69** [IntelOrca/biorand#523]
### Version

3.1.0 (ef39513)

### Seed

R730-JJ1Z-XN96UMWZ9YM00NQKAAZB3ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

claire R2R

### What happened?

BUG TEXTURES MISSING

**Comment by IntelOrca** [comment]
Probably a duplicate of #531
