### ISSUE TITLE
RE 3, 107, crash due to Marvin 2 as NPC

### ISSUE THREAD

**Issue by TheMitu97** [IntelOrca/biorand#525]
### Version

3.1.0 (ef39513)

### Seed

R730-VTJZ-XJHE70VFLM710V500W000XNGBZPAUTZXZZZ0Y00000

### Scenario

RE 3 (Jill)

### Player Character

Mikhail 

### What happened?

As title says, game crashes during bar cutscene, as soon as the camera angle is supposed to switch (I swear this bar is cursed for some reason, lots of crashes always happen there). Another thing to mention is that some zombies in the alley before bar have white heads for some reason.
According to log file, Brad in bar scene became Ark, so I'm guessing his swap is causing the game to crash

**Comment by IntelOrca** [comment]
> I swear this bar is cursed for some reason

Unfortunately many of the NPCs crash this room, you just found one more.
