### ISSUE TITLE
RE 3, 105, crash caused by Irons NPC

### ISSUE THREAD

**Issue by Kogohazan** [IntelOrca/biorand#528]
### Version

3.1.0 (ef39513)

### Seed

R730-TLK3-NNN854QZ9Y000M1000003ZZZZZZZZZZZZZZZZ00000

### Scenario

RE 3 (Jill)

### Player Character

Carlos (RE3)

### What happened?

In room 105 (cut 9) Room right before Brad would shoot a zombie and run into the bar. The game crashed. As soon as I made the transition from cut 10 to cut 9 the game froze for about 5 seconds and then completely shut down and closed out.

**Comment by IntelOrca** [comment]
Fixed in f6f4add294dd3a004e685956634a2839bbc8e788
