### ISSUE TITLE
RE 1, room 500, softlock when escape sequence active

### ISSUE THREAD

**Issue by johnnybeard42** [IntelOrca/biorand#529]
### Version

3.1.0 (ef39513)

### Seed

R710-6U5W-ZJHH60MY9Y00HNN92NUP4XZXZZZZZZZZZZKPYL02WZ

### Scenario

RE 1 (Jill)

### Player Character

Leon (RE2 Remake)

### What happened?

Quite a bit into the seed the game softlocks if you go for the 'good ending' scenario, if you go through certain doors, defeat the first Tyrant boss, escape with "Barry" and "Chris" you get to the final door before the emergency exit and there's no way to open it and the only doors accessible from that point are the guardhouse door before Plant 42 and the room with the projector. This is because the door you normally come from (which is the elevator descending into the lab) is inaccessible and says "there's no turning back".

There may be a way around this seed if you don't take the specific path I took, I'm still going to play on the seed to find out, but I wanted to flag it up.

**Comment by IntelOrca** [comment]
Can you please attach your saved game

**Comment by johnnybeard42** [comment]
Here it is :)

Cheers,
JB

**Comment by IntelOrca** [comment]
> Here it is :) Cheers, JB

I don't see it. You need to go on GitHub directly and upload a zip file containing the saved game. I am not sure you can use the e-mail reply system.

**Comment by johnnybeard42** [comment]
No problem, here you go :)

[Jill_03_2023-08-02 13^33.07.zip](https://github.com/IntelOrca/biorand/files/12267019/Jill_03_2023-08-02.13.33.07.zip)

**Comment by IntelOrca** [comment]
@johnnybeard42 I loaded your save and teleported to room 500 and I could go through the elevator door.
Are you able to provide a debug save at the point you can't go through it?

**Comment by johnnybeard42** [comment]
[Save file at soft lock.zip](https://github.com/IntelOrca/biorand/files/12267525/Save.file.at.soft.lock.zip)
[Save file pre-soft lock.zip](https://github.com/IntelOrca/biorand/files/12267526/Save.file.pre-soft.lock.zip)

I've uploaded a debug save and a my last formal save and provided the pathway to the softlock below:
Load file
> 510 Maze B
> 50C Front of Elevator
> 405 Center Passage
> 101 1F Left Stairs
> 508 Double Lock
> 500 Under Fountain
*SOFTLOCKED*

**Comment by IntelOrca** [comment]
> 

thanks, I can reproduce it now
