### ISSUE TITLE
Can't pick Ark in RE1, enemies won't replace?

### ISSUE THREAD

**Issue by OGOctupleOG** [IntelOrca/biorand#532]
### Version

3.1.0 (ef39513)

### Seed

R710-MZVT-XQHHH0MZ9Y1C0NN9KPEB6ZZZZZZZZZZZZZ7HYLUZZZ

### Scenario

RE 1 (Chris)

### Player Character

Ark

### What happened?

I'm trying to generate a seed where you play as Ark over Chris, but it says Failed to Generate: Index Out of Bounds. Then it links to the audio .ogg files for Ark Thompson. Also when I chose another character, the Hunters and Tyrant were not replaced by skins.

**Comment by IntelOrca** [comment]
Seems to be fixed in latest dev. build.
