### ISSUE TITLE
RE3 room105 Game Crash

### ISSUE THREAD

**Issue by Nick97it** [IntelOrca/biorand#533]
### Version

3.1.0 (ef39513)

### Seed

R730-CZ4R-XTHHHHC99Y000L3ZZY3T0ZZZZZZZZZZZZZZZZ00000

### Scenario

RE 3 (Jill)

### Player Character

Alyssa

### What happened?

the game crashes shortly after entering room 105. or the room at the bottom, passing the boutique.

**Comment by IntelOrca** [comment]
Duplicate of #528
