### ISSUE TITLE
3.1.0 RE3 seed run out of free item slots

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#537]
### Version

3.1.0

### Seed

R730-NY2V-ZTM885XZ3VY20QNHMHLK0C00H200H200ZZEXZYZZZZ

### Scenario

RE 3 (Jill)

### Player Character

kendo

### What happened?

![re3 gen bug](https://github.com/IntelOrca/biorand/assets/120957601/00c2b870-e5e7-429b-800e-568f1f5e0a73)

**Comment by IntelOrca** [comment]
I have changed this message in dev. builds now to explain and just say "try another seed". I am no longer taking reports of this issue, as it is just down to a non-perfect door randomizer.
