### ISSUE TITLE
3.1.0 re3 room 11b npc graphic glitch 

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#538]
### Version

3.1.0

### Seed

R730-M01E-ZTM885XZ3XY20QNHMHL20C00H200H200ZZEXZYZZZZ

### Scenario

RE 3 (Jill)

### Player Character

kendo

### What happened?

graphic glitch :  
11B:0 (0x4D42) [NIKOLAI ZINOVIEV] becomes [CHIEF IRONS (david)]
11B:0 (0x4E00) [NIKOLAI ZINOVIEV] becomes [CHIEF IRONS (david)]
[bug 03_2023-08-08 01^13.18.zip](https://github.com/IntelOrca/biorand/files/12283776/bug.03_2023-08-08.01.13.18.zip)

game ok if disable mod_biorand\room

![Capture](https://github.com/IntelOrca/biorand/assets/120957601/0f84cbb9-627e-4f91-abdf-13c70d9c6fae)
![Capture2](https://github.com/IntelOrca/biorand/assets/120957601/3eb9c097-73a6-4691-9831-2a513250cde7)
![Capture3](https://github.com/IntelOrca/biorand/assets/120957601/c386e78c-8a82-482c-8cf1-b7291c47e560)

**Comment by IntelOrca** [comment]
@otamega72 you are playing an old version. This should be fixed in 3.1.1.
