### ISSUE TITLE
RE1 Game Crash

### ISSUE THREAD

**Issue by Junoh315** [IntelOrca/biorand#539]
### Version

3.1.0 (ef39513)

### Seed

R710-0000-XJZH20ZZ4Z000NN90W020ZZZZZZZZZZZZZZZZYZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Rebecca

### What happened?

Game crashed in the "L Passage" on east side of the first floor of the mansion after the hunters spawned.  The game froze for a couple of seconds after shooting a zombie in there before the crash.

No saves were made but the playthrough was recorded.  Incident occurred at 1:41:53.

https://youtu.be/NbhQ2kSTRE4

**Comment by IntelOrca** [comment]
This might be fixed in latest version
