### ISSUE TITLE
RE 3, Sheva model is glitched in HD

### ISSUE THREAD

**Issue by Atreid3s** [IntelOrca/biorand#541]
### Version

3.1.1

### Seed

R730-VRB5-XX6666AZ9YH10AJ9KR92WZZZZZZZZZZZZZP2YZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Sheva

### What happened?

Hi there.

Sheva lower body is missing. I tried in different seeds but it still happens. Cheers!

![Sin título](https://github.com/IntelOrca/biorand/assets/121364437/b1e9480f-eda4-4103-bea8-3d9e3c4274d8)

**Comment by IntelOrca** [comment]
It will be an issue with the PLD file for that character. It is possibly going over some game limits which cause various corruption to occur.
