### ISSUE TITLE
[3.1.1] RE1 No Armor Key

### ISSUE THREAD

**Issue by silberberg44** [IntelOrca/biorand#542]
### Version

3.1.1 (1e8850a)

### Seed

R710-4BW0-XQHH40MZ9Y000NNZZZZZZZZZZZZZZZZZZZGZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Richard

### What happened?

The seed log says ARMOR KEY x6 is in room 113:1, but I don't find any key aside from SMALL KEY.

**Comment by IntelOrca** [comment]
The key is in the bath.
