### ISSUE TITLE
[3.1.1] RE 1, Missing Crank

### ISSUE THREAD

**Issue by silberberg44** [IntelOrca/biorand#543]
### Version

3.1.1 (1e8850a)

### Seed

R710-XZP1-XQHH40MZ9Y000NNZZZZZZZZZZZZZZZZZZZGZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Barry

### What happened?

After leaving the Mansion I fail to obtain the SQUARE CRANK (which, for some reason, is located in room 300:9), essencially causing a softlock from the rest of the game.

**Comment by IntelOrca** [comment]
The crank is the 2nd herb in the corner in 300 (First House Out)
