### ISSUE TITLE
RE3 Randomize NPCs does not work

### ISSUE THREAD

**Issue by Light-Light-00** [IntelOrca/biorand#545]
When i try to generate a seed for RE3 with Randomize NPCs ON, then i keep getting this error (yes i change the seed and i keep getting it)
![image_2023-08-11_143159598](https://github.com/IntelOrca/biorand/assets/141843903/c1d476d6-b56f-4034-81c7-16182eb85903)

**Comment by IntelOrca** [comment]
Can you please send me the log file

**Comment by RikumaXZ** [comment]
I had the same problem, I decided to change the version of the game.

**Comment by Light-Light-00** [comment]
> Can you please send me the log file

is it the log file ?
[log_pl0.txt](https://github.com/IntelOrca/biorand/files/12327297/log_pl0.txt)

**Comment by IntelOrca** [comment]
Duplicate of #325 and now fixed
