### ISSUE TITLE
Game crashes when trying to access the first door

### ISSUE THREAD

**Issue by guiprd** [IntelOrca/biorand#551]
### Version

3.1.1 (1e8850a)

### Seed

R730-6M8H-ZNHH0HMZCP000QJZZZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Carlos (RE3)

### What happened?

The game crashes when trying to access the first door (101 to 501). Weapon equipped or not doesn't matter in this scenario.

**Comment by IntelOrca** [comment]
I wasn't able to reproduce this:
![image](https://github.com/IntelOrca/biorand/assets/1482259/4306d246-a6d2-4e43-9d95-2c82fdd4df7c)
