### ISSUE TITLE
[3.1.1] [RE1] Unstable Seed?

### ISSUE THREAD

**Issue by silberberg44** [IntelOrca/biorand#557]
### Version

3.1.1 (1e8850a)

### Seed

R710-NGEB-ZTHH40MZ9Y000NNZZZZZZZZZZZZZZZZZZZGZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Barry

### What happened?

The seed has multiple instances of connection overlaps on a single door: opening it may lead to one room, then opening the same door from the same room it was opened may lead to a totally different room. In addition, certain rooms are "locked from the inside", which leads to an immediate softlock. 

If I were to retrace my steps by room numbers: 203 (Dining Hall 2F door) -> 202 -> 201 -> 101 -> 204 -> 206 -> 207 (going through the staircase) -> 400. In Room 400 I supposedly appear by the red door, but when I "go back" through that door, I don't arrive back at 207 staircase, but arrive at Room 404. In addition to that, when I reach Room 403 from Room 400, the door back is "locked from the other side", leading to a softlock.

**Comment by IntelOrca** [comment]
When I tried this seed, it didn't fit your description. All doors in 400 work both ways. Are you able to send me a log file?

**Comment by silberberg44** [comment]
It would seem the problem was with the game itself, as reinstalling the game helped. Now I can pass through the seed normally.
