### ISSUE TITLE
softlocked seed

### ISSUE THREAD

**Issue by Chunkbingus420** [IntelOrca/biorand#558]
### Version

3.1.1 (1e8850a)

### Seed

R720-292R-ZXHH40C58PF60BNBPF4VFZZZZZQYZVQGZZL2YQAYZZ

### Scenario

RE 2 (leon)

### Player Character

hunk

### What happened?

got through most of the seed but no diamond key or blue keycard was spawned and resulted in dead ends everyother door was locked from the other side

**Comment by IntelOrca** [comment]
What scenario were you playing, you just put `(leon)` without saying A or B.
