### ISSUE TITLE
RE3 biorand

### ISSUE THREAD

**Issue by lameche2220** [IntelOrca/biorand#560]
### Version

3.1.1 (1e8850a)

### Seed

R730-TCEV-XWHZ4HMZWYJ00QNZZWA9X1H000008E02ZZVZYXZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Chris (CV)

### What happened?

R730-TCEV-XWHZ4HMZWYJ00QNZZWA9X1H000008E02ZZVZYXZZZZ

**Comment by IntelOrca** [comment]
Please describe the issue or problem you encountered.
