### ISSUE TITLE
RE3 - Crash After Jill's Intro Dialogue

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#564]
### Version

3.1.1 (1e8850a)

### Seed

R730-WWGQ-ZNMTG3109F000GJLARLJWZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Alexia

### What happened?

Right after "This is my last escape", it does not load the intro area. 
I've attached the log.
[log_pl0.txt](https://github.com/IntelOrca/biorand/files/12501826/log_pl0.txt)

**Comment by missingno1711** [comment]
Hmmm....same settings tried a different seed. Same result
R730-A6T6-ZNMTG3109F000GJLARLJWZZZZZZZZZZZZZZZZZZZZZ

**Comment by otamega72** [comment]
your enemy skins (kevin) crashed the game. In your seed , kevin skin is em1e.*
mod_biorand\room\emd\em1e.* 

Create a new folder in mod\biorand\room\emd  ,  
move em1e.* to that folder , then run the game again.

Other enemy skins might crash the game are : 
wesker (re1r)  ,  kevin  , ashley  , billy  ,  regina  ,  sheva

Open log_pl0.txt , search keyword : skins , 
move those skins files which might crash the game to other folder.

**Comment by IntelOrca** [comment]
New version is now available, let me know if it still happens.
