### ISSUE TITLE
RE 1, Chris, random items in inventory slot 7,8

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#565]
### Version

3.1.2

### Seed

R710-APRZ-XXHH40MZ9Y860LQZZZZZZZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Lott

### What happened?

As shown in the gif I included, when I picked up the sword key off of the body, 2 of my starting items duplicated. [gif](https://i.imgur.com/fz2KnKO.gif)

**Comment by AlbertFnWesker** [comment]
Did another seed with chris and same thing happened, I opened up the debug menu and looked at the inventory and the double items are already there, just invisible until you pick up enough items. [example](https://i.imgur.com/CjEIuBo.png)

**Comment by IntelOrca** [comment]
If you play Jill first, then go back to the menu and play as Chris, does the issue still happen?
