### ISSUE TITLE
RE 1, room 10E, crash when enemy is adder

### ISSUE THREAD

**Issue by heymert8657** [IntelOrca/biorand#572]
### Version

3.1.2 (5a4a08a)

### Seed

R710-U124-ZXPG20FZ9Y000BNXVZBGFW0ZZXZZZZZZZZZZZZZQYZZZ

### Scenario

RE 1 (Jill)

### Player Character

Regina from Dino Crisis

### What happened?

as soon as I enter the bedroom in the west wing of the mansion, they game keeps crashing because it cannot find a file ["/horr/jpn"]
![Bild_2023-09-07_085036358](https://github.com/IntelOrca/biorand/assets/117825073/485c4c65-8796-4c48-8156-0429113e89bc)

And how do I upload the recent save file? Where do I find it?

**Comment by otamega72** [comment]
Go to directory [horr] , create a folder [jpn] , move following folders into [jpn] :
[data] , [effspr] , [enemy] , [item_m*] , [movie] ,[objspr] , [players] , [sound] , [stage*] , [voice] , select_b.tim

**Comment by IntelOrca** [comment]
> And how do I upload the recent save file? Where do I find it?

Under your RE 1 directory is a folder called savedata. Upload the latest file from there in a zip file.
