### ISSUE TITLE
RE1, door rando keeps breaking

### ISSUE THREAD

**Issue by AugmentedAntics** [IntelOrca/biorand#573]
### Version

3.1.2

### Seed

R710-0AQC-ZNRE00MB9P000LNBTTKR1R0ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Claire RE2

### What happened?

Above seed is just one of them, but door randos in RE1 keep breaking, as I regularly "escape" the randomized sequence and end up back in the vanilla sequence, complete with un-randomized items in resulting rooms (in this seed, I use the crests only to fall into the vanilla guardhouse sequence). It may be worth noting that I also have Classic Rebirth with the Seamless HD pack installed. RE2 and 3 never seem to have this problem after the last few versions of BioRand, despite also having Classic Rebirth and Seamless HD installed for those.

**Comment by IntelOrca** [comment]
The door that requires the crests should have taken you to the dressing room (111). It does for me. Can you send me a saved game?

**Comment by AugmentedAntics** [comment]
So, I think what may have happened is that I had a botched install, as I was having weird side effects like alternate camera angles and whatnot (like the camera on the second floor of the dining room hanging over the open middle area instead of being against the wall like it normally is). Whatever this was doing was probably confusing the door rando and sending me every which way but where I was supposed to be going. I then got rid of my installation and used the one from your site instead. Afterwards, I retried this seed to test it and now the problem seems to have been solved.

**Comment by IntelOrca** [comment]
@AugmentedAntics what you had were the director's cut angles. I am unsure what the implications of this are, it may or may not have been the cause. In the install you got from the website, the DC cameras are disabled. If you want to re-enable them, rename `_bio1dc` to `bio1dc`.
