### ISSUE TITLE
no diamond key?

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#578]
### Version

3.1.3

### Seed

R723-W4YG-XNHH60MZ9UT60JQKK3JMEZ1ZZZZZZZZZZZZZZZZGWXZZ

### Scenario

RE 2 (Claire B)

### Player Character

Alexia

### What happened?

I checked the seed log and it said the diamond key is in 20B, but i cant find it in there, unless theres a spot im missing/was unaware of.

**Comment by IntelOrca** [comment]
There are two items behind the desk:
![image](https://github.com/IntelOrca/biorand/assets/1482259/112e6b3f-a553-4396-902e-b32236e83e4c)
