### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by homesickmarcus** [IntelOrca/biorand#589]
### Version

3.1.3 (cbe02d7)

### Seed

R730-RMWK-XNHH4HMZ2YA00QK9KW92YZ1ZGZZZZZZZZZZZZZZZXZZZ

### Scenario

RE 1 (Chris)

### Player Character

Barry

### What happened?

Crashed upon opening the very first door after climbing the dumpster. Right in the beginning.

**Comment by IntelOrca** [comment]
I am unable to reproduce this
