### ISSUE TITLE
RPD Gate Crash

### ISSUE THREAD

**Issue by homesickmarcus** [IntelOrca/biorand#590]
### Version

3.1.3 (cbe02d7)

### Seed

R730-EYPK-XNHH4HMZ2YA00QK9KW92YZ1ZGZZZZZZZZZZZZZZZXZZZ

### Scenario

RE 1 (Chris)

### Player Character

Barry

### What happened?

Upon opening the gate to the RPD the game crashed

**Comment by IntelOrca** [comment]
I teleported to 10A and was able to go through the gate, dodge Nemesis and into the RPD. Do you have any more information on how to repro?
