### ISSUE TITLE
RE1 - Key Items didn't spawn in room 300

### ISSUE THREAD

**Issue by bfinz** [IntelOrca/biorand#591]
### Version

v3.1.3

### Seed

R710-KBN4-XNHH50MZ9Y3A0LJK2JJN490ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Rebecca

### What happened?

The room in question is outside before you reach the crank area to drain the water. There were several green, red, and blue herbs. They all contained the herb items they appeared to be, which I found to be extremely odd at first. I eventually got stuck and looked up the log for the seed. 

Room 300 was supposed to contain the Square Crank, Red Book, 2 batteries and "3 other items". This matches up with the 3 green, 2 red and 2 blue that spawn by default. I verified via F6 that the room I was in in 300, and via the DGML that this is where the crank I needed ended up. Seed appears soft-locked with items not spawning in this room.

**Comment by IntelOrca** [comment]
I tried this seed and the crank was in room 300. I expect there may be something wrong with your install.

**Comment by bfinz** [comment]
It was because I had the Seamless HD Project installed. Apparently it does not play nicely! I went back to vanilla and have my items, thanks for helping troubleshoot.

**Comment by IntelOrca** [comment]
@bfinz the HD pack is compatible, but make sure you disable the DC camera angles.

**Comment by bfinz** [comment]
> @bfinz the HD pack is compatible, but make sure you disable the DC camera angles.

Oh I'm not familiar with that option, what is it?

**Comment by IntelOrca** [comment]
@bfinz you will need to check the readme that came with it. You rename a folder called `bio1dc` to something else.

Alternatively the version you can download via the official website: https://biorand.net has a version guaranteed to work.
