### ISSUE TITLE
softlock in RE2 US version rando

### ISSUE THREAD

**Issue by Bizetty** [IntelOrca/biorand#592]
### Version

3.1.3 (cbe02d7)

### Seed

R720-GC5F-ZXHB00MZ9YR60HJRN3U40Z1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire B)

### Player Character

Alexia

### What happened?

Rando places item 'mainfuse' in room 202.15. Either I cannot find item or postion does not exsist. Playing Arrange mode

**Comment by IntelOrca** [comment]
You shouldn't play arrange mode, that is not part of biorand.

**Comment by Bizetty** [comment]
There may be some confusion on my end. Biorand 3.1.1 [Feature] RE 2, add US/EUR item placements. I assumed that ment Arrange mode was now playable. Its like 80%  playable lol, my mistake. Looking foward to the next update!

**Comment by IntelOrca** [comment]
No problem, sorry for the confusion.
