### ISSUE TITLE
BioRand RE1 Crashes and Softlock

### ISSUE THREAD

**Issue by envelas** [IntelOrca/biorand#596]
### Version

3.1.3 (cbe02d7)

### Seed

R710-3T1L-ZEHH40WW9Y000QJZZZZZZZ1QZVAUZZZZZZZZY4YGVZZZ

### Scenario

RE 1 (Chris)

### Player Character

Chris (RE1)

### What happened?

Back to back crashes. First time was after entering the underground crank puzzle room where you get a doom book. I entered from the guardhouse bathroom door in the room with the red books next to plant 42. There were two Black Tiger's in the underground crank puzzle room and upon entering, I attempted to turn around and exit through the door when Chris clipped through the scene and walked out of field of view, then it crashed moments later. No saves were made.
After firing up a new game with the same seed, I made it to the bloody hallway before Forest / Bazooka room, entering from same door as vanilla. Two Cerberus were in room, I proceeded to knife them and succesfully killed one. I was finishing off the other one, knife slash had sent him back to near the examinable knife stain on the floor. I ran up to dog, aimed down with knife, mashed attack but instead of slashing, Chris bent to examine the blood followed by the examination message at which point Cerberus got an attack in. After taking damage the game began to slow followed by chopped frames then a crash. No saves were made. 
Also a softlock in one path where a door took me to the elevator leading to the underground, the final part of the underground with the boulder and the spinning crank room that leads to the crank puzzle room with doom book. Two chimeras active in the area, after activating and avoiding the boulder no key items were found in the area. Door leading into underground pass was locked from other side. When I attempted to go back I realized the path had changed. Originally it was Mansion 2F east hallway (Zombies) -> Library (Two Black Tigers, Red Herb instead of Botany Book) -> Underground Final Boulder area (Two Chimeras, Helmet key behind boulder). When I made it back to library, door to Mansion 2F East hallway took me to underground pass saveroom (one Adder). Going back through this door leads me back to the library and therefore an inescapable segment.

[Chris_01_2023-09-14 22^09.12.zip](https://github.com/IntelOrca/biorand/files/12616040/Chris_01_2023-09-14.22.09.12.zip)

**Comment by IntelOrca** [comment]
I am having trouble understanding what I need to do to reproduce your issue from the saved game. It might be because the seed was generated differently. Are you able to give precise instructions on what to do from the saved game, or provide a debug save closer to where the issue is. You can make a debug save at any time using the debug menu.

Alternatively record a video showing the issue. Thanks.

**Comment by lycanxlotus** [comment]
This is the only post I've been able to find on the entire Internet that has spoken about the issue where some doors can spontaneously change their path. Before you know it, you're soft locked into the same three rooms because the only path available just starts to loop in on itself. Whhhyyyy? I want to play through this so bad, but everytime I do it always ends due to one door suddenly not going where I expected, and the way back is not the way i came from. Someone pls help

**Comment by IntelOrca** [comment]
@lycanxlotus please attach a debug saved game and seed just before the door that doesn't go the way you expect.

**Comment by envelas** [comment]
@IntelOrca 

To reproduce the 1st crash I described:
Save should load up in [40A Room 003], enter the bathroom door (should lead to [306 Item Passage]) and there should be two Black Tigers in this room. Turn around to face the door you just entered and run forward. Keep running and Chris will clip through the scene disappearing altogether, followed by a crash.
[Chris_255_2023-09-16 17^39.44.zip](https://github.com/IntelOrca/biorand/files/12641825/Chris_255_2023-09-16.17.39.44.zip)


To reproduce the 2nd crash I described: 
Save should load up in [50C Front of Elevator], enter door directly behind Chris (should lead to [211 Terrace Passage]). There should be one Cerberus in here, attempt to examine the bloodstain on the ground and crash will occur just as Chris gets on one knee.
[Chris_255_2023-09-16 17^20.16.zip](https://github.com/IntelOrca/biorand/files/12641785/Chris_255_2023-09-16.17.20.16.zip)


To reproduce the softlock:
Save should load up in [204 C Passage], enter the door right by Chris leading to [206 Doll Room]. There should be two Black Tigers in this room, turn around and enter the door you just came in from to end up in [30E Save Room] with one Adder in here. Exit the save room to end up back in [206 Doll Room] with the two Black Tigers. Enter the other door in the Doll Room to end up exiting off the lift into [30F Crank Passage] with two Chimeras. If you go up the lift you just came from, you will be back in the Doll Room. Back in [30F Crank Passage] if you try to open the door in this room it will be locked from the other side. As you can see, the player is stuck in this 3 room section with no way out besides using the debug menu.
[Chris_255_2023-09-16 18^14.46.zip](https://github.com/IntelOrca/biorand/files/12641857/Chris_255_2023-09-16.18.14.46.zip)

**Comment by envelas** [comment]
Turns out the issues were primarily being caused by the fact that I had the Director's Cut camera angles turned on, turned them off and it's basically a completely different seed. My apologies! Still good to note I guess if you ever decide to also support a DC version. 
@lycanxlotus is your game also using the DC camera angles? If so then I'm guessing that you must have the teamx HD mod installed, and in that case you most likely have a folder titled bio1dc in the root of your re1 game folder. I recommend turning off the DC camera angles when using BioRand. To do so, just rename the bio1dc folder to something else like bio1dc_. Hope that helps!

Sidenote, @IntelOrca thank you for all your hard work in making this amazing mod!

**Comment by IntelOrca** [comment]
@envelas thanks, I have added a warning popup now if it detects DC camera angles.

**Comment by lycanxlotus** [comment]
100% DC camera angles seem to affect the mod's logic. They have to be disabled or it's softlock city. Thank you so much!
