### ISSUE TITLE
3.1.3 - RE2 Game Crash (Room 207) - Alexia magnum & Brad zombie

### ISSUE THREAD

**Issue by NawiEchi** [IntelOrca/biorand#600]
### Version

v3.1.3

### Seed

R720-MBUG-ZXYZM0W19Y760ZJZZZZZZZ1EXZNF5FVLGZYZZPYZZZZZ

### Scenario

RE 2 (Claire B)

### Player Character

Alexia

### What happened?

Game crash in room 207 when I shoot Brad (zombie) using the Magnum. No problems with other enemies

https://github.com/IntelOrca/biorand/assets/122708115/630069a5-8565-4200-b41a-f60221942a2d

**Comment by IntelOrca** [comment]
Duplicate of #426
