### ISSUE TITLE
RE 1, room 306, black tigers push player out of bounds

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#601]
### Version

3.1.3

### Seed

R710-FUCK-ZXPH40QZ4Z3CHQNV6XVM4L01J11RZZZZZZZZH2YYZZZZ

### Scenario

RE 1 (Chris)

### Player Character

regina

### What happened?

room 306 pc out of bound
[Chris_02_2023-09-19 01^41.01.zip](https://github.com/IntelOrca/biorand/files/12651825/Chris_02_2023-09-19.01.41.01.zip)

**Comment by IntelOrca** [comment]
This may no longer be a problem in dev. builds as it is limited to one black tiger regardless of difficulty. I think what is happening is that the black tigers are so big that it pushes you out the room when you enter the door.
