### ISSUE TITLE
Cannot get the Square crank to work right away.

### ISSUE THREAD

**Issue by JackDeRipper494** [IntelOrca/biorand#604]
### Version

3.1.3 (cbe02d7)

### Seed

R730-PKJ0-XXNE57KZ9PN10QQR9W4TWZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Wesker CV (I dont think it matters)

### What happened?

Unless I pass a certain "stage", I cant use the 'square crank' on the metal gate to get items.

**Comment by IntelOrca** [comment]
This is unfortunately a limitation of the game. No logic exists for the crank on the daytime version of that room.
