### ISSUE TITLE
crash at same spot

### ISSUE THREAD

**Issue by ghost** [IntelOrca/biorand#605]
### Version

3.1.3 (cbe02d7)

### Seed

R721-VFH9-ZXZF20ZZ9M00HGJ0NAEKAZ11440002895RWZYNZ7YVZZ

### Scenario

RE 2 (Claire A)

### Player Character

Piers

### What happened?

game crashes and closes exiting room with valve handle, claire A

**Comment by IntelOrca** [comment]
Now sure exactly which room you are referring to. Do you mean room 212 (outside alley with manhole cover) where there are giant moths?
