### ISSUE TITLE
tyrants not able to kill jill

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#606]
### Version

3.1.3

### Seed

R710-QYB9-XNFF00GZ9R6F09Q000RJZ00ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Sherry

### What happened?

So on a few occasions I was "killed" by tyrants, but it never triggered the game over screen, I was just running around dead.

**Comment by IntelOrca** [comment]
More or less same issue as #581
