### ISSUE TITLE
RE 3, room 107, crash

### ISSUE THREAD

**Issue by ghost** [IntelOrca/biorand#608]
### Version

3.1.3 (cbe02d7)

### Seed

R730-ANQP-WXGA4GQZ9Y000GJ8QXWWWZ10HWZXYTLF0ZYZUZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Jill RE3remake

### What happened?

Game crashed when entering Bar where Brad dies.

**Comment by IntelOrca** [comment]
I was unable to reproduce this
