### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by ghost** [IntelOrca/biorand#609]
### Version

3.1.3 (cbe02d7)

### Seed

R730-3FQ0-XXGA45Q79PW00GJ8QXWWWZ10HWZXYTLF0ZYZFPYXZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Jill RE3

### What happened?

Random crash

**Comment by IntelOrca** [comment]
Please describe what happened and how to reproduce the issue, ideally a debug save game just before the crash. Without this information, I cannot investigate the issue.

**Comment by gurizzy** [comment]
This was RE3 not sure why it says RE1. Game crashed shooting at nikolai skin zombie with western custom in the starting room with the truck where you meet dario.

**Comment by IntelOrca** [comment]
@gurizzy because you said **Scenario: RE 1 (Chris)**

**Comment by gurizzy** [comment]
Uh no I didn't I clicked a button on a program

**Comment by gurizzy** [comment]
Stop responding unless you intent to try to solve the problem, genius.

**Comment by IntelOrca** [comment]
The program does automatically set that particular option for you, because for RE 2 it can't know which scenario you were playing.
