### ISSUE TITLE
RE 3, room 10D, crash when playing as Regina

### ISSUE THREAD

**Issue by killerlilm** [IntelOrca/biorand#610]
### Version

3.1.3 (cbe02d7)

### Seed

R730-0G4N-ZXHHHHYZ9YN00VNRJZEVYZ1ZZZZZZZZZZZZZRKYZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Regina

### What happened?

Room: 10D Start Room
Crash Report: 
The Game Crashes upon the cutscene regarding Regina jumping out of the burning building.
I have tested this on different games because i thought it was just mine then i changed characters and its just running fine.

I retested it with another character (Dario)

**Comment by killerlilm** [comment]
Room: 105 Basement Alley

Character: Dario

Seed: same one as previous

Crash: when brad breaks down the door and runs away just as the door breaks open the game crashes

**Comment by killerlilm** [comment]
Room: Cable Car (Will get the room number after i get to it)

Character: Dario
HUNK

Seed: same one as previous

Crash: crashes after door loads up. There was supposed to be a cutscene where Jill gets her sidepack

Same Seed

Character: Wesker (RE5)

Crashes after loading a Save Game

**Comment by IntelOrca** [comment]
I was unable to reproduce your 105 and 20C crashes, but I can reproduce the Regina issues.
