### ISSUE TITLE
RE 3, swap player character can be enabled via pasting a seed

### ISSUE THREAD

**Issue by killerlilm** [IntelOrca/biorand#615]
### Version

3.1.4 (25e489a)

### Seed

R730-3WF9-XXHH4HQ59W000HLNZZZZZZZ1ZZZZZZZQNZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Random

### What happened?

The recent update it seems I either got a faulty pl00.pld or its just not there for RE3 Seed because I have tried to generate about 20 seeds so far and I'm getting the same message.
![Capture](https://github.com/IntelOrca/biorand/assets/132631083/68806242-bba6-4381-a1b8-92f3175f155b)

**Comment by killerlilm** [comment]
![norandom](https://github.com/IntelOrca/biorand/assets/132631083/8bfcea19-9071-4fe3-90c7-8d8f6122f54d)
![testing](https://github.com/IntelOrca/biorand/assets/132631083/903d588f-bf8a-470b-b606-a7463637ea80)

Further testing it seems that changing your player character is what failed to generate

**Comment by IntelOrca** [comment]
Does it still happen if you use the version of the game from https://biorand.net?

**Comment by killerlilm** [comment]
So this previous results is from grabbing the update from github and copy and replacing from the zip folder. I have first tried it on my version of RE3 (Didn't Work) and i thought it may have been i accidently deleted something while just pasting over so i erasing and started from from the zip file. Again didn't work, so i tried it on the HD version from https://biorand.net/ on both Jill becomes Random and jill becomes Krauser neither worked on the HD version (Same Result).

I currently just tried the Biorand from https://biorand.net/ on both my version and the HD version from the HD pack and still the same results the only one i havent tried yet is the middle option (Resident Evil + BioRand) so i am currently downloading it and will test it once its completed.

**Comment by killerlilm** [comment]
New Update 10/12/23 7:37PM CST
Tried a new one by default with some seeds and generated and it worked this time.
![3 1 5](https://github.com/IntelOrca/biorand/assets/132631083/2ccd5be7-6c34-44a3-917c-4a01cb7892d8)

Now why i said this time? well because afterwards i tried to update using an old seed i tried previously to see if it has that same crash as before. 

Here is the Seed Code: R730-PJFV-XXHH4HQA9Y000QNZZZZZZZ1ZZZZZZZZQNZZZZZZZZZZZ0

Now it didn't work and I also noticed where the bar for Jill becomes [Insert Character or Random] instead of being below it like in the previous picture its instead south east in a different location and the error pops up. and the code comes back the same no matter what seed I try to generate or delete the last Biorand zip file and make another one.

![new one](https://github.com/IntelOrca/biorand/assets/132631083/bbaa74f6-fedc-4829-8a50-46a01d3fa2e2)

**Comment by IntelOrca** [comment]
I think I can see the problem. If you look at the change player character box, it thinks you can only change the B character, and not the A character. Somehow you have the swap character flag enabled which doesn't apply to RE 3. This will be in the seed, but the UI is not visible for you to change it. I can fix this in the next update so that it forces the flag off.
