### ISSUE TITLE
RE 3, room 504, crash in middle of cutscene

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#619]
### Version

3.1.5

### Seed

R730-5354-XWMH4CM509YC20QNRPEV6WZ10020002001ZZZEXZYZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Billy

### What happened?

room 504 crashed if selected jump off.

[jump 01_2023-10-14 00^18.39.zip](https://github.com/IntelOrca/biorand/files/12896319/jump.01_2023-10-14.00.18.39.zip)

**Comment by IntelOrca** [comment]
This saved game crashes on vanilla as well. It may take some time to identify the issue, potentially a particular flag that breaks the game.

**Comment by otamega72** [comment]
> This saved game crashes on vanilla as well. It may take some time to identify the issue, potentially a particular flag that breaks the game.

1) press keyboard to skip the cutscene immediately (before Carlos shot the zombies) can avoid the crash.

2) Maybe changing route made 504 crashed 

I generated similar seed (R730-5354-***) (pl00 = billy , pl08 = wesker , without randomize npc , enmey skin , music )
game did not crash if the route are : 
rpd -> press office (trigger nemesis , hide ) -> restaurant -> sales office (didn't trigger nemesis in hydrant alley 2) -> cable car (trigger Mikhail's shooting zombies )->  gas station -> power station (increase elec output)  -> cable car (didn't trigger nemesis and digger ) -> cable car jump window -> skip way to chronos room ( 3 stones room ) -> active tower clock , fight nemesis -> Carlos scenario (B3->4F) -> park -> skip all the way to grave yard route -> open gate to factory-> select jump off  

Saved file which crashed the game route : 
sales office -> rpd -> power station -> restaurant -> press office -> gas station ->  cable car -> all CT route -> Carlos -> grave yard ->digger -> to factory  -> jump off -> CRASH

Will test the route which crash the game in this new seed again.

attach new save file (no crash) :
[jump_no_crash.zip](https://github.com/IntelOrca/biorand/files/12934335/jump_no_crash.zip)

**Comment by IntelOrca** [comment]
I think it is because you killed another enemy that shared the same global enemy ID as one of the zombies in the cutscene. So one didn't spawn and that crashes the game. I have now made sure those IDs are reserved and not used for random enemies.
