### ISSUE TITLE
Room 700 crash before cutscene - Claire B

### ISSUE THREAD

**Issue by sprogiman** [IntelOrca/biorand#62]
Seed: R320-CW8V-Z9UV3LK

After Destroying the Helicopter wall in "Room 10A" and entering the door which takes to "Chief Irons office", on the rando it is supposed to send the player to "Room 700" which starts with a Cutscene. But after the door animation the game hangs on a black screen and turns the game off.
The Rando is not finishable since you have to pull a lever in "Room 700" to open the gate for the train.

Edit - Version 1.3.3

**Comment by IntelOrca** [comment]
Fixed
