### ISSUE TITLE
Redownloaded

### ISSUE THREAD

**Issue by Finalflashbang** [IntelOrca/biorand#627]
### Version

3.1.6 (0f27194) this versions is actually 3.1.5

### Seed

R720-Y1BY-XXHH40M5Z9Y000QJZZZZZZZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Piers

### What happened?

I shoot the magnum once it crashes and it varies how many times I shoot the Beretta and it also crashes.

**Comment by IntelOrca** [comment]
Were you shooting brad zombies at the time?
