### ISSUE TITLE
Unplayable at a point

### ISSUE THREAD

**Issue by dontjoome** [IntelOrca/biorand#63]
Seed: R320-9WHE-V1HHHMZ

It was shortly after the Birkin fight on the tram, ended up in the save room with the elevator that would normally lead to the Annette cutscene where she'd shoot Leon.

Going down that elevator had me turn into Ada but it was the 3rd floor entrance where the plug is in RPD, but heading back to use the item box and leaving out of any door afterwards mangled the graphics and only showed Ada's character model all over the screen.

**Comment by IntelOrca** [comment]
Fixed
