### ISSUE TITLE
RE 3, room 30E, 500 crash

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#630]
### Version

3.1.6

### Seed

R730-GUGU-XWHC48W509YG20QNRPEV6WZ1M8H00900HYZZZEXZYZZZZ

### Scenario

RE 3 (Jill)

### Player Character

random (Carlos RE3R)

### What happened?

30e (CT Hall 1F 2 ) crashed 
500 (Factory 1F cutscene) crashed (jump off the bridge scenario . Game no crash if select push nemesis )

FYI : removed biorand\data\re3\pld0\ 
kevin , krauser , leon.re6 , piers , regina , sheva , all 4 wesker

[30e.500.zip](https://github.com/IntelOrca/biorand/files/13053084/30e.500.zip)

2) Is it possible to randomize 50e voice ? (m50ea020.wav)
[50e voice.zip](https://github.com/IntelOrca/biorand/files/13053386/50e.voice.zip)

**Comment by otamega72** [comment]
Double checked : 
The seed already had it own randomized m50ea020.wav , but the game used default (vanilla)  wav .

**Comment by otamega72** [comment]
Testing 50e  m50ea020.wav in vanilla re3 :
Even deleted m50ea020.wav , Carlos still can say "Yes ! " 
Look like that cannot be randomized , or did I miss something ?

**Comment by IntelOrca** [comment]
When inspecting the last cutscene in process monitor, no sound file load is attempted when Carlos speaks, so it is probably from the VB data which I can't replace.
