### ISSUE TITLE
RE3 - Can't Change Player Character (PLD error)

### ISSUE THREAD

**Issue by ShiinWindragon** [IntelOrca/biorand#633]
### Version

3.1.6

### Seed

Non-specific, happens every time I try to generate a seed with the change player character option selected

### Scenario

RE 3 (Jill)

### Player Character

Jill (Any different character)

### What happened?

Whenever I try to change the player character, I get an error that it could not find a PLD file. The error is (my personal information edited out): "Could not find file 'C:\Users\...\Desktop\RE3 Biorand\mod_biorand\DATA\PLD\pl00.pld'. Please report this seed and try another."

I can randomize everything else without issue and it works, but I've been getting this error ever since I updated my biorand version. I haven't had issue with it before so I'm a little confused as to what's happening. I tried a fresh install of both the game and biorand 3.1.6 and still get the same issue.  I did a fresh install of the game with biorand 3.1.5 and I didn't encounter this issue.

Thanks!

**Comment by IntelOrca** [comment]
Please write at least one of seeds

**Comment by ShiinWindragon** [comment]
Odd, I had issues with this all morning trying different seeds, but now I came back and it's working fine. I have no idea what happened. I guess we can consider this closed for now and if I bump into it again, I'll make sure to grab seeds for you.
