### ISSUE TITLE
Issues with Marvin's room / septic rooms

### ISSUE THREAD

**Issue by sarcasm-chasm** [IntelOrca/biorand#634]
### Version

3.16

### Seed

R720-M97V-ZNQM60E4Z9F3J0BHV8P4QEV0GVZZFGZFQGXZZYQYZZVZZ

### Scenario

RE 2 (Claire A)

### Player Character

Claire

### What happened?

Hi there,

I noticed a few issues with this seed. For context, I'm a new Biorand user and the only other mods I was using concurrently are the REbirth and Seamless HD. I first encountered a softlock when I tried to enter the septic save room (outside where you fight the G-Adult). Using a door randomizer, that room took me to the sewer scene where you get sucked into the sewer drain. I was able to play after that, but I had no way to progress since the only other door was locked. I started the seed again and chose to go down the stairs in that septic hallway, which led me back to Marvin's room, where Marvin was a G-parasite, and the game froze after the cutscene where he would normally turn into a zombie. I could hear myself being attacked, but the screen was frozen on where the closeup would have been on Marvin's face. Again, this could totally be user error on my part by having the other mods installed, but I feel like I've seen streamers use them in conjunction with limited issues.

Thanks for the help!

**Comment by IntelOrca** [comment]
You generated a seed for Leon A / Claire B, but played Claire A. Be sure to play the correct scenario you generated, otherwise the seed won't make any sense.

**Comment by sarcasm-chasm** [comment]
Ahh, figured it was my user error. Sorry for the trouble and thanks for the response! I wonder if I did something similar on my other thread.
