### ISSUE TITLE
Unexpected Error RE1 First Zombie Room

### ISSUE THREAD

**Issue by sarcasm-chasm** [IntelOrca/biorand#635]
### Version

3.1.6

### Seed

R710-ZHNA-ZNMJ80C5Z9F000LJZZZ7VGB1GZZZYGVYXZZZZYQYZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Annette

### What happened?

Similar to the last report, this time I was using the seamless HD mod, classic REbirth, and a dgvoodoo config since I have an AMD processor and was having texture issues, so this could totally be my fault. I went through the opening cutscenes after Barry and I separate for the first time. I went back to the room with the first zombie, and the game crashed with an "Unexpected Error" popup. Thank you for all your time and help!

**Comment by IntelOrca** [comment]
I am unable to reproduce this.
I am afraid this unlikely to be a biorand issue. I have heard this can happen with AMD cards.

**Comment by sarcasm-chasm** [comment]
Thanks for the effort! I appreciate the attempt to resolve.
