### ISSUE TITLE
3.1.6 RE3 crashed if using mine thrower

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#636]
### Version

3.1.6

### Seed

R730-5H1T-ZWHC48W5W9YF30QNRPEV6WZ1P90H08002YZZZEXZYZZZZ

### Scenario

RE 3 (Jill)

### Player Character

william

### What happened?

refer to #323 

Mine thrower : Certain PCs will crash.
alfred
ark
ashley
barry
ben
billy
brad*
chris , cv, re5
dario*
enrico
hunk
irons
jake
kendo , re2r
leon , re2r , re4
marvin , re2r
mikhail*
rebecca
richard
steve
william

*brad , dario , mikhail : mine thrower no problem if using debug menu to select same player

** below PCs fully crashed my game , cannot test mine thrower for them.
kevin
krauser
leon.re6
murphy
piers
sheva
wesker
wesker.cv
wesker.re1r
wesker.re5

[mt.crash.zip](https://github.com/IntelOrca/biorand/files/13066351/mt.crash.zip)

**Comment by IntelOrca** [comment]
I am not able to reproduce the crash. It looks like the same problem you have had since the beginning, your system doesn't like most of the new custom models.

**Comment by otamega72** [comment]
What is the difference between RE3 (Vanilla) data\pld\pl09.pld (Mikhail) and biorand\data\re3\pld0\mikhail\pl00.pld ?

**Comment by otamega72** [comment]
biorand...\mikhail\pl00.pld replaced by vanilla re3 pl09.pld , mine thrower worked fine in my game.

Vanilla re3 Brad and 2 Dario pld had weird action when attacked by dogs , they kneel and fall down just like dying , and then stand up again. 

I just realized biorand set Brad's profile name as " chicken" ,who did this naughty thing ?

**Comment by IntelOrca** [comment]
> I just realized biorand set Brad's profile name as " chicken" ,who did this naughty thing ?

@CaptainKashup

**Comment by otamega72** [comment]
Check rendering fix on , problem solved.
