### ISSUE TITLE
3.1.6 RE3 412 cutscene crashed

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#641]
### Version

3.1.6

### Seed

R730-NEMY-ZW8848W5W9PW20QJRPNV6WZ1110HH40H0RZZZEXZYZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill (RE3)

### What happened?

412 grave cabin cutscene crashed . 
game still crashed even disable mod_biorand\room and/or \data_a

note:
save file c.1 = didn't take the key in grave secret room （414）
save file c.2 = key been taken

[412.zip](https://github.com/IntelOrca/biorand/files/13185991/412.zip)

**Comment by IntelOrca** [comment]
Duplicate of #637
