### ISSUE TITLE
Crashing when entering the Hospital alley in the Carlos portion.

### ISSUE THREAD

**Issue by JackDeRipper494** [IntelOrca/biorand#643]
### Version

3.1.6 (0f27194)

### Seed

R730-HZ1L-XXQH57K5Z9R200QJR1WXVWZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Ada RER2

### What happened?

When I enter the Hospital alley playing as carlos, the game crashes.

**Comment by IntelOrca** [comment]
@JackDeRipper494 do you have a saved game just before the crash that you could upload?
