### ISSUE TITLE
Couldn't randomize items

### ISSUE THREAD

**Issue by Natsunokoide24** [IntelOrca/biorand#647]
### Version

3.1.6 (0f27194)

### Seed

R710-5Q1Y-ZXHH40M5Z9Y000QQZZZZZZZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Random

### What happened?

It told me it was unable to randomize items for Resident Evil 1

**Comment by Natsunokoide24** [comment]
I tried to randomize all doors, NPC, enemies, and items and it without warning or cause stated refused to randomize the items, then on a second attempt froze on "randomzing enemies endlessly" choosing seed then generate again seems to have fixed it

**Comment by IntelOrca** [comment]
Seems to be fixed in dev. builds
