### ISSUE TITLE
3.1.6 RE2 G-Adult crashed in 20e

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#649]
### Version

3.1.6

### Seed

R723-BUTT-XWCC40W589YL2HQQRPNT69T000004HJ15HWXZZZZYZZZZ

### Scenario

RE 2 (Claire B)

### Player Character

kevin

### What happened?

[20e.zip](https://github.com/IntelOrca/biorand/files/13204452/20e.zip)

**Comment by IntelOrca** [comment]
Is this the integration room? I might have already fixed this in the dev. builds.

**Comment by otamega72** [comment]
mirror room 

![re2 g crash](https://github.com/IntelOrca/biorand/assets/120957601/b98fe555-1b3f-4bf6-8379-1e70bd39681d)
