### ISSUE TITLE
RE 2, room 704, crash due to G-Adult

### ISSUE THREAD

**Issue by HaithamGaafer** [IntelOrca/biorand#660]
### Version

3.1.7 (06d5680)

### Seed

R720-YZKK-ZXRHA0N5ZCY0003N7QZBNGU9ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

William

### What happened?

In room 704, the game crashed without a reason

**Comment by IntelOrca** [comment]
Fixed
