### ISSUE TITLE
Crash after Birkin fight on train platform, Claire B

### ISSUE THREAD

**Issue by RealSovietBear** [IntelOrca/biorand#661]
### Version

3.1.7 (06d5680)

### Seed

R720-L0L0-WXHH40M5Z9Y0007JZZZZZZZ5ZZZZZZZZZZZZZZZZZXZZZ

### Scenario

RE 2 (Claire B)

### Player Character

Alexia

### What happened?

After the Birkin fight on the train platform, I jumped into the Lab hallway where you can only go through one of two doors. Opening the door crashed the game twice in a row.

[Claire B_10_2023-11-11 18^27.42.zip](https://github.com/IntelOrca/biorand/files/13326121/Claire.B_10_2023-11-11.18.27.42.zip)

**Comment by IntelOrca** [comment]
fixed
