### ISSUE TITLE
RE 2, Spider spawned when slider was set to none

### ISSUE THREAD

**Issue by HaerinEnjoyer** [IntelOrca/biorand#665]
### Version

3.1.7

### Seed

R721-TBE8-ZXML50C3Y38RK03JU2WT8P29ZZZZZZZZZZZZZA4YZZXZZ

### Scenario

RE 2 (Claire A)

### Player Character

Claire RE2R

### What happened?

I have the Spider slider set to none yet in room 302 there is a spider. I have arachnophobia so this is very problematic for me.

**Comment by IntelOrca** [comment]
Fixed in latest version
