### ISSUE TITLE
RE 2, room 612, crash due to moths

### ISSUE THREAD

**Issue by df-f** [IntelOrca/biorand#668]
### Version

3.1.7 (06d5680)

### Seed

R721-0GCH-XXZN30Z79YH20L5QZZZZZZ1ZZZZZZZZZZZZZZZZZZZZ00

### Scenario

RE 2 (Leon B)

### Player Character

Jake

### What happened?

Room 612, 6 moths, once you pass half of the room the game crashes
![Screenshot 2023-11-19 130100](https://github.com/IntelOrca/biorand/assets/68758105/da6c5caf-c02b-4ff3-9274-36345f79488e)

**Comment by df-f** [comment]
Seems like i can't upload the save file directly from here. Any other way to provide you it?

**Comment by IntelOrca** [comment]
I'll just exclude moths from this room, since that is probably the issue.
