### ISSUE TITLE
Claire laying on the floor

### ISSUE THREAD

**Issue by Res2236Dan** [IntelOrca/biorand#672]
### Version

3.1.7 (06d5680)

### Seed

R710-CW5V-XXRR4076Z9Y0007NZZZZGWZEZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Jill

### What happened?

![RESIDENT EVIL® PC 22_11_2023 14_20_51](https://github.com/IntelOrca/biorand/assets/151756153/1362b246-9d00-42d0-bb2c-537bd40f078b)
claire laying on the floor not standing weird

**Comment by IntelOrca** [comment]
This is intentional for comedic effect.
