### ISSUE TITLE
Game Crashes at startup

### ISSUE THREAD

**Issue by darkseifer67** [IntelOrca/biorand#675]
### Version

3.1.7 (06d5680)

### Seed

R710-C56V-XXHH80M5Z9YNC07L0PXV6C04ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Leon (RE6)

### What happened?

After configuring everything and starting the game once it get to the main menu that game crashes even setting to run as admin still crashes

**Comment by IntelOrca** [comment]
Does the vanilla game crash the same way?

**Comment by darkseifer67** [comment]
Yes it does the same thing

**Comment by IntelOrca** [comment]
@darkseifer67 I am afraid it is unrelated to biorand then.
