### ISSUE TITLE
RE 1, pass code door does not work in Mansion 1

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#676]
### Version

3.1.7

### Seed

R710-872L-XNHH00G7Z9YT203N9KW9K494ZZZZZZZZZZZZZUQY7UZZZ

### Scenario

RE 1 (Jill)

### Player Character

Ada

### What happened?

Due to getting the helmet key early I was able to do the yawn 2 fight early, after doing yawn 2 i was given the code for the door, when i went to the door the door told me i didnt know the code eventho i was just given the code for it.

**Comment by IntelOrca** [comment]
fixed
