### ISSUE TITLE
Resident Evil 2 Claire B, 3rd floor balcony tryant crash

### ISSUE THREAD

**Issue by HavocYourWay** [IntelOrca/biorand#683]
### Version

3.1.7 (06d5680)

### Seed

R721-3BUR-XXHH40W5Z9Y1603NZZZZZZZGK8CH88024018W60YZZZZZ

### Scenario

RE 2 (Claire B)

### Player Character

Alexia

### What happened?

Run went fine until the third floor balcony Tyrant cutscene caused the game to crash. After using gear and crank to acquire the blue key item, right before entering the library door.

**Comment by IntelOrca** [comment]
May be fixed in 3.1.8, re-open if it occurs still.
