### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by trojan12kelley** [IntelOrca/biorand#685]
### Version

3.1.7 (06d5680)

### Seed

R730-0WHW-XXHH4HM5Z9YW003JZZZZZZZ7ZZZZYZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill RE3

### What happened?

Hard crashed when approaching the door Brad runs from when being chased by zombies, entered from door nearest starting warehouse

**Comment by IntelOrca** [comment]
This is potentially fixed in 3.1.8
