### ISSUE TITLE
Leon B Scenario w/Jessica (REV1) Bugged From Onset

### ISSUE THREAD

**Issue by RPDino** [IntelOrca/biorand#690]
### Version

3.1.8 (2f583cd)

### Seed

R720-UP9U-ZXHH40X7Z9Y00H7JZZZZZ3ZZZZZZZZZZZZZZZZZZZZTZZZZZZ

### Scenario

RE 2 (Leon B)

### Player Character

Jessica (RE Revelations 1)

### What happened?

Seed starts you in Raccoon Streets B with the only door being "locked from the inside".

Thanks for all you do!

**Comment by IntelOrca** [comment]
You played the wrong scenario

**Comment by RPDino** [comment]
Seeing that now, thanks!

**Comment by RPDino** [comment]
Closing, was on the wrong scenario.
