### ISSUE TITLE
RE2 room 405 704 crashed 

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#691]
### Version

3.1.8

### Seed

R723-V318-ZXPH40N4XWY2M07N8MJ3BFAFZZZZZZZZZZZZZZZZZZPL8FVZZ

### Scenario

RE 2 (Claire B)

### Player Character

Jessica

### What happened?

[re2.405.zip](https://github.com/IntelOrca/biorand/files/13626576/re2.405.zip)

1.  Connected 114:1 to 405:1 crashed.

 Randomizing room 405 with enemy: Spider
      Created 405:0 (0x0) [SPIDER,0,0,16,0] at (-19407,0,-958)
      Created 405:1 (0x0) [SPIDER,0,0,16,0] at (-22889,0,-4513)
      Created 405:2 (0x0) [SPIDER,0,0,16,0] at (-10420,0,-1680)
      Created 405:3 (0x0) [SPIDER,0,0,16,0] at (-13899,0,-26161)
      Created 405:4 (0x0) [SPIDER,0,0,16,0] at (-15118,0,-8628)
      Created 405:5 (0x0) [SPIDER,0,0,16,0] at (-10143,0,-4327)
      Created 405:6 (0x0) [SPIDER,0,0,16,0] at (-22889,0,-4513)
      Created 405:7 (0x0) [SPIDER,0,0,16,0] at (-19407,0,-958)
      Created 405:8 (0x0) [SPIDER,0,0,16,0] at (-10420,0,-1680)
      Created 405:9 (0x0) [SPIDER,0,0,16,0] at (-15118,0,-8628)

2. 703 to 704 crashed

  Randomizing room 704 with enemy: G-Embryo
      Created 704:5 (0x8) [G EMBRYO,3,0,20,0] at (1893,0,-24995)
      Created 704:6 (0x1E) [G EMBRYO,3,0,20,0] at (-6096,0,-23251)
      Created 704:7 (0x34) [G EMBRYO,3,0,20,0] at (5623,0,-22932)
      Created 704:8 (0x4A) [G EMBRYO,3,0,20,0] at (-18730,0,-23845)
      Created 704:9 (0x60) [G EMBRYO,3,0,20,0] at (12987,0,-21753)
      Created 704:10 (0x76) [G EMBRYO,3,0,20,0] at (-11996,0,-25367)
      Created 704:11 (0x8C) [G EMBRYO,3,0,20,0] at (-11523,0,-20965)
      Created 704:12 (0xA2) [G EMBRYO,3,0,20,0] at (-11523,0,-20965)
      Created 704:13 (0xB8) [G EMBRYO,3,0,20,0] at (-6096,0,-23251)
      Created 704:14 (0xCE) [G EMBRYO,3,0,20,0] at (1893,0,-24995)
      Created 704:15 (0xE4) [G EMBRYO,3,0,20,0] at (12987,0,-21753)
      Created 704:16 (0xFA) [G EMBRYO,3,0,20,0] at (5623,0,-22932)

**Comment by IntelOrca** [comment]
I wasn't able to reproduce this, possibly because when I generate that seed, I get different enemies in those rooms.
