### ISSUE TITLE
RE 3, room 110, locked RPD causes softlock

### ISSUE THREAD

**Issue by johnnybeard42** [IntelOrca/biorand#694]
### Version

3.1.8 (2f583cd)

### Seed

R730-NQNA-ZNHH4HM5Y9Y0003NH4NKMEZ5GTZZXYWXZXQZZZZ2E13200400

### Scenario

RE 3 (Jill)

### Player Character

Nikolai (RE3)

### What happened?

I got to the police station where Nemesis attacks "Jill" and when prompted to "Enter the Police Station", I chose it and the door was locked from the inside and the game glitched by not exiting the cutscene.

**Comment by IntelOrca** [comment]
That's a new one 😅, I will prevent the RPD front door from being locked.
