### ISSUE TITLE
Hunk With Bloody Torso And No Head In CutScene With Rebecca Chambers

### ISSUE THREAD

**Issue by supreme1568js** [IntelOrca/biorand#701]
### Version

3.1.8 (2f583cd)

### Seed

R710-MP7P-ZXHHH04509Y0007JZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

rebecca chambers

### What happened?

20A study Room Hunk Has No Head And Is Bloody On Body 
![RESIDENT EVIL® PC 13_12_2023 06_13_18](https://github.com/IntelOrca/biorand/assets/123736638/e8fb76a1-15b5-4112-8e7c-9a632d87c7f5)

**Comment by IntelOrca** [comment]
I think we will go with "it's a feature" rather than bug 😅

**Comment by supreme1568js** [comment]
okay :)
