### ISSUE TITLE
Unspecified Error

### ISSUE THREAD

**Issue by joeyb666** [IntelOrca/biorand#702]
### Version

3.1.8 (2f583cd)

### Seed

R710-7314-ZNQPA0655LP00H3NPVXBKB96ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Enrico

### What happened?

I loaded the seed and sat through the first cutscene in the main hall. As soon as i entered the dining room the game crashed and i got an error pop up stating Unspecified Error

**Comment by IntelOrca** [comment]
This a common issue hit by people and has been known to be solved by using the dgvoodoo fix and increasing the VRAM for it. More information is available in the official discord channel.
