### ISSUE TITLE
RE 2, room 10C, moths crash game

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#703]
### Version

3.1.8

### Seed

R721-B0RE-ZXQ970Z5J4XWY07N8MELBFAU0100040023024RZC0YY180VZZ

### Scenario

RE 2 (Leon B)

### Player Character

mark

### What happened?

[10c.zip](https://github.com/IntelOrca/biorand/files/13662294/10c.zip)

    Randomizing room 10C with enemy: Moth
      Created 10C:0 (0x0) [GIANT MOTH,0,0,23,0] at (-7951,-3600,-10812)
      Created 10C:1 (0x0) [GIANT MOTH,0,0,23,0] at (2426,-3600,-6980)
      Created 10C:2 (0x0) [GIANT MOTH,0,0,23,0] at (-25374,-3600,-15452)
      Created 10C:3 (0x0) [GIANT MOTH,0,0,23,0] at (-21592,-3600,-15032)
      Created 10C:4 (0x0) [GIANT MOTH,0,0,23,0] at (-3554,-3600,-9534)
      Created 10C:5 (0x0) [GIANT MOTH,0,0,23,0] at (-19397,-3600,-9926)
      Created 10C:6 (0x0) [GIANT MOTH,0,0,23,0] at (-24326,-3600,-10020)
      Created 10C:7 (0x0) [GIANT MOTH,0,0,23,0] at (-17624,-3600,-16300)

**Comment by KuronekoLen** [comment]
I didn't crash in this room when I debugged my way there but the moths _were_ extremely glitchy, turning invisible and generally not staying on the level geometry or respecting the vertical coordinate.

**Comment by IntelOrca** [comment]
> I didn't crash in this room when I debugged my way there but the moths _were_ extremely glitchy, turning invisible and generally not staying on the level geometry or respecting the vertical coordinate.

Moths tend to be hit and miss with the crashes. I usually just prevent them from spawning in any rooms that get reported to have crashed due to moths.
