### ISSUE TITLE
RE 3, text 50A, text disappears

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#706]
### Version

3.1.8

### Seed

R730-140L-XNHH5077Z9Y0303N9KW9K4Z5ZZZZVZZZZVYZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Kevin

### What happened?

during "night time" when trying to enter the room that has the bus that normally birds would bust through the windows, there was a crash when trying to enter that room. also there were 2 instances of text dissapearing. 1st time it was triggered by picking up items in the news office, there but input delay i could instantly notice then soon after text started going away. also end game in the waste disposal facility the text issue happened again.

**Comment by df-f** [comment]
I had the same issue at that exact location on various seeds, and by text disappearing you mean using f6 menu?

**Comment by IntelOrca** [comment]
> and by text disappearing you mean using f6 menu?

Yes, random letters are gone
