### ISSUE TITLE
RE2 Room 404 softlock

### ISSUE THREAD

**Issue by Bizetty** [IntelOrca/biorand#707]
### Version

3.1.8 (2f583cd)

### Seed

R721-HGLB-ZXHA00M5Z9YAN00J8VWBP104ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon B)

### Player Character

Vincent

### What happened?

Room 404 cutscene fails to start resulting in the player unable to change camera angles, Player can use map to navigate to other 2 doors in T passage, but opon returning cutscene begins and player turns invisible and is unable to attack for the remainder of the game resulting in a softlock

**Comment by IntelOrca** [comment]
Please submit a saved game, otherwise I am unable to investigate this

**Comment by Bizetty** [comment]
I don't have a save, but the issue still happens if you start leon b and leave room 104 to 403. From there dev console to room 404.
