### ISSUE TITLE
RE2 Selecting Lily crashes game

### ISSUE THREAD

**Issue by Bizetty** [IntelOrca/biorand#708]
### Version

3.1.8 (2f583cd)

### Seed

R721-HGLB-ZXHA00M5Z9YAX00J8VWBP104ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Lily

### What happened?

Selecting Lily crashes the game after the begining second cutscene on this seed and other random seeds

**Comment by IntelOrca** [comment]
Unfortunately this is not enough information. The second cutscene doesn't mean a whole lot in a door rando. I need the room number and ideally a debug save just before the room with the crash occurs.

**Comment by Bizetty** [comment]
The second cutscene meaning at the start of the game after the truck crash. After the movie is skipped, the game crashes immiadately at room 100. This happens on any seed I choose with Lily

**Comment by IntelOrca** [comment]
Okay, I can't reproduce it then. It does not crash for me.
