### ISSUE TITLE
RE3 Jill as Leon instead of Brad (Claire A)

### ISSUE THREAD

**Issue by Sleestakman** [IntelOrca/biorand#709]
### Version

v3.1.7

### Seed

R721-UUK3-XTJ920L5Z9Y6U07NRZZZZZZ5XNGBZPACXJ7ZYZZZTZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Misty

### What happened?

I don't have a save (was trying to see how far I could get without saving). I was playing as Misty (Claire A) and had set Leon to spawn as Brad. Somehow, when I got to the first scripted cutscene with Leon (the one in the 2F hallway just before the library), rather than being Brad, he was RE3 Jill. Honestly don't see this as a negative at all, it was just bizarre.

**Comment by Neil-F2** [comment]
The characters you set as Leon and Claire only affects the playable characters, in the cutscenes the NPCs of Leon and Claire will be a random character and not the ones you set, in Leon B in very likely that you will not encounter Misty as Claire in the same cutscene

**Comment by Sleestakman** [comment]
Oh! Okay. Misunderstanding of how the mods works, then. Beautiful mod, by the way. It's great fun.
________________________________
