### ISSUE TITLE
RE2  Rodrigo cannot knife

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#710]
### Version

3.1.8

### Seed

R721-B0RE-TWQ970Z5J4X7X0750040000U0100040023024RZC0YY180VZZ

### Scenario

RE 2 (Leon B)

### Player Character

 Rodrigo

### What happened?

[rodrigo.zip](https://github.com/IntelOrca/biorand/files/13691112/rodrigo.zip)

1.  Rodrigo cannot knife
2.  I can't find these items , please enlight me :  
      a. Marvin office  :  202:12 [HANDGUNAMMO x15] with 202:12 [ACIDROUNDS x2]
      b. RPD front yard :  103:31 [HANDGUNAMMO x30] with 103:31 [SMGAMMO x7]

**Comment by IntelOrca** [comment]
2a) there are two items behind the desk
2b) in the plant pot next to the steps, right of the RPD

**Comment by IntelOrca** [comment]
The knife works for me. Was this perhaps caused by #548, does unequipping and equipping the knife fix it?

**Comment by otamega72** [comment]
> The knife works for me. Was this perhaps caused by #548, does unequipping and equipping the knife fix it?

yes , problem solved.

2. marvin office items can be found : 
[HERBG x1] with 202:18 [SHOTGUN x5]
[MEMOTOLEON x1] with 202:16 [INKRIBBON x2]
[HERBG x1] with 202:7 [SPARKSHOTAMMO x77]
(MANHOLEOPENER x1) in 202:15
(FILMD x1) in 202:4

still cannot find :
[HANDGUNAMMO x15] with 202:12 [ACIDROUNDS x2]

![201 1](https://github.com/IntelOrca/biorand/assets/120957601/230eafac-b5f0-4fc4-948a-f9039bf0fd82)
![202 2a](https://github.com/IntelOrca/biorand/assets/120957601/1bff65a9-b089-44d4-9aed-5e6e839bb23b)
![202 3](https://github.com/IntelOrca/biorand/assets/120957601/70144b91-81cc-495d-9f78-f5e6ec8f507b)
![202 4](https://github.com/IntelOrca/biorand/assets/120957601/4c4446ed-2c25-4333-bb13-f8a6442a9f8e)
![202 5a](https://github.com/IntelOrca/biorand/assets/120957601/6d679dff-b34a-4bfe-9c07-f1181158aaba)
![202 6a](https://github.com/IntelOrca/biorand/assets/120957601/6b37b2c6-2327-4223-9dfd-12038fa0af08)
![202 7](https://github.com/IntelOrca/biorand/assets/120957601/b5754fea-6102-4933-93c2-9422c347f142)
![202 8](https://github.com/IntelOrca/biorand/assets/120957601/e071b884-8339-4d8a-99d3-0aa1b85bf294)
![202 9a](https://github.com/IntelOrca/biorand/assets/120957601/8c5763b2-1e72-4da1-9e26-d4d9103f7fe4)

**Comment by otamega72** [comment]
RPD front yard : 
found :
103:5   [HERBG x1] with 103:5 [FLAMEROUNDS x7] 

can't find : 
103:31 [HANDGUNAMMO x30] with 103:31 [SMGAMMO x7]

![103 1a](https://github.com/IntelOrca/biorand/assets/120957601/681a91db-2af9-4eb4-9433-afbfa2dd36f3)

**Comment by IntelOrca** [comment]
Oh 103:31 is the special key, you won't be able to pick that up. It won't ever be an important item.
202:12, did you try the locker behind where Marvin sits when you first meet him?

**Comment by otamega72** [comment]
>  202:12, did you try the locker behind where Marvin sits when you first meet him?

I did , but nothing found 
![202 locker](https://github.com/IntelOrca/biorand/assets/120957601/c969e2a1-31a5-4061-9435-e83a5f9a7be2)


more items not found in room 410 :
[FAIDSPRAY x1] with 410:6 [MAGNUMAMMO x8]
[INKRIBBON x3] with 410:4 [SHOTGUNAMMO x25]

found : 
[INKRIBBON x3] with 410:7 [HANDGUNAMMO x40]

![410a](https://github.com/IntelOrca/biorand/assets/120957601/bd9cc6be-ee0e-488d-94cd-1a7d4d62b1c1)

**Comment by IntelOrca** [comment]
Okay I am not sure about 202:12, but it will never be an important item.
I am aware of the items not found in 410, again they will never be important items.
