### ISSUE TITLE
RE 2, room 309, crash due to enemies

### ISSUE THREAD

**Issue by JSmonsterr** [IntelOrca/biorand#711]
### Version

3.1.8 (2f583cd)

### Seed

R721-V656-XXHH40M5Z9Y0007JZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Regina (dino Crisis)

### What happened?

After Carlos (Chief irons) died to the G-virus monster he birthed, I took a trip the ladder and the game crashed. This is right before the g-virus monster fight before you loose Sherry in the sewers.  No error code provided and does it on repeat tries.

**Comment by JSmonsterr** [comment]
Is this fixed in an upcoming patch?  Is Claire A just bugged or is there a setting I need to change?  I've had the majority of these runs die on 3 different computers.

**Comment by IntelOrca** [comment]
> If there is anything I can do to help with backend testing, let me know as I would love to play this more often on stream.

@JSmonsterr Sure, just keep testing the latest dev. builds and report any issues with a debug save as close to the issue as possible. Thanks!
