### ISSUE TITLE
RE 2, enemy crash due to memory extension

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#712]
### Version

3.1.8

### Seed

R720-3A18-XNHH4077Z9YH503NKMW949K4CEEXNYYZZVZKQZZZZZ7H0HTZZ

### Scenario

RE 2 (Leon A)

### Player Character

birkin(G1)

### What happened?

I dont know if im supposed to report on dev builds, i downloaded the latest build and selected g1 birkin. in the very first room i could hear a g adult then the game crashed.

**Comment by IntelOrca** [comment]
Please specify the build ID, otherwise I can't track which version you are using.

**Comment by AlbertFnWesker** [comment]
[screenshot](https://i.imgur.com/0rfAUIW.png)

**Comment by IntelOrca** [comment]
Clicking "report issue with this seed" in biorand fills in it automatically.
