### ISSUE TITLE
Cannot find part of the path when generating seed for RE1 and RE3

### ISSUE THREAD

**Issue by Bunkeredelf5713** [IntelOrca/biorand#713]
### Version

3.1.8 (2f583cd)

### Seed

R710-Y7XF-XXHH40M5Z9Y0007JZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Chris

### What happened?

Could not find a part of the path

**Comment by Bunkeredelf5713** [comment]
This happens on any seed that I try on both games. RE2 works fine generating new seeds

**Comment by IntelOrca** [comment]
I need more information, screenshots, logs, etc.
