### ISSUE TITLE
Biorand re2 crash report

### ISSUE THREAD

**Issue by 404scamnotfound** [IntelOrca/biorand#717]
### Version

3.1.8 (2f583cd)

### Seed

R720-VC2Z-ZXQQA0N5K9Y0007JZZZRZZZ7ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

carlos re3r

### What happened?

when leaving the rpd car park after pushing the van, the next room containing moths causes the game to crash after a few seconds.

**Comment by IntelOrca** [comment]
I think moth crashes are fixed in dev. builds now
