### ISSUE TITLE
biorand crashing when putting path to Resident Evil folder

### ISSUE THREAD

**Issue by Akahama-Patryk** [IntelOrca/biorand#72]
When I put the path in biorand to Resident Evil 2 Sourcenext exe it freeze and after few seconds it crashed. When I try to do the same but for Resident Evil 1 then it works fine. I also tried reinstall the game and with/without 1.10 patch and with/without rebirth dll.
My path to RE2 is: C:\Program Files (x86)\CAPCOM\BIOHAZARD 2 PC\bio2.exe
My path to RE1 is: C:\Program Files (x86)\BIOHAZARD\Biohazard.exe
Before version 2.0.1 and 2.0 biorand worked perfectly,

**Comment by IntelOrca** [comment]
How did it crash? Was it possible to wait a bit longer for it to process the directory?

**Comment by Akahama-Patryk** [comment]
![image](https://user-images.githubusercontent.com/46816365/208272369-2b4e2254-a4ea-4c8a-9254-4207a1a04fb1.png)
Like in the image I choose bio2.exe file and when I confirm it it freezes a bit and then it closes the app. No error and no new files in directory.

**Comment by IntelOrca** [comment]
Can you try editing `%AppData%\biorand\settings.json`:

And change the value of `gamePath2` to your RE2 path. This will bypass the settings panel, but can you tell me if you can still generate a rando for RE2?

**Comment by Akahama-Patryk** [comment]
I have edited but didn't gave any effect. Application gives an error about path and when I check the settings.json it has changed my changes back to null. I even tried edit again and put the settings,json in Read-only but nothing changed.

**Comment by Akahama-Patryk** [comment]
Ok, I found the solution. Based on putting RE1 into biorand (which works for me) I found out that the path written in .json file is written differently. So I tried again and put the path to RE2 like to RE1 in the settings.json. 
![image](https://user-images.githubusercontent.com/46816365/208274470-8e8f478e-e953-4342-8506-e9aa5dd5ecad.png)
It worked but I got a new issue when I generate the seed.
![image](https://user-images.githubusercontent.com/46816365/208274578-44cc2dd5-17ce-4fc0-a714-560d7b40c9a7.png)

**Comment by IntelOrca** [comment]
What is in the data folder of your RE2 install? I am not sure why that exists if the pl0 and pl1 folders are in the root.

**Comment by Akahama-Patryk** [comment]
Before I pasted all Biohazard 2 game folders the data folder was from the biorand zip file that I downloaded directly from your github.

**Comment by IntelOrca** [comment]
> Before I pasted all Biohazard 2 game folders the data folder was from the biorand zip file that I downloaded directly from your github.

Oh please don't mix biorand with your game installs. Keep them well separate. Delete your data directory in the RE2 install.

**Comment by Akahama-Patryk** [comment]
> 

I understand that I shouldn't do that but in my situation that's the solution if I want biorand to work correctly. The weird is that app wants the game folders and the folders with characters/music from another RE's which was together with the Rando files.
![image](https://user-images.githubusercontent.com/46816365/208276289-c08b1d26-0eb8-4b63-9e9a-aa04c678d968.png)

**Comment by IntelOrca** [comment]
It doesn't you just extract biorand to anywhere else like your desktop. You don't need to put the biorand files in your RE2 install directory. To fix this, you will need to remove that data directory, or revert the RE2 install back to its original state.

**Comment by Akahama-Patryk** [comment]
> 

So I did like you have written and you are right. Whole issue from the beginning was because I put biorand in game directory when I was not supposed to do that. I'm sorry that I wasted your precious time on this stupid mistake and I'm thankful for helping me with this problem :)

**Comment by IntelOrca** [comment]
@Akahama-Patryk no problem, I can try to add more checks in the program to say what the problem is. It should certainly not crash, so I need to fix that.

**Comment by IntelOrca** [comment]
I now catch exceptions to avoid crash. It also ignores any data directory not containing RDTs which might help.
