### ISSUE TITLE
Handgun didn't hit anything

### ISSUE THREAD

**Issue by Harveece** [IntelOrca/biorand#720]
### Version

3.1.8 (2f583cd)

### Seed

R710-8QX8-ZNHH40M5Y9YK0H3N9KMUP494GZZQY7VVEZZZZZZ2EJ7HZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Leon

### What happened?

The pistol would fire normally, but would not hit zombies or dogs.

**Comment by KuronekoLen** [comment]
Does it hit normally if you aim down? Certain characters need some coordinates adjusted to make guns work.

**Comment by Harveece** [comment]
I apologize I just now saw this, I will re-attempt and let you know

**Comment by IntelOrca** [comment]
Combining all aim related issues to #140
