### ISSUE TITLE
3.1.8 beta RE2 some bugs

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#722]
### Version

3.1.8 beta 0422f52

### Seed

R720-B0RE-ZXQ970Z5J4XHM07X84YU69AU0100H1C1100000ZC0YPJ82ZZZ

### Scenario

RE 2 (Leon A)

### Player Character

ethan

### What happened?

[save.zip](https://github.com/IntelOrca/biorand/files/13753199/save.zip)

1. room 118 , enemy open door , camera locked.
![camera](https://github.com/IntelOrca/biorand/assets/120957601/4b88f915-48df-4270-b60e-f5526ab623cf)

2. room 615 , door won't open
![615 door closed](https://github.com/IntelOrca/biorand/assets/120957601/223eac23-e787-4a3e-988e-ff5ff057b595)

3. room 209 , enemies keep open door , dead spiders won't shrink and block the way.
![209 dead spidar block](https://github.com/IntelOrca/biorand/assets/120957601/b5b2a9f9-372e-4ce9-b21c-298c5fc12a2e)

4. 200 to 60b crashed . first time enter no problem , (may be fix  in 962bc1b ? )
![60b](https://github.com/IntelOrca/biorand/assets/120957601/287add0f-e696-496d-95b7-4d75aedd230a)

**Comment by IntelOrca** [comment]
Please put the exact build id you are using. If you click report issue with this seed link in biorand. It fills in most of the fields for you.

**Comment by IntelOrca** [comment]
* [ ] 1. room 118 , enemy open door , camera locked.
* [ ] 2. room 615 , door won't open
* [x] 3. room 209 , enemies keep open door , dead spiders won't shrink and block the way.
* [x] 4. 200 to 60b crashed . first time enter no problem

**Comment by IntelOrca** [comment]
1. is a a general issue with random cutscenes
