### ISSUE TITLE
RE2 Crash (Plus Minor Bugs)

### ISSUE THREAD

**Issue by STARSMember930** [IntelOrca/biorand#724]
### Version

3.1.8 (2f583cd)

### Seed

R720-R7EQ-XX9920M6Z9YQHH7JZZZZZQWEZZZZZZZZZZZZZZZZZZZJQZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Claire RE2

### What happened?

When playing as Claire RE2 in Leon A, when you enter area 402 (the first Sewer room after the boss battle through the large door, the one before the save space) you encounter a room full of moths. Ada has become Wesker. If you run towards Cut 2 against the back wall/bars, the game crashes out. I tested twice without killing any moths and the crash happened both times. If you clear some of the moths, the crash doesn't happen. I'm guessing there are too many enemies/characters rendering and that is what causes the crash? I've attached a save file right after entering that room so you can see it. 

[Leon A_02_2023-12-22 23^04.08.zip](https://github.com/IntelOrca/biorand/files/13757976/Leon.A_02_2023-12-22.23.04.08.zip)

Additional minor/not game breaking bugs to note with this seed:
1. I believe this is known but when playing as Claire in Leon (character swap) her ponytail is missing.
2. When you trigger the scene where (in the non-modded) Leon gives Ada a boost to enter the duct and then you take control of her for the first time, the chosen character changes from Claire to Steve (with voice lines). After you regain control of your character, the skin is back to Claire (I have observed this in other seeds so I think this might be a known thing).
4. After the above interaction and section, Claire's personal item goes from the regular Magnum to the G-virus. 
*Note my save above doesn't show number 3 above because I door-skipped around that to send you the file.

**Comment by IntelOrca** [comment]
Moth crashes may now be fixed in dev. builds
