### ISSUE TITLE
Game crashes when going down the ladder to fight G Adult

### ISSUE THREAD

**Issue by AuthenticSky** [IntelOrca/biorand#726]
### Version

3.1.8 (2f583cd)

### Seed

R721-R14E-TWZC00G6Z3Z9U02H80W0K004ZZZZZZZZZZZZZZZXZZ0U00XZZ

### Scenario

RE 2 (Claire A)

### Player Character

Jill (RE3R)

### What happened?

Game consistently crashes while going down the ladder to fight G Adult in the Sewer

**Comment by IntelOrca** [comment]
Duplicate of  #711
