### ISSUE TITLE
3.1.8 beta re2 bugs 2

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#727]
### Version

3.1.8  (0422f52)

### Seed

R720-B0RE-ZXQ970Z5J4XHM07X84YU69AU0100H1C1100000ZC0YPJ82ZZZ

### Scenario

RE 2 (Claire B)

### Player Character

eveline

### What happened?

1. room 111 unstop spin crank cut scene soft lock 
[log_pl1.txt](https://github.com/IntelOrca/biorand/files/13758596/log_pl1.txt)
[111 Claire B_00_2023-12-23 14^43.35.zip](https://github.com/IntelOrca/biorand/files/13758598/111.Claire.B_00_2023-12-23.14.43.35.zip)

![111](https://github.com/IntelOrca/biorand/assets/120957601/b9667f09-e77e-4987-a68a-d26ff9f90292)

2. room 213 power supply won't work . cannot access red card  (debug jump to room 211 , check weapon storage door light) 
please refer : 
 https://github.com/IntelOrca/biorand/issues/722#issuecomment-1867804451

**Comment by IntelOrca** [comment]
1. Probably same issue and might now be fixed
