### ISSUE TITLE
RE2 Boiler room interactions

### ISSUE THREAD

**Issue by MsieurDooM** [IntelOrca/biorand#728]
### Version

3.1.8 (962bc1b)

### Seed

R720-AVEL-XXHH10M5Z1Y0007TZZZXZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

mikhail

### What happened?

In room 213 (boiler room), i can pick up the plant but can't interact with the generator or pick up the map. I'm using random events and i have wesker (RE1) following me (but shown as mikhail too in the inventory)

**Comment by IntelOrca** [comment]
Closing as SCE task changes happened since this build. Re-open if it still occurs.
