### ISSUE TITLE
Room 407 unable to interact with Medals pannel

### ISSUE THREAD

**Issue by ViniciusTsukune** [IntelOrca/biorand#729]
### Version

3.1.8 (962bc1b)

### Seed

R720-KWG7-ZXHH40W6Z9Y2007TUPXUYZ7ZZZZZZZZZZZZZZZZZZZGZQZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Andy

### What happened?

Unable to interact with the Wolf/ Eagle medals pannel in Room 407, the message for interacting with the pannel doesnt appear and using the  items doesnt give any error but the animation doesnt play either, double checked to see if the hitbox was moved a bit further away somehow but no success.

**Comment by IntelOrca** [comment]
Closing as SCE task changes happened since this build. Re-open if it still occurs.
