### ISSUE TITLE
reporting seed

### ISSUE THREAD

**Issue by scooby1123** [IntelOrca/biorand#73]
Seed: R410-VB21-V1PCURYL100

**Comment by IntelOrca** [comment]
Can you tell me what the problem was?

**Comment by scooby1123** [comment]
Hey there so in the re1 door rando killing a chimera anywhere insta crashes the game saddly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IntelOrca** [comment]
Thanks, I will merge this issue with #70

**Comment by scooby1123** [comment]
Also I wanted to mention that the dbl door in the 1st zombie hall crashes the game sometimes to when opened

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IntelOrca** [comment]
Thanks, that has been reported too:  #71
