### ISSUE TITLE
Corridor beyond the chief's office Moss giant bug

### ISSUE THREAD

**Issue by TronPolan** [IntelOrca/biorand#731]
### Version

ver 3.1.8 (2f583cd)

### Seed

R721-L1UU-ZXHH4045N4Z0007JE4PP2KYAZZZZZZZZZZZZZZZZZZHB7LVZZ

### Scenario

RE 2 (Leon B)

### Player Character

Barry(RE1)

### What happened?

The game crashed right after I shot a sulfuric acid bomb at the Moth Giant in the hallway beyond the chief's office (the room where the Tyrant appears in vanilla Leon B).

I always have fun playing it. thank you.

**Comment by IntelOrca** [comment]
Moth crashes are probably fixed now
