### ISSUE TITLE
RE 2, room 202, crash when partner is in room

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#732]
### Version

3.1.8 (5468ae8)

### Seed

R720-2024-ZXQ970V5LWW3P07X84YU69AU2100HJC1108000Z00HP19AZZZ

### Scenario

RE 2 (Claire B)

### Player Character

jessica

### What happened?

[202-112.zip](https://github.com/IntelOrca/biorand/files/13769367/202-112.zip)

1. 112 library crashed ( gorillas open door  )
![library crash](https://github.com/IntelOrca/biorand/assets/120957601/acfba350-d72e-4a98-8a8e-16cbb845229a)

2. 202 marvin room , running zombies bite crashed (zombie jake)
![re2 runing zom crash](https://github.com/IntelOrca/biorand/assets/120957601/92316ef3-db30-4239-abe1-62103e9cfc98)

3. zombie jake behave weird when dead (running , standing dead ,  running pose dead )
![re2 runing zom 2](https://github.com/IntelOrca/biorand/assets/120957601/c656f8be-f43f-4e06-91e9-24c94b33162d)
![re2 runing zom](https://github.com/IntelOrca/biorand/assets/120957601/8380107a-996e-4209-9673-68115d7041a2)

4. how to help the npc ? what ever you choose , npc just run away.
![help](https://github.com/IntelOrca/biorand/assets/120957601/b7ba25f1-7f68-464d-8319-d74008950188)

**Comment by IntelOrca** [comment]
I wasn't able to repro. the gorilla crash
