### ISSUE TITLE
Bullets not hitting the target

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#733]
### Version

3.1.8 (133fb8e)

### Seed

R721-5XWN-XNHH4077Z9Y0P03X9KW9K8A6GENCNUXNYCVV6FZZZZ4H8KZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Jessica from Revelations 1

### What happened?

So I was playing as her and it was real messy trying to actually shoot enemies. aiming down depending on the gun wasnt working, also aiming straight forward wasnt working either against final birkin boss fight, was using the custom magnum and the bullets just werent connecting.

**Comment by IntelOrca** [comment]
Combining all aim related issues to #140
