### ISSUE TITLE
3.1.8 beta RE2 If Partner Dies, So Do You?

### ISSUE THREAD

**Issue by missingno1711** [IntelOrca/biorand#735]
### Version

3.1.8 (b23b334)

### Seed

R720-ZJ0H-ZXFAB0P7Z9C0007TVKACL4BZLNZ65ZEGWY17PXZG6YWQ9FZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Kevin

### What happened?

Reached room 20C, took a few steps, and went to "You Died" screen. I believe Ivy's were in the room with Wesker being the partner. He was in Danger status. 

I was trying to get a screenshot of this. So I saved in the room before it happens and reloaded. Now Wesker doesn't die. Strange.
![image](https://github.com/IntelOrca/biorand/assets/123828971/c313b2f4-0ca7-4beb-8fdf-f3254675e5c2)

**Comment by IntelOrca** [comment]
This is expected
