### ISSUE TITLE
Crash on meeting G-Baby

### ISSUE THREAD

**Issue by CalAnon** [IntelOrca/biorand#740]
### Version

3.1.8 (133fb8e)

### Seed

R721-YQ4B-XXRA00Q6Z2Y7E17X8HW8210CKCV052C9FLA3B4YNQX1E0KZZZ

### Scenario

RE 2 (Claire)

### Player Character

Sheva as Claire

### What happened?

Immediately after seeing Piers with his "face-shirt," going to fight G-Baby results in a crash. I have no idea if this data is relevant, but I included the crash pop-up.
![Piers Face Crash](https://github.com/IntelOrca/biorand/assets/155108879/62bf5eb3-75e1-4f32-842b-744ba9c3f82f)

**Comment by IntelOrca** [comment]
Please post a saved game

**Comment by CalAnon** [comment]
I would, but I deleted all of them after the crash. I tend to keep my Save folder tidy. I'll remember to preserve my save files from now on.

**Comment by IntelOrca** [comment]
I think this is fixed in latest version
