### ISSUE TITLE
the Seed cannot be generated

### ISSUE THREAD

**Issue by TheSeriusGui** [IntelOrca/biorand#741]
### Version

3.1.8 (4915e72)

### Seed

R721-ZPMA-ZNHH40N699Y0007ERZZZZZZ9ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

I Dont Know

### What happened?

I Dont know, the Biorand could not make the seed and ask me to report the seed

**Comment by IntelOrca** [comment]
Just a faulty build, fixed in latest
