### ISSUE TITLE
Manhole Opener was out of sequence and/or missing for this RE2 seed

### ISSUE THREAD

**Issue by belkitoFUERTE** [IntelOrca/biorand#746]
### Version

3.1.8 (2f583cd)

### Seed

R721-X0FN-NNHH40V3Z9W2103LZZZZZZZGZZZZZZZZZZZZZZZ05JZVZZZZZ

### Scenario

RE 2 (Leon B)

### Player Character

Nemesis (RE3)

### What happened?

A soft-lock where the manhole opener could not be obtained before proceeding into the sewers. Had to use the debug menu to place it into my inventory. I checked every possible item check throughout the RPD that I know of (I speedrun this game so I do know at the very least 95% of the item placements by heart). Since it's a key item to proceed into the sewers, I needed it. It's possible that the manhole opener could be in the sewers or lab for this seed, but none of the key item checks in the RPD gave it to me. I plan on beating this save tomorrow just to see if the manhole opener is anywhere after the RPD.

**Comment by belkitoFUERTE** [comment]
[Leon B_08_2023-12-30 03^10.20.zip](https://github.com/IntelOrca/biorand/files/13797621/Leon.B_08_2023-12-30.03.10.20.zip)

**Comment by IntelOrca** [comment]
Did you check the spoiler log?

**Comment by belkitoFUERTE** [comment]
Yes! Sorry about the delay. New Year's, etc. 
I did find it. It was in a spot I probably checked but got confused thinking it was still the shotgun ammo. Perhaps I was just seeing things and assumed it was still shotgun ammo since I know the items show what they are in the vanilla game when you open drawers, etc, and then show up as the set item for the seeds in the inventory.

I might have just kept mashing the cancel button thinking it was just shotgun ammo, so my menuing was probably too quick to realize it was in fact the manhole opener.

Thank you for such a quick response and for your time. I really am loving this randomizer. Y'all are absolutely incredible programmers and have truly added more life to my favorite games.
