### ISSUE TITLE
RE2 | Crash at Sewer Entrance after G-Mutant

### ISSUE THREAD

**Issue by Snypehunter007** [IntelOrca/biorand#750]
### Version

3.1.8

### Seed

R720-M2PK-XXHH40M5Z9Y6913JZZZZZZZ5ZZZZZZZZZZZZZZZXZZZVQ5ZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Richard (RE1)

### What happened?

**Description:**
After finishing up the G-Mutant fight and having the talk with Ada (as Marvin) in the room past the boss arena, I went through the next door and was attacked by the giant moth. Ran past it while Ada (now as Sherry with Magnum) fought it. Jumped up on the ledge and picked up one of the two blue herbs there (I think it was the one closest to the door) and the game crashed.

**Save File:**
[Crash Save.zip](https://github.com/IntelOrca/biorand/files/13800240/Crash.Save.zip)
- The save is prior to the G-Mutant fight.

**Comment by IntelOrca** [comment]
Moth crashes should be fixed in dev builds
