### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Indes1992** [IntelOrca/biorand#751]
### Version

3.1.8 (143532d)

### Seed

R721-1TPG-WWHH00J7Z9Y0003T9KWA459FZZZZZZZZZZZZZZZZZZ700TZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Alexia

### What happened?

after the scene where chief Irons dies, going down the ladder game crashes
- going down with Sherry before killing boss
- hearing sound of spiders before crash
- maybe it causes more differend enemies where boss should appear with cutscene instead.

**Comment by Indes1992** [comment]
Happens in Claire Boos room

**Comment by eliotest98** [comment]
I have the same issue with this seed: R722-J88Z-XXZP40M6Z9Y9V07NZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
Scenario Clare A and the Player Character is Jill

**Comment by IntelOrca** [comment]
Should be fixed in latest version
