### ISSUE TITLE
Partner tag along

### ISSUE THREAD

**Issue by ashleycroft** [IntelOrca/biorand#753]
### Version

3.1.8 (2f583cd)

### Seed

R720-Q6VN-XXHH40M5B0YU407J0JM9K014ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Leon (RE6) Ada (RE2R)

### What happened?

How can i get a partner to tag long with me in this biorand and also have a couple of survivors with me?

**Comment by IntelOrca** [comment]
You can find your partner in some of the early rooms. Interact with them and say yes for them to tag along. You can only have one partner at the moment.
