### ISSUE TITLE
RE 1, room 10F, Jill softlock when using music notes

### ISSUE THREAD

**Issue by Tigui91racing** [IntelOrca/biorand#756]
### Version

3.1.8 (2f583cd)

### Seed

R710-L8EC-ZXRF00N559FU0H3NZZZTZMQ8ZZZZZZZZZZZZZZZH2H3KZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Nemesis

### What happened?

I played the Music score on the piano, then the passage open and game freeze, need to alt + f4

**Comment by IntelOrca** [comment]
@Tigui91racing in future, make sure you have the debug menu enabled (F5) so you can reload the room.
