### ISSUE TITLE
An error occurred during seed generation.

### ISSUE THREAD

**Issue by OnSilverwings** [IntelOrca/biorand#765]
### Version

3.2.0 (c468b41)

### Seed

R720-KBJU-XXHH40M5Z9Y0007TZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Random

### What happened?

An error pop up message came up as the seed generation was complete. I have no other details I can share since biorand prompted me that an error had occured.

**Comment by IntelOrca** [comment]
Unable to reproduce, might be a one-off issue.
