### ISSUE TITLE
RE 2, room 601, Leon B crash

### ISSUE THREAD

**Issue by Cael130** [IntelOrca/biorand#769]
### Version

3.2.0 (c468b41)

### Seed

R721-WCRX-XXHH40M5Z9Y9103TZZZRZZZ5ZZZZZZZZZZZZZZZZZZYZZZZZZ

### Scenario

RE 2 (Leon B)

### Player Character

Steve

### What happened?

The Crash to desktop happens right after I obtain "Sherry" (who was RE3 Nikolai) and carry him to the elevator in the lab to use the Master Key to get to the train.. The elevator door opens but after the game crashes. If it helps I also have a partner enabled and it was Ada but with David's voice. I try to use the debug to skip to the elevator as well as past it (I don't think I can because I haven't accessed the train yet.) Skipping to the elevator also causes the crash.

**Comment by Cael130** [comment]
[Leon B_21_2024-01-03 02^30.11.zip](https://github.com/IntelOrca/biorand/files/13816653/Leon.B_21_2024-01-03.02.30.11.zip)
Here is the zip file. I figured it out lol.

**Comment by Neil-F2** [comment]
Can confirm the Crash and also the same thing happened to me in another Seed, Leon B, Hunk was gonna rescue Sherry (Alyssa) and it crash when they were entering the elveator
