### ISSUE TITLE
Failed To Generate

### ISSUE THREAD

**Issue by ToasterAssassin** [IntelOrca/biorand#78]
Hi,

When trying to generate a seed with Resident Evil 2, I get the following error.

Any help is greatly appreciated.

![image_2022-12-18_140112186](https://user-images.githubusercontent.com/120944213/208302612-ea835f7a-1a88-41eb-a0e0-c1ad7b1847f5.png)

**Comment by IntelOrca** [comment]
It looks like there might be an issue with the path you have specified for RE 1. Did you have data in your RE 1 path? Try removing that, if that still doesn't work, can you send me a listing of your RE 1 directory.

**Comment by ToasterAssassin** [comment]
Hello!

That solved the issue! I had a Data folder from a previous mod that I thought was the base directory

Much appreciated, sorry for the hassle.
