### ISSUE TITLE
Can't use square-shaped crank

### ISSUE THREAD

**Issue by Matakomi** [IntelOrca/biorand#780]
### Version

3.2.1 (0770993)

### Seed

R730-EHM4-XXHH4HM5Z9Y0003JRHZZZZZ3ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Leon (Classic)

### What happened?

I got the square-shaped crank. But when trying to use it, nothing happens. 
[01_2024-01-07 17^21.17.zip](https://github.com/IntelOrca/biorand/files/13854864/01_2024-01-07.17.21.17.zip)

**Comment by IntelOrca** [comment]
If you attempt to use the crank before picking up the lockpick in the STARS room, this will happen. The day time version of the room doesn't have the logic to do this event.

**Comment by Matakomi** [comment]
> If you attempt to use the crank before picking up the lockpick in the STARS room, this will happen. The day time version of the room doesn't have the logic to do this event.

Thanks a lot! It worked!
