### ISSUE TITLE
Unbeatable Seed

### ISSUE THREAD

**Issue by TheOnyx1** [IntelOrca/biorand#782]
### Version

3.2.1 (0770993)

### Seed

R730-F6KL-ZXHH4AM449Y2207JVPW9P5Z9ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Ada RE2R

### What happened?

The CHRONOS KEY is missing from room 11B (I believe it is the room called "Sales Office" , the room with the tv remote puzzle). The jill log states it is in this room and I tried clicking everywhere and could not find this key. All other paths on this door rando lead to dead ends and basically I need this key to progress but it didn't spawn.

**Comment by IntelOrca** [comment]
![image](https://github.com/IntelOrca/biorand/assets/1482259/445a077c-859c-4790-9adc-445c13a7c41c)

Here
