### ISSUE TITLE
biorand 2.0.1 RE1 setting message : one or more of your room files are missing.

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#80]
integrity check failed
one or more of your room files did not match the original version.
If you have installed over another mod,issues may occur so proceed with caution!

upload the files list except [movie],[voice],[sound]

![horr](https://user-images.githubusercontent.com/120957601/208308603-2e4ddefd-15ca-4c92-a3da-70b87145bba1.JPG)
![jpn](https://user-images.githubusercontent.com/120957601/208308786-17689836-2a1f-4612-91a6-f2c633f0bc75.JPG)
![stage1](https://user-images.githubusercontent.com/120957601/208308230-aa00668b-f90d-4705-8eee-fdcc63f606a8.JPG)
![stage2](https://user-images.githubusercontent.com/120957601/208308227-094d1e8a-db5f-409b-b4c5-65b1753769ce.JPG)
![stage3](https://user-images.githubusercontent.com/120957601/208308224-c20f9a3c-2b7a-45fe-b068-dbfbdfa37d6e.JPG)
![stage4](https://user-images.githubusercontent.com/120957601/208308222-d9e5f3eb-d85c-4f1e-b961-8ffb7f8a2274.JPG)
![stage5](https://user-images.githubusercontent.com/120957601/208308220-564b8a4d-2d5b-401f-9f80-c94c4f35b3f1.JPG)
![stage6](https://user-images.githubusercontent.com/120957601/208308214-52cba941-c92b-4fe4-adf2-950e8714c3f3.JPG)
![stage7](https://user-images.githubusercontent.com/120957601/208308241-e16e4ce8-1a49-4524-8c3c-5c134060e0dd.JPG)
![data](https://user-images.githubusercontent.com/120957601/20830830
![effspr](https://user-images.githubusercontent.com/120957601/208308339-e7162211-7500-4635-8097-80e447264407.JPG)
9-367343e3-f643-403b-bc9a-5d1e90af6797.JPG)
![enemy](https://user-images.githubusercontent.com/120957601/208308365-1b5d084e-6e19-43fa-816b-e67136227092.JPG)
![players](https://user-images.githubusercontent.com/120957601/208308573-4f9fc9b1-c321-4a62-840c-568f32a2b116.JPG)
![objspr part 1](https://user-images.githubusercontent.com/120957601/208308585-9f02af3d-8b0f-440a-b30f-620333ff6494.JPG)
![objspr part 2](https://user-images.githubusercontent.com/120957601/208308577-03ef7828-6a09-4bf0-969c-89ffe25f5704.JPG)
![item_m1](https://user-images.githubusercontent.com/120957601/208308602-5b8eb52b-bc7d-4f7b-8648-09f9bfbd64a9.JPG)
![item_m2](https://user-images.githubusercontent.com/120957601/208308597-a21e64c1-4670-4b74-85a6-576da42b6b34.JPG)

**Comment by IntelOrca** [comment]
@otamega72 are you still able to play the rando? The message is just a warning, not an error. The warning is because one or more of your RDT files do match the vanilla version that I expect.

In order to investigate further, I will need you to send me all your RDT files.

**Comment by otamega72** [comment]
1) It can generate RE1 random mod , but did not have menifest.txt. I have to create it myself. (Without menifest.txt , we cannot select the mod from drop down menu.) 
2) Only Jill's game can be randomized.
3) Checked the [biorand\stage*] , no any Chris's room had been randomized.

![re1 rand](https://user-images.githubusercontent.com/120957601/208314298-c39316e9-8966-4c2d-afd5-2344709a09e4.JPG)
![biorand stage1](https://user-images.githubusercontent.com/120957601/208314868-cd6d2696-5533-431d-9c6e-86d351feb5cc.JPG)

**Comment by IntelOrca** [comment]
@otamega72 okay, quickest way for me to investigate this issue is for you to zip up your game files and send them to me. You can probably just zip up the RDT files.

**Comment by otamega72** [comment]
[stage1.zip](https://github.com/IntelOrca/biorand/files/10255107/stage1.zip)
[stage2.zip](https://github.com/IntelOrca/biorand/files/10255110/stage2.zip)
[Stage3.zip](https://github.com/IntelOrca/biorand/files/10255111/Stage3.zip)
[Stage4.zip](https://github.com/IntelOrca/biorand/files/10255119/Stage4.zip)
[Stage5.zip](https://github.com/IntelOrca/biorand/files/10255129/Stage5.zip)
[Stage6.zip](https://github.com/IntelOrca/biorand/files/10255134/Stage6.zip)
[Stage7.zip](https://github.com/IntelOrca/biorand/files/10255139/Stage7.zip)

**Comment by IntelOrca** [comment]
@otamega72 I think you must just have a different version of the game to what I test with. Regardless of that, I was still able to generate a rando for both Chris and Jill. After the integrity error pops up, I then get another message saying the rando successfully generated.

**Comment by otamega72** [comment]
v2.0.3 fixed the problems of my RE1 cannot generate Chris's random RDT and missing menifest.txt.
Thanks.
