### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Deucegreenback** [IntelOrca/biorand#801]
### Version

3.2.1 (0770993)

### Seed

R730-2FB6-XXHC2HM5Z9YX002JRZXZQZZ7ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill R3R

### What happened?

Seed has crashed 3 times at the point of getting to cable car and walking into next room within the car where carlos hands jill the side pack, screen goes black then crashes.

**Comment by IntelOrca** [comment]
Sorry, I was unable to reproduce this issue.
I will have to mark it as a duplicate of #352.
