### ISSUE TITLE
Green Gem unobtainable 

### ISSUE THREAD

**Issue by Matakomi** [IntelOrca/biorand#803]
### Version

3.2.3 (5e89e20)

### Seed

R730-HJQR-XXHH4HM5Z9Y0007JZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

Got only Blue Gem. Checked on dgml file, but item is not at designated location.
[mod_biorand.zip](https://github.com/IntelOrca/biorand/files/13999727/mod_biorand.zip)

**Comment by IntelOrca** [comment]
The map on the reception desk in the RPD hall is the green gem.
