### ISSUE TITLE
Emblem key inside shutter door? (EMBLEM KEY x1) in 120:8

### ISSUE THREAD

**Issue by Matakomi** [IntelOrca/biorand#804]
### Version

3.2.3 (5e89e20)

### Seed

R730-VH2U-XNQH4HQ7Z9Y0003J00W000ZZZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Steve

### What happened?

I've checked the dgml file, and looks like the **EMBLEM KEY** is inside the shutter door at the back alley. I have the **CRANK**, but it can't be used before picking up the **LOCKPICK** in the STARS room, which requires the **EMBLEM KEY** that's locked inside the shutter door.
 I could repair the tram, since the last part I need is the **FUSE**, so I could just find it and skip to the next area. I checked at the dgml map file and guess what? The **FUSE** is inside STARS office! XD

Either way, I'm really enjoying this mod. That's why I'm reporting this. 

[mod_biorand.zip](https://github.com/IntelOrca/biorand/files/14002185/mod_biorand.zip)

**Comment by IntelOrca** [comment]
The emblem key is actually the hidden item on the bins which you can get during the day. The items in the shutter will never be ke items for reasons such as this.
