### ISSUE TITLE
3 issues with this cvx seed i tried

### ISSUE THREAD

**Issue by AlbertFnWesker** [IntelOrca/biorand#828]
### Version

3.2.4 (a7dd5a6)

### Seed

R741-ZJRR-JNKK60RAZ7G090ZZ33M9KWZZZZ9FYZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

claire

### What happened?

so i made a cvx seed and couldnt get out of the prison area. 3 things i noticed, 2 items you could see but not pick up,  then an item that you pick up on a shelf that is supposed to trigger a zombie to fall through a window didnt fall thru the window, normally he'd drop guns, so that was another item that i wasnt able to pick up. screenshots provided [zombie window break didnt happen](https://i.imgur.com/1P8w7m5.png) [item next to first typewriter](https://i.imgur.com/unomZlm.png) [item on barrel](https://i.imgur.com/jBKLaLP.png)

**Comment by IntelOrca** [comment]
The trigger boundaires for those 2 items are a big small, just step back a bit and steer until you get them.
Window should now be fixed.
