### ISSUE TITLE
Ben first cutscene softlock

### ISSUE THREAD

**Issue by SkyyOtter** [IntelOrca/biorand#83]
Seed: R420-CR46-XNTA3LYLL52

**Comment by IntelOrca** [comment]
How did it softlock?

**Comment by SkyyOtter** [comment]
Ada was replaced by Rebecca and when she came into the scene, she was turned around and tried walking forward forever.

**Comment by SkyyOtter** [comment]
I've attached a short video. This is Leon A.

https://user-images.githubusercontent.com/121004014/208536850-0b6ecb4e-f784-44cd-8080-04a79dd527a8.mp4

**Comment by IntelOrca** [comment]
NPC swap for Ada has been reverted for now. Eventually a better fix will go in.
