### ISSUE TITLE
CVX: Unable to pickup item in Airport Cargo Bay elevator

### ISSUE THREAD

**Issue by kapdap** [IntelOrca/biorand#831]
### Version

dev

### Seed

R740-TP3C-J4HH40ZZZMEZ9HZZ340ZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

Claire (CVX)

### What happened?

The item that is usually the "Bioharzard Card" on top of the boxes in the Airport Cargo Bay can't be picked up or interacted. Tried moving the character into different positions but it seems to trigger the message for the cargo lift. Have tried 2 different seeds.

```
        Replaced 502:12 [BiohazardCard x1] with 502:12 [RedHerb x1]
```

![image](https://github.com/IntelOrca/biorand/assets/30880441/cc69372a-e8b0-4664-89c5-74181c9f3db6)

**Comment by IntelOrca** [comment]
fixed
