### ISSUE TITLE
biorand 2.0.1 -RE1 Jill crash when CHIMERA killed to die

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#84]
R412-0000-Z1HHHMZL103
Connected 308:2 to 300:0

weapon used : beretta. 
game won't crash if you not to kill them.

300:0 (0x1600C) [CERBERUS,12,0,0,0] becomes [CHIMERA,0,0,0,0]
300:1 (0x16022) [CERBERUS,12,0,0,0] becomes [CHIMERA,0,0,0,0]
300:2 (0x1603E) [CERBERUS,12,0,0,0] becomes [CHIMERA,0,0,0,0]

**Comment by IntelOrca** [comment]
Fixed in 2.0.2
