### ISSUE TITLE
when you use ashley for Claire route A and vote randomized item you will always get crash

### ISSUE THREAD

**Issue by qqwpgg** [IntelOrca/biorand#840]
### Version

3.2.5 (b05b532)

### Seed

R720-RV5M-WLZ100YZZM5Z9HVF06N9P4MR6K50H0000000000000ZZZZZZZZZZ

### Scenario

RE 2 (Claire A)

### Player Character

ashley

### What happened?

when you use ashley for Claire route and randomized item you will get crash

**Comment by qqwpgg** [comment]
![1708484477028](https://github.com/IntelOrca/biorand/assets/160692384/194b5efb-d74e-4dd3-811b-5471aee75e15)
p.s every character in Claire rute crashed when you vote rando item in 2.6

**Comment by AlbertFnWesker** [comment]
i tested it and it works fine. you must have made a seed for claire B, that message pops up when you click the wrong scenario. load a claire B save file.
