### ISSUE TITLE
Re2 Room 202 Marvin as Licker

### ISSUE THREAD

**Issue by kickgripping88** [IntelOrca/biorand#85]
Seed R420-0000-XQHHHMZLLB2 

Claire B, Marvin is replaced by a Licker who attacks during the first encounter with Marvin cut-scene.

**Comment by IntelOrca** [comment]
There is no cut scene for B scenario, not sure what you mean.

**Comment by kickgripping88** [comment]
Sorry I was playing the wrong scenario. But I did find in room 109 of Claire B, instead of crows, spiders spawned and they are invincible.

**Comment by IntelOrca** [comment]
> Sorry I was playing the wrong scenario. But I did find in room 109 of Claire B, instead of crows, spiders spawned and they are invincible.

Probably related to #7
