### ISSUE TITLE
Seed crashing

### ISSUE THREAD

**Issue by patrickbila** [IntelOrca/biorand#852]
### Version

3.2.4 (a2a63e5)

### Seed

R710-G93V-XXHH40M5Z9Y0002JZZZZZ798ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Alexia

### What happened?

When you enter in room 308 (the courtyard B1 where you meed barry and answer his questions the game crash and teh error "Couldn't find file /horr/jpn/24.tmd" is showed up

**Comment by IntelOrca** [comment]
Duplicate of #808
