### ISSUE TITLE
re3 crash's at start

### ISSUE THREAD

**Issue by Chunkbingus420** [IntelOrca/biorand#860]
### Version

3.2.6 (8171900)

### Seed

R730-6PBJ-ZXHH4HZXZM599H9103NH2XVPAZ7ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

murphy

### What happened?

re3 seems to crash as soon as Jill's apartment blows up

**Comment by otamega72** [comment]
Tick [ Rendering Fix] and try again.
![rendering fix](https://github.com/IntelOrca/biorand/assets/120957601/599570cf-d919-4218-b7b9-4884d533bc7c)

**Comment by Chunkbingus420** [comment]
That worked! Thank you so much for you help!
