### ISSUE TITLE
Bug Ink Ribon in Resident evil 2 randomizer Arrange mode Leon A

### ISSUE THREAD

**Issue by Srkamado95** [IntelOrca/biorand#869]
### Version

3.2.6 (8171900)

### Seed

R720-XV0T-XXHH00ZZZMEZ9H0007JZZZZZZZ5ZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Barry

### What happened?

In the initial window of the randomizer I remove the option for Ink Ribon to appear, but even so it appears in the room where you place the two jewels in the Resident Evil 2 randomizer Arrange mode Leon A, this is getting in the way of continuing the game as these Ink Ribons are appearing instead of mission item, an item that is necessary to progress in the game, in my last run it appeared instead of the Crank,

**Comment by IntelOrca** [comment]
Arrange mode should never be used in biorand.
