### ISSUE TITLE
Improve tooltips for door rando sliders

### ISSUE THREAD

**Issue by TharynP** [IntelOrca/biorand#90]
Hi there, on a couple of seeds I noticed that RE1 NPCs can get stuck in cutscenes. For me it was Chris during the Leon, Ben, and Ada cutscene in the jail room, and Rebecca during the part when you play as Ada and come back with items. Not sure if they're getting stuck on geometry or their cutscene AI is bugged. RE2 NPCs seem to work just fine no matter what model is picked.

Another thing, the Door Rando tooltips on the program itself are a little confusing and don't explain what both options do (Number of Segments and Segment Size). It might be easier for others to understand if you explain specifically what each option does according to the rooms. I know a door rando obviously randomizes where doors take you, but in my few previous attempts I'm not sure what the extra options changed other than how long the rando took.

Anyway, this is a great mod and I look forward to future updates! Thank you for your hard work!

**Comment by TharynP** [comment]
Wow, I completely skimmed over the README when first using the rando.
That's my mistake. As for tooltip suggestions;

Number of Segments - "Adjusts how many groups of rooms appear before
reaching the end."

Segment Size - "Adjusts how many rooms are in a group."


That's based on my understanding of the feature after reading the README.
Again, my mistake on that part. Another thing I did notice however, is that
the program seems to forget where the RE1 and RE2 directories are after
exiting it, so I have to select them again when starting up the program.
Not too big of a deal but would be nice if it was fixed.

**Comment by IntelOrca** [comment]
> Another thing I did notice however, is that
the program seems to forget where the RE1 and RE2 directories are after
exiting it, so I have to select them again when starting up the program.
Not too big of a deal but would be nice if it was fixed.

In order to fix this, I need to know how to reproduce the issue. Could you send me your `%APPDATA/biorand/settings.json` file?

**Comment by TharynP** [comment]
Here you go.

**Comment by IntelOrca** [comment]
@TharynP I don't think you attached anything

**Comment by TharynP** [comment]
Oh sorry I replied via email, but github won't actually let me attach the JSON file here. Not a supported file type. You want me to just copy the contents to a TXT file or something?

**Comment by IntelOrca** [comment]
@TharynP if you zip it first, it should be fine.

**Comment by TharynP** [comment]
[settings.zip](https://github.com/IntelOrca/biorand/files/10273820/settings.zip)

The bug actually seems to be gone now, which is strange. I haven't done anything differently, but it's saving the directory paths now. Also, I do want to suggest a feature for the rando which I think would be cool. Do you want me to submit that as a separate issue, or...?

**Comment by IntelOrca** [comment]
Yeah whenever I ask people to send me the file, the issue goes away, making it hard to investigate.
Make a seperate issue for the feature request.
