### ISSUE TITLE
RE1 Crash When Trying to create new save

### ISSUE THREAD

**Issue by Theparky105** [IntelOrca/biorand#904]
### Version

3.2.5 (b05b532)

### Seed

R710-H2X5-5XHH40ZZZMEZ9HE0H7JZZZZZZZ5ZZZZZZZZZZZZZZZW101HZZZZZ

### Scenario

RE 1 (Jill)

### Player Character

Dood (Maximilian Dood Mod)

### What happened?

Game crashes when I try to create the very first new save. So far, it happens in 106-Main Hall (after getting lockpick) and in 118-Room under Stairs (accessing it for the first time). I am using the Maximilian Dood for BioRand mod (ver. 3.1): https://www.moddb.com/mods/biorand/addons/maximiliandood-for-biorand

**Comment by IntelOrca** [comment]
This is an unfortunately an issue with classic rebirth, not biorand. You must create a save in vanilla game first before playing any mod.
