### ISSUE TITLE
Valve Handle unobtainable

### ISSUE THREAD

**Issue by SalioMal573** [IntelOrca/biorand#906]
### Version

3.2.5 (b05b532)

### Seed

R721-8QQR-XXHH40ZZZCBZ9H9007JRZZZZZZ9LPXZZJ9ZQ3GWHZWZZEZZZZZZZ

### Scenario

RE 2 (Leon B)

### Player Character

Carlos (RE3R)

### What happened?

In Resident Evil 2, Leon B Scenario,  The Valve Handle was randomized inside the burning helicopter, which can only be accessed by using the Valve handle to put out the fire.  Item unobtainable without debug menu.

**Comment by IntelOrca** [comment]
Duplicate of #889
