### ISSUE TITLE
Failing to Generate a Seed

### ISSUE THREAD

**Issue by ArashTheGreat** [IntelOrca/biorand#928]
### Version

3.2.7 (ca32730)

### Seed

R820-BB88-XXHGJ0ZZZMEZ9H0007JZZZZZZZEZZZZZZZZZZZZZZZZZZZZZZZYZZZZZZZ

### Scenario

RE 2 (Leon A)

### Player Character

Random

### What happened?

Hi IntelOrca.
Ever since I updated BioRand, my RE2 rando doesn't work at all for some reason. other two games (RE1,RE3) work fine but RE2 in particular doesn't seem to be working. any solutions on how to fix this? thanks!

**Comment by IntelOrca** [comment]
Please re download the latest release again. It was reuploaded to fix this issue.
