### ISSUE TITLE
Using Helmet Key crashes the game

### ISSUE THREAD

**Issue by Soket13** [IntelOrca/biorand#94]
Seed: R410-0000-X5GG4GZL1ZZ

Hi guys, first time playing the random and loving it, but i got an issue after opening a helmet key door the game crash and close.
Anything i set wrong? Any tips what i should mark or do in-game?

**Comment by IntelOrca** [comment]
Were you playing Chris or Jill?

**Comment by Soket13** [comment]
Forgot that,
I was playing Jill with the 2,0,3 version!

**Comment by IntelOrca** [comment]
@Soket13 sorry, I made a mistake in the logic. It should only randomize the helmet key in a door rando, not a non-door rando. The helmet key must only be used after killing plant 42.
