### ISSUE TITLE
Suggestion: Option to include Both Scenarios, 4th Survivor, and Extreme Battle room layouts

### ISSUE THREAD

**Issue by TharynP** [IntelOrca/biorand#98]
In another randomizer I've played before there was an option to have rooms use enemy layouts from other scenarios or game modes. So a room might not have enemies in Scenario A or B but does in Extreme Battle. Or a room in Scenario A has a different layout and enemy count in Scenario B. You could toggle if you wanted to include those room layouts in what gets randomized or keep it the set layout to the scenario you're playing.

**Comment by IntelOrca** [comment]
Rather than use their layouts, I was actually thinking of doing a large enemy update at some point which will randomize enemy quantity, locations and even add them to rooms that don't have enemies in any scenario.

**Comment by TharynP** [comment]
That actually sounds way better. I wasn't sure if creating brand new layouts was possible, so I just suggested what I had seen before. Either way you do it, that'd be an awesome feature.

**Comment by TharynP** [comment]
You think maybe you could also balance it depending on enemy type? I know currently some rooms have a lot of enemies cause it's usually just zombies (like the morgue for example), but then those zombies get switched with say lickers or spiders and suddenly that room is wayyyy more annoying to deal with.

**Comment by IntelOrca** [comment]
> You think maybe you could also balance it depending on enemy type? I know currently some rooms have a lot of enemies cause it's usually just zombies (like the morgue for example), but then those zombies get switched with say lickers or spiders and suddenly that room is wayyyy more annoying to deal with.

To some degree, currently certain rooms are excluded from spawning lickers, tyrants or Ivys if if enemy difficulty is low.

**Comment by IntelOrca** [comment]
Random enemy locations implemented in 1.2.4.
