### ISSUE TITLE
[v2.0.3] Sherry+Voicelines not randomized after Birkin fight in Iron's Basement Claire B 

### ISSUE THREAD

**Issue by AfkKun** [IntelOrca/biorand#99]
Seed: R420-88AB-XTKA4B33L53

After fighting Birkin and going down the elevator in Irons office with Sherry:  Sherry model + Voicelines of Claire/Sherry cutscenes are not randomized until after the Platform fight

**Comment by IntelOrca** [comment]
Sherry can't be randomized as any other character will prevent you from going through the doors due to the "I must wait for Sherry" message.

The voice lines are now randomized though.
